'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.573
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization

'
'This source code was auto-generated by xsd, Version=1.1.4322.573.
'
Namespace wsTravelTalk.wmAirRulesIn_v03

    '<remarks/>
    <System.Xml.Serialization.XmlRootAttribute(IsNullable:=False)>
    Public Class Address

        '<remarks/>
        Public StreetNmbr As StreetNmbr

        '<remarks/>
        Public BldgRoom As String

        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("AddressLine")>
        Public AddressLine() As String

        '<remarks/>
        Public CityName As String

        '<remarks/>
        Public PostalCode As String

        '<remarks/>
        Public County As String

        '<remarks/>
        Public StateProv As StateProv

        '<remarks/>
        Public CountryName As CountryName

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(),
         System.ComponentModel.DefaultValueAttribute(False)>
        Public FormattedInd As Boolean = False

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public ShareSynchInd As AddressShareSynchInd

        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>
        Public ShareSynchIndSpecified As Boolean

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public ShareMarketInd As AddressShareMarketInd

        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>
        Public ShareMarketIndSpecified As Boolean

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public Type As String
    End Class

    '<remarks/>
    <System.Xml.Serialization.XmlRootAttribute(IsNullable:=False)>
    Public Class StreetNmbr

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public PO_Box As String

        '<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()>
        Public Value As String
    End Class

    '<remarks/>
    <System.Xml.Serialization.XmlRootAttribute(IsNullable:=False)>
    Public Class CountryName

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public Code As String

        '<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()>
        Public Value As String
    End Class

    '<remarks/>
    <System.Xml.Serialization.XmlRootAttribute(IsNullable:=False)>
    Public Class StateProv

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public StateCode As String

        '<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()>
        Public Value As String
    End Class

    '<remarks/>
    Public Enum AddressShareSynchInd

        '<remarks/>
        Yes

        '<remarks/>
        No

        '<remarks/>
        Inherit
    End Enum

    '<remarks/>
    Public Enum AddressShareMarketInd

        '<remarks/>
        Yes

        '<remarks/>
        No

        '<remarks/>
        Inherit
    End Enum

    '<remarks/>
    <System.Xml.Serialization.XmlRootAttribute(IsNullable:=False)>
    Public Class AirTraveler

        '<remarks/>
        Public ProfileRef As ProfileRef

        '<remarks/>
        Public PersonName As PersonName

        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Telephone")>
        Public Telephone() As Telephone

        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Email")>
        Public Email() As Email

        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Address")>
        Public Address() As Address

        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("CustLoyalty")>
        Public CustLoyalty() As CustLoyalty

        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Document")>
        Public Document() As Document

        '<remarks/>
        Public PassengerTypeQuantity As PassengerTypeQuantity

        '<remarks/>
        Public TravelerRefNumber As TravelerRefNumber

        '<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("FlightSegmentRPH", IsNullable:=False)>
        Public FlightSegmentRPHs() As String

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public Gender As AirTravelerGender

        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>
        Public GenderSpecified As Boolean

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public ShareSynchInd As AirTravelerShareSynchInd

        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>
        Public ShareSynchIndSpecified As Boolean

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public ShareMarketInd As AirTravelerShareMarketInd

        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>
        Public ShareMarketIndSpecified As Boolean

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="date")>
        Public BirthDate As Date

        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>
        Public BirthDateSpecified As Boolean

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public CurrencyCode As String

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public PassengerTypeCode As String

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public AccompaniedByInfant As Boolean

        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>
        Public AccompaniedByInfantSpecified As Boolean
    End Class

    '<remarks/>
    <System.Xml.Serialization.XmlRootAttribute(IsNullable:=False)>
    Public Class ProfileRef

        '<remarks/>
        Public UniqueID As UniqueID
    End Class

    '<remarks/>
    <System.Xml.Serialization.XmlRootAttribute(IsNullable:=False)>
    Public Class UniqueID

        '<remarks/>
        Public CompanyName As CompanyName

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="anyURI")>
        Public URL As String

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public Type As String

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public Instance As String

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public ID As String

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public ID_Context As String
    End Class

    '<remarks/>
    <System.Xml.Serialization.XmlRootAttribute(IsNullable:=False)>
    Public Class CompanyName

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public CompanyShortName As String

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public TravelSector As String

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public Code As String

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public CodeContext As String

        '<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()>
        Public Value As String
    End Class

    '<remarks/>
    <System.Xml.Serialization.XmlRootAttribute(IsNullable:=False)>
    Public Class PersonName

        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("NamePrefix")>
        Public NamePrefix() As String

        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("GivenName")>
        Public GivenName() As String

        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("MiddleName")>
        Public MiddleName() As String

        '<remarks/>
        Public SurnamePrefix As String

        '<remarks/>
        Public Surname As String

        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("NameSuffix")>
        Public NameSuffix() As String

        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("NameTitle")>
        Public NameTitle() As String

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public ShareSynchInd As PersonNameShareSynchInd

        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>
        Public ShareSynchIndSpecified As Boolean

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public ShareMarketInd As PersonNameShareMarketInd

        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>
        Public ShareMarketIndSpecified As Boolean

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public NameType As String
    End Class

    '<remarks/>
    Public Enum PersonNameShareSynchInd

        '<remarks/>
        Yes

        '<remarks/>
        No

        '<remarks/>
        Inherit
    End Enum

    '<remarks/>
    Public Enum PersonNameShareMarketInd

        '<remarks/>
        Yes

        '<remarks/>
        No

        '<remarks/>
        Inherit
    End Enum

    '<remarks/>
    <System.Xml.Serialization.XmlRootAttribute(IsNullable:=False)>
    Public Class Telephone

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public ShareSynchInd As TelephoneShareSynchInd

        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>
        Public ShareSynchIndSpecified As Boolean

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public ShareMarketInd As TelephoneShareMarketInd

        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>
        Public ShareMarketIndSpecified As Boolean

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public PhoneLocationType As String

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public PhoneTechType As String

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public CountryAccessCode As String

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public AreaCityCode As String

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public PhoneNumber As String

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public Extension As String

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public PIN As String

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(),
         System.ComponentModel.DefaultValueAttribute(False)>
        Public FormattedInd As Boolean = False
    End Class

    '<remarks/>
    Public Enum TelephoneShareSynchInd

        '<remarks/>
        Yes

        '<remarks/>
        No

        '<remarks/>
        Inherit
    End Enum

    '<remarks/>
    Public Enum TelephoneShareMarketInd

        '<remarks/>
        Yes

        '<remarks/>
        No

        '<remarks/>
        Inherit
    End Enum

    '<remarks/>
    <System.Xml.Serialization.XmlRootAttribute(IsNullable:=False)>
    Public Class Email

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public ShareSynchInd As EmailShareSynchInd

        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>
        Public ShareSynchIndSpecified As Boolean

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public ShareMarketInd As EmailShareMarketInd

        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>
        Public ShareMarketIndSpecified As Boolean

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(),
         System.ComponentModel.DefaultValueAttribute(False)>
        Public DefaultInd As Boolean = False

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public EmailType As String

        '<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()>
        Public Value As String
    End Class

    '<remarks/>
    Public Enum EmailShareSynchInd

        '<remarks/>
        Yes

        '<remarks/>
        No

        '<remarks/>
        Inherit
    End Enum

    '<remarks/>
    Public Enum EmailShareMarketInd

        '<remarks/>
        Yes

        '<remarks/>
        No

        '<remarks/>
        Inherit
    End Enum

    '<remarks/>
    <System.Xml.Serialization.XmlRootAttribute(IsNullable:=False)>
    Public Class CustLoyalty

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public ShareSynchInd As CustLoyaltyShareSynchInd

        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>
        Public ShareSynchIndSpecified As Boolean

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public ShareMarketInd As CustLoyaltyShareMarketInd

        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>
        Public ShareMarketIndSpecified As Boolean

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public ProgramID As String

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public MembershipID As String

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public TravelSector As String

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public LoyalLevel As String

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public SingleVendorInd As CustLoyaltySingleVendorInd

        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>
        Public SingleVendorIndSpecified As Boolean

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="date")>
        Public SignupDate As Date

        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>
        Public SignupDateSpecified As Boolean

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="date")>
        Public EffectiveDate As Date

        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>
        Public EffectiveDateSpecified As Boolean

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="date")>
        Public ExpireDate As Date

        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>
        Public ExpireDateSpecified As Boolean

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public RPH As String
    End Class

    '<remarks/>
    Public Enum CustLoyaltyShareSynchInd

        '<remarks/>
        Yes

        '<remarks/>
        No

        '<remarks/>
        Inherit
    End Enum

    '<remarks/>
    Public Enum CustLoyaltyShareMarketInd

        '<remarks/>
        Yes

        '<remarks/>
        No

        '<remarks/>
        Inherit
    End Enum

    '<remarks/>
    Public Enum CustLoyaltySingleVendorInd

        '<remarks/>
        SingleVndr

        '<remarks/>
        Alliance
    End Enum

    '<remarks/>
    <System.Xml.Serialization.XmlRootAttribute(IsNullable:=False)>
    Public Class Document

        '<remarks/>
        Public DocHolderName As String

        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("DocLimitations")>
        Public DocLimitations() As String

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public ShareSynchInd As DocumentShareSynchInd

        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>
        Public ShareSynchIndSpecified As Boolean

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public ShareMarketInd As DocumentShareMarketInd

        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>
        Public ShareMarketIndSpecified As Boolean

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public DocIssueAuthority As String

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public DocIssueLocation As String

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public DocID As String

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public DocType As String

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public Gender As DocumentGender

        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>
        Public GenderSpecified As Boolean

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="date")>
        Public BirthDate As Date

        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>
        Public BirthDateSpecified As Boolean

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="date")>
        Public EffectiveDate As Date

        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>
        Public EffectiveDateSpecified As Boolean

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="date")>
        Public ExpireDate As Date

        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>
        Public ExpireDateSpecified As Boolean
    End Class

    '<remarks/>
    Public Enum DocumentShareSynchInd

        '<remarks/>
        Yes

        '<remarks/>
        No

        '<remarks/>
        Inherit
    End Enum

    '<remarks/>
    Public Enum DocumentShareMarketInd

        '<remarks/>
        Yes

        '<remarks/>
        No

        '<remarks/>
        Inherit
    End Enum

    '<remarks/>
    Public Enum DocumentGender

        '<remarks/>
        Male

        '<remarks/>
        Female

        '<remarks/>
        Unknown
    End Enum

    '<remarks/>
    <System.Xml.Serialization.XmlRootAttribute(IsNullable:=False)>
    Public Class TravelerRefNumber

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public RPH As String
    End Class

    '<remarks/>
    Public Enum AirTravelerGender

        '<remarks/>
        Male

        '<remarks/>
        Female

        '<remarks/>
        Unknown
    End Enum

    '<remarks/>
    Public Enum AirTravelerShareSynchInd

        '<remarks/>
        Yes

        '<remarks/>
        No

        '<remarks/>
        Inherit
    End Enum

    '<remarks/>
    Public Enum AirTravelerShareMarketInd

        '<remarks/>
        Yes

        '<remarks/>
        No

        '<remarks/>
        Inherit
    End Enum

    '<remarks/>
    <System.Xml.Serialization.XmlRootAttribute(IsNullable:=False)>
    Public Class AirTravelerAvail

        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("PassengerTypeQuantity")>
        Public PassengerTypeQuantity() As PassengerTypeQuantity

        '<remarks/>
        Public AirTraveler As AirTraveler
    End Class

    '<remarks/>
    <System.Xml.Serialization.XmlRootAttribute(IsNullable:=False)>
    Public Class BookingChannel

        '<remarks/>
        Public CompanyName As CompanyName

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public Type As String

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public Primary As Boolean

        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>
        Public PrimarySpecified As Boolean
    End Class

    '<remarks/>
    <System.Xml.Serialization.XmlRootAttribute(IsNullable:=False)>
    Public Class FlightSegmentRPHs

        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("FlightSegmentRPH")>
        Public FlightSegmentRPH() As String
    End Class

    '<remarks/>
    <System.Xml.Serialization.XmlRootAttribute(IsNullable:=False)>
    Public Class NegotiatedFareCode

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public Code As String

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public CodeContext As String

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="anyURI")>
        Public URI As String

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public Quantity As Integer

        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>
        Public QuantitySpecified As Boolean

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public SecondaryCode As String

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public SupplierCode As String

        '<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()>
        Public Value As String
    End Class

    '<remarks/>
    <System.Xml.Serialization.XmlRootAttribute(IsNullable:=False)>
    Public Class OTA_AirRulesRQ

        '<remarks/>
        Public POS As POS

        '<remarks/>
        Public AirItinerary As AirItinerary

        '<remarks/>
        Public TravelerInfoSummary As TravelerInfoSummary

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public EchoToken As String

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public TimeStamp As Date

        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>
        Public TimeStampSpecified As Boolean

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(),
         System.ComponentModel.DefaultValueAttribute(OTA_AirRulesRQTarget.Production)>
        Public Target As OTA_AirRulesRQTarget = OTA_AirRulesRQTarget.Production

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public Version As Double

        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>
        Public VersionSpecified As Boolean

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public TransactionIdentifier As String

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public SequenceNmbr As Integer

        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>
        Public SequenceNmbrSpecified As Boolean

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public TransactionStatusCode As OTA_AirRulesRQTransactionStatusCode

        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>
        Public TransactionStatusCodeSpecified As Boolean

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public PrimaryLangID As String

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public AltLangID As String
    End Class

    '<remarks/>
    <System.Xml.Serialization.XmlRootAttribute(IsNullable:=False)>
    Public Class POS

        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Source")>
        Public Source() As Source

        '<remarks/>
        Public TPA_Extensions As TPA_Extensions
    End Class

    '<remarks/>
    <System.Xml.Serialization.XmlRootAttribute(IsNullable:=False)>
    Public Class Source

        '<remarks/>
        Public RequestorID As RequestorID

        '<remarks/>
        Public Position As Position

        '<remarks/>
        Public BookingChannel As BookingChannel

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public AgentSine As String

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public PseudoCityCode As String

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public ISOCountry As String

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public ISOCurrency As String

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public AgentDutyCode As String

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public AirlineVendorID As String

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public AirportCode As String

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public FirstDepartPoint As String

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public ERSP_UserID As String
    End Class

    '<remarks/>
    <System.Xml.Serialization.XmlRootAttribute(IsNullable:=False)>
    Public Class RequestorID

        '<remarks/>
        Public CompanyName As CompanyName

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="anyURI")>
        Public URL As String

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public Type As String

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public Instance As String

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public ID As String

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public ID_Context As String
    End Class

    '<remarks/>
    <System.Xml.Serialization.XmlRootAttribute(IsNullable:=False)>
    Public Class Position

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public Latitude As String

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public Longitude As String

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public Altitude As String
    End Class

    '<remarks/>
    <System.Xml.Serialization.XmlRootAttribute(IsNullable:=False)>
    Public Class TPA_Extensions

        '<remarks/>
        Public Provider As Provider
        Public ConversationID As String
    End Class

    '<remarks/>
    <System.Xml.Serialization.XmlRootAttribute(IsNullable:=False)>
    Public Class Provider

        '<remarks/>
        Public Name As String

        '<remarks/>
        Public System As String

        '<remarks/>
        Public Userid As String

        '<remarks/>
        Public Password As String
    End Class

    '<remarks/>
    <System.Xml.Serialization.XmlRootAttribute(IsNullable:=False)>
    Public Class TravelerInfoSummary

        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("SeatsRequested")>
        Public SeatsRequested() As Integer

        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("AirTravelerAvail")>
        Public AirTravelerAvail() As AirTravelerAvail

        '<remarks/>
        Public PriceRequestInformation As PriceRequestInformation
    End Class

    '<remarks/>
    <System.Xml.Serialization.XmlRootAttribute(IsNullable:=False)>
    Public Class PriceRequestInformation

        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("NegotiatedFareCode")>
        Public NegotiatedFareCode() As NegotiatedFareCode

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public FareQualifier As String

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public NegotiatedFaresOnly As Boolean

        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>
        Public NegotiatedFaresOnlySpecified As Boolean

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public CurrencyCode As String

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public PricingSource As PriceRequestInformationPricingSource

        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>
        Public PricingSourceSpecified As Boolean

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public Reprice As Boolean

        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>
        Public RepriceSpecified As Boolean

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public ValidatingAirlineCode As String
    End Class

    '<remarks/>
    <System.Xml.Serialization.XmlRootAttribute(IsNullable:=False)>
    Public Class PassengerTypeQuantity

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public Age As Integer

        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>
        Public AgeSpecified As Boolean

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public Code As String

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public CodeContext As String

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="anyURI")>
        Public URI As String

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public Quantity As Integer

        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>
        Public QuantitySpecified As Boolean

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(),
         System.ComponentModel.DefaultValueAttribute(True)>
        Public Changeable As Boolean = True
    End Class

    '<remarks/>
    <System.Xml.Serialization.XmlRootAttribute(IsNullable:=False)>
    Public Class AirItinerary

        '<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("OriginDestinationOption", IsNullable:=False),
         System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=False, NestingLevel:=1)>
        Public OriginDestinationOptions()() As FlightSegment

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public DirectionInd As AirItineraryDirectionInd

        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>
        Public DirectionIndSpecified As Boolean
    End Class

    '<remarks/>
    <System.Xml.Serialization.XmlRootAttribute(IsNullable:=False)>
    Public Class FlightSegment

        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("DepartureAirport")>
        Public DepartureAirport As DepartureAirportv03

        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("ArrivalAirport")>
        Public ArrivalAirport As ArrivalAirportv03

        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("OperatingAirline")>
        Public OperatingAirline As OperatingAirlinev03

        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Equipment")>
        Public Equipment() As Equipment

        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("MarketingAirline")>
        Public MarketingAirline As MarketingAirlinev03

        '<remarks/>
        Public MarriageGrp As String

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public DepartureDateTime As String

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public ArrivalDateTime As String

        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>
        Public ArrivalDateTimeSpecified As Boolean

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public StopQuantity As Integer

        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>
        Public StopQuantitySpecified As Boolean

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public RPH As String

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public InfoSource As String

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public FlightNumber As String

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public TourOperatorFlightID As String

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public ResBookDesigCode As String

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public ActionCode As FlightSegmentActionCode

        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>
        Public ActionCodeSpecified As Boolean

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public NumberInParty As Integer

        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>
        Public NumberInPartySpecified As Boolean
    End Class

    '<remarks/>
    <System.Xml.Serialization.XmlRootAttribute(IsNullable:=False)>
    Public Class DepartureAirportv03

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public LocationCode As String

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(),
         System.ComponentModel.DefaultValueAttribute("IATA")>
        Public CodeContext As String = "IATA"

        '<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()>
        Public Value As String
    End Class

    '<remarks/>
    <System.Xml.Serialization.XmlRootAttribute(IsNullable:=False)>
    Public Class ArrivalAirportv03

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public LocationCode As String

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(),
         System.ComponentModel.DefaultValueAttribute("IATA")>
        Public CodeContext As String = "IATA"

        '<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()>
        Public Value As String
    End Class

    '<remarks/>
    <System.Xml.Serialization.XmlRootAttribute(IsNullable:=False)>
    Public Class OperatingAirlinev03

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public CompanyShortName As String

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public TravelSector As String

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public Code As String

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public CodeContext As String

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public FlightNumber As String

        '<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()>
        Public Value As String


    End Class

    '<remarks/>
    <System.Xml.Serialization.XmlRootAttribute(IsNullable:=False)>
    Public Class MarketingAirlinev03

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public CompanyShortName As String

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public TravelSector As String

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public Code As String

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public CodeContext As String

        '<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()>
        Public Value As String
    End Class

    '<remarks/>
    <System.Xml.Serialization.XmlRootAttribute(IsNullable:=False)>
    Public Class Equipment

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public AirEquipType As String

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(),
         System.ComponentModel.DefaultValueAttribute(False)>
        Public ChangeofGauge As Boolean = False

        '<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()>
        Public Value As String
    End Class

    '<remarks/>
    Public Enum FlightSegmentActionCode

        '<remarks/>
        OK

        '<remarks/>
        Waitlist

        '<remarks/>
        Other
    End Enum

    '<remarks/>
    Public Enum AirItineraryDirectionInd

        '<remarks/>
        OneWay

        '<remarks/>
        [Return]

        '<remarks/>
        Circle

        '<remarks/>
        OpenJaw

        '<remarks/>
        Other
    End Enum

    '<remarks/>
    Public Enum PriceRequestInformationPricingSource

        '<remarks/>
        Published

        '<remarks/>
        [Private]

        '<remarks/>
        Both
    End Enum

    '<remarks/>
    Public Enum OTA_AirRulesRQTarget

        '<remarks/>
        Test

        '<remarks/>
        Production
    End Enum

    '<remarks/>
    Public Enum OTA_AirRulesRQTransactionStatusCode

        '<remarks/>
        Start

        '<remarks/>
        [End]

        '<remarks/>
        Rollback

        '<remarks/>
        InSeries
    End Enum

End Namespace
