@echo off
rem setlocal
set path=C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools;%path%

xsltc /settings:document+,script+ AmadeusWS_AirAvailRQ.xsl
xsltc /settings:document+,script+ AmadeusWS_AirAvailRS.xsl
xsltc /settings:document+,script+ AmadeusWS_AirFlifoRQ.xsl
xsltc /settings:document+,script+ AmadeusWS_AirFlifoRS.xsl
xsltc /settings:document+,script+ AmadeusWS_AirPriceRQ.xsl
xsltc /settings:document+,script+ AmadeusWS_AirPriceRS.xsl
xsltc /settings:document+,script+ AmadeusWS_AirPrice1RS.xsl
xsltc /settings:document+,script+ AmadeusWS_AirRulesRQ.xsl
xsltc /settings:document+,script+ AmadeusWS_AirRulesRS.xsl
xsltc /settings:document+,script+ AmadeusWS_AirScheduleRQ.xsl
xsltc /settings:document+,script+ AmadeusWS_AirScheduleRS.xsl
xsltc /settings:document+,script+ AmadeusWS_AirSeatMapRQ.xsl
xsltc /settings:document+,script+ AmadeusWS_AirSeatMapRS.xsl
xsltc /settings:document+,script+ AmadeusWS_CarAvailRQ.xsl
xsltc /settings:document+,script+ AmadeusWS_CarAvailRS.xsl
xsltc /settings:document+,script+ AmadeusWS_CarInfoRQ.xsl
xsltc /settings:document+,script+ AmadeusWS_CarInfoRS.xsl
xsltc /settings:document+,script+ AmadeusWS_CarListRQ.xsl
xsltc /settings:document+,script+ AmadeusWS_CarListRS.xsl
xsltc /settings:document+,script+ AmadeusWS_CarRulesRQ.xsl
xsltc /settings:document+,script+ AmadeusWS_CarRulesRS.xsl
xsltc /settings:document+,script+ AmadeusWS_CCValidRQ.xsl
xsltc /settings:document+,script+ AmadeusWS_CCValidRS.xsl
xsltc /settings:document+,script+ AmadeusWS_CruiseCabinAvailRQ.xsl
xsltc /settings:document+,script+ AmadeusWS_CruiseCabinAvailRS.xsl
xsltc /settings:document+,script+ AmadeusWS_CruiseCabinHoldRQ.xsl
xsltc /settings:document+,script+ AmadeusWS_CruiseCabinHoldRS.xsl
xsltc /settings:document+,script+ AmadeusWS_CruiseCabinUnHoldRQ.xsl
xsltc /settings:document+,script+ AmadeusWS_CruiseCabinUnHoldRS.xsl
xsltc /settings:document+,script+ AmadeusWS_CruiseCancelRQ.xsl
xsltc /settings:document+,script+ AmadeusWS_CruiseCancelRS.xsl
xsltc /settings:document+,script+ AmadeusWS_CruiseCategoryAvailRQ.xsl
xsltc /settings:document+,script+ AmadeusWS_CruiseCategoryAvailRS.xsl
xsltc /settings:document+,script+ AmadeusWS_CruiseCreateBookingRQ.xsl
xsltc /settings:document+,script+ AmadeusWS_CruiseCreateBookingRS.xsl
xsltc /settings:document+,script+ AmadeusWS_CruiseFareAvailRQ.xsl
xsltc /settings:document+,script+ AmadeusWS_CruiseFareAvailRS.xsl
xsltc /settings:document+,script+ AmadeusWS_CruiseItineraryDescRQ.xsl
xsltc /settings:document+,script+ AmadeusWS_CruiseItineraryDescRS.xsl
xsltc /settings:document+,script+ AmadeusWS_CruiseModifyBookingRQ.xsl
xsltc /settings:document+,script+ AmadeusWS_CruisePackageAvailRQ.xsl
xsltc /settings:document+,script+ AmadeusWS_CruisePackageAvailRS.xsl
xsltc /settings:document+,script+ AmadeusWS_CruisePackageDescRQ.xsl
xsltc /settings:document+,script+ AmadeusWS_CruisePackageDescRS.xsl
xsltc /settings:document+,script+ AmadeusWS_CruisePriceBookingRQ.xsl
xsltc /settings:document+,script+ AmadeusWS_CruisePriceBookingRQ1.xsl
xsltc /settings:document+,script+ AmadeusWS_CruisePriceBookingRS.xsl
xsltc /settings:document+,script+ AmadeusWS_CruiseReadRQ.xsl
xsltc /settings:document+,script+ AmadeusWS_CruiseReadRS.xsl
xsltc /settings:document+,script+ AmadeusWS_CruiseSailAvailRQ.xsl
xsltc /settings:document+,script+ AmadeusWS_CruiseSailAvailRS.xsl
xsltc /settings:document+,script+ AmadeusWS_CruiseTransferAvailRQ.xsl
xsltc /settings:document+,script+ AmadeusWS_CruiseTransferAvailRS.xsl
xsltc /settings:document+,script+ AmadeusWS_CrypticRQ.xsl
xsltc /settings:document+,script+ AmadeusWS_CrypticRS.xsl
xsltc /settings:document+,script+ AmadeusWS_CurConvRQ.xsl
xsltc /settings:document+,script+ AmadeusWS_CurConvRS.xsl
xsltc /settings:document+,script+ AmadeusWS_DisplayTicketRQ.xsl
xsltc /settings:document+,script+ AmadeusWS_FareDisplayRQ.xsl
xsltc /settings:document+,script+ AmadeusWS_FareDisplayRS.xsl
xsltc /settings:document+,script+ AmadeusWS_FareInfoRQ.xsl
xsltc /settings:document+,script+ AmadeusWS_FareInfoRS.xsl
xsltc /settings:document+,script+ AmadeusWS_HotelAvail_FeaturesRS.xsl
xsltc /settings:document+,script+ AmadeusWS_HotelAvailRQ.xsl
xsltc /settings:document+,script+ AmadeusWS_HotelAvailRS.xsl
xsltc /settings:document+,script+ AmadeusWS_HotelInfoRQ.xsl
xsltc /settings:document+,script+ AmadeusWS_HotelInfo1RQ.xsl
xsltc /settings:document+,script+ AmadeusWS_HotelInfoRS.xsl
xsltc /settings:document+,script+ AmadeusWS_HotelSearchRQ.xsl
xsltc /settings:document+,script+ AmadeusWS_HotelSearchRS.xsl
xsltc /settings:document+,script+ AmadeusWS_IssueTicketRQ.xsl
xsltc /settings:document+,script+ AmadeusWS_IssueTicketRS.xsl
xsltc /settings:document+,script+ AmadeusWS_IssueTicketSessionedRQ.xsl
xsltc /settings:document+,script+ AmadeusWS_IssueTicketSessionedRS.xsl
xsltc /settings:document+,script+ AmadeusWS_LowFare1RS.xsl
xsltc /settings:document+,script+ AmadeusWS_LowFare2RS.xsl
xsltc /settings:document+,script+ AmadeusWS_LowFareRQ.xsl
xsltc /settings:document+,script+ AmadeusWS_LowFarePlus1RS.xsl
xsltc /settings:document+,script+ AmadeusWS_LowFarePlus2RS.xsl
xsltc /settings:document+,script+ AmadeusWS_LowFarePlusRQ.xsl
xsltc /settings:document+,script+ AmadeusWS_LowFareMatrix1RS.xsl
xsltc /settings:document+,script+ AmadeusWS_LowFareMatrix2RS.xsl
xsltc /settings:document+,script+ AmadeusWS_LowFareMatrixRQ.xsl
xsltc /settings:document+,script+ AmadeusWS_LowFareFlightsRQ.xsl
xsltc /settings:document+,script+ AmadeusWS_LowFareFlights1RQ.xsl
xsltc /settings:document+,script+ AmadeusWS_LowFareFlights2RQ.xsl
xsltc /settings:document+,script+ AmadeusWS_LowFareFlightsRS.xsl
xsltc /settings:document+,script+ AmadeusWS_LowFareFlights1RS.xsl
xsltc /settings:document+,script+ AmadeusWS_LowFareFlights3RS.xsl
xsltc /settings:document+,script+ AmadeusWS_LowFareScheduleRQ.xsl
xsltc /settings:document+,script+ AmadeusWS_LowFareScheduleRS.xsl
xsltc /settings:document+,script+ AmadeusWS_LowOfferMatrix1RS.xsl
xsltc /settings:document+,script+ AmadeusWS_LowOfferMatrix2RS.xsl
xsltc /settings:document+,script+ AmadeusWS_LowOfferMatrixRQ.xsl
xsltc /settings:document+,script+ AmadeusWS_LowOfferSearch1RS.xsl
xsltc /settings:document+,script+ AmadeusWS_LowOfferSearch2RS.xsl
xsltc /settings:document+,script+ AmadeusWS_LowOfferSearchRQ.xsl
xsltc /settings:document+,script+ AmadeusWS_PNRCancelRQ.xsl
xsltc /settings:document+,script+ AmadeusWS_PNRCancelRS.xsl
xsltc /settings:document+,script+ AmadeusWS_PNREndRQ.xsl
xsltc /settings:document+,script+ AmadeusWS_PNRReadRQ.xsl
xsltc /settings:document+,script+ AmadeusWS_PNRReadRS.xsl
xsltc /settings:document+,script+ AmadeusWS_PNRReadRS_Rules.xsl
xsltc /settings:document+,script+ AmadeusWS_PNRReadRS_FlightInfo.xsl
xsltc /settings:document+,script+ AmadeusWS_PNRRepriceRQ.xsl
xsltc /settings:document+,script+ AmadeusWS_PNRRepriceRS.xsl
xsltc /settings:document+,script+ AmadeusWS_PNRSplitRQ.xsl
xsltc /settings:document+,script+ AmadeusWS_QueueReadRQ.xsl
xsltc /settings:document+,script+ AmadeusWS_QueueReadRS.xsl
xsltc /settings:document+,script+ AmadeusWS_QueueRQ.xsl
xsltc /settings:document+,script+ AmadeusWS_QueueRS.xsl
xsltc /settings:document+,script+ AmadeusWS_RefundTicketRQ.xsl
xsltc /settings:document+,script+ AmadeusWS_RefundTicketRS.xsl
xsltc /settings:document+,script+ AmadeusWS_SalesReportRQ.xsl
xsltc /settings:document+,script+ AmadeusWS_SalesReportRS.xsl
xsltc /settings:document+,script+ AmadeusWS_SearchNameRQ.xsl
xsltc /settings:document+,script+ AmadeusWS_SearchNameRS.xsl
xsltc /settings:document+,script+ AmadeusWS_ShowMileageRQ.xsl
xsltc /settings:document+,script+ AmadeusWS_ShowMileageRS.xsl
xsltc /settings:document+,script+ AmadeusWS_StoredFareBuildRQ.xsl
xsltc /settings:document+,script+ AmadeusWS_StoredFareBuildRS.xsl
xsltc /settings:document+,script+ AmadeusWS_StoredFareUpdateRQ.xsl
xsltc /settings:document+,script+ AmadeusWS_StoredFareUpdateRS.xsl
xsltc /settings:document+,script+ AmadeusWS_TB_Errors.xsl
xsltc /settings:document+,script+ AmadeusWS_TimeDiffRQ.xsl
xsltc /settings:document+,script+ AmadeusWS_TimeDiffRS.xsl
xsltc /settings:document+,script+ AmadeusWS_TransferOwnershipRQ.xsl
xsltc /settings:document+,script+ AmadeusWS_TransferOwnershipRS.xsl
xsltc /settings:document+,script+ AmadeusWS_TravelBuildRQ.xsl
xsltc /settings:document+,script+ AmadeusWS_UpdateDeleteRQ.xsl
xsltc /settings:document+,script+ AmadeusWS_UpdateInsertRQ.xsl
xsltc /settings:document+,script+ AmadeusWS_UpdateModifyRQ.xsl
xsltc /settings:document+,script+ AmadeusWS_VoidTicketRQ.xsl
xsltc /settings:document+,script+ SellIssuesRQ.xsl
xsltc /settings:document+,script+ v02_AmadeusWS_HotelAvailRQ.xsl
xsltc /settings:document+,script+ v02_AmadeusWS_HotelAvailRS.xsl
xsltc /settings:document+,script+ v02_AmadeusWS_HotelInfo1RQ.xsl
xsltc /settings:document+,script+ v03_AmadeusWS_AirAvailRQ.xsl
xsltc /settings:document+,script+ v03_AmadeusWS_AirAvailRQ1.xsl
xsltc /settings:document+,script+ v03_AmadeusWS_AirAvailRS.xsl
xsltc /settings:document+,script+ v03_AmadeusWS_AirAvailRPHRS.xsl
xsltc /settings:document+,script+ v03_AmadeusWS_AirPriceRQ.xsl
xsltc /settings:document+,script+ v03_AmadeusWS_AirPriceRS.xsl
xsltc /settings:document+,script+ v03_AmadeusWS_AirRulesRQ.xsl
xsltc /settings:document+,script+ v03_AmadeusWS_AirRulesRS.xsl
xsltc /settings:document+,script+ v03_AmadeusWS_DisplayTicketRQ.xsl
xsltc /settings:document+,script+ v03_AmadeusWS_PNRReadRQ.xsl
xsltc /settings:document+,script+ v03_AmadeusWS_PNRReadRS.xsl
xsltc /settings:document+,script+ v03_AmadeusWS_TB_Errors.xsl
xsltc /settings:document+,script+ v03_AmadeusWS_TravelBuildRQ.xsl
xsltc /settings:document+,script+ v03_AmadeusWS_StoredFareBuildRQ.xsl
xsltc /settings:document+,script+ v03_AmadeusWS_StoredFareBuildRS.xsl
xsltc /settings:document+,script+ v04_AmadeusWS_PNRReadRQ.xsl
xsltc /settings:document+,script+ v04_AmadeusWS_PNRReadRS.xsl
xsltc /settings:document+,script+ v04_AmadeusWS_TB_Errors.xsl
xsltc /settings:document+,script+ v04_AmadeusWS_TravelBuildRQ.xsl
xsltc /settings:document+,script+ v04_AmadeusWS_QueueReadRQ.xsl
xsltc /settings:document+,script+ v05_AmadeusWS_PNRReadRQ.xsl
xsltc /settings:document+,script+ v05_AmadeusWS_PNRReadRS.xsl
xsltc /settings:document+,script+ AmadeusWS_ListVirtualCardsRQ.xsl
xsltc /settings:document+,script+ AmadeusWS_ListVirtualCardsRS.xsl
xsltc /settings:document+,script+ AmadeusWS_GenerateVirtualCardRQ.xsl
xsltc /settings:document+,script+ AmadeusWS_GenerateVirtualCardRS.xsl
xsltc /settings:document+,script+ AmadeusWS_GetVirtualCardDetailsRQ.xsl
xsltc /settings:document+,script+ AmadeusWS_GetVirtualCardDetailsRS.xsl
xsltc /settings:document+,script+ AmadeusWS_DeleteVirtualCardRQ.xsl
xsltc /settings:document+,script+ AmadeusWS_DeleteVirtualCardRS.xsl
xsltc /settings:document+,script+ AmadeusWS_ReIssueTicketRQ.xsl
xsltc /settings:document+,script+ v03_AmadeusWS_SalesReportRQ.xsl
xsltc /settings:document+,script+ v03_AmadeusWS_SalesReportRS.xsl

xsltc /settings:document+,script+ v03_AmadeusWS_LowFarePlus2RQ.xsl
xsltc /settings:document+,script+ v03_AmadeusWS_LowFarePlus2RS.xsl

xcopy "*.dll"  "..\..\wsTripXML\bin"  /c /d /i /y
xcopy "*.dll"  "..\..\TripXMLMain\Xsl\AmadeusWS"  /c /d /i /y
xcopy "*.dll"  "C:\TripXML\Xsl\AmadeusWS"  /c /d /i /y

del "*.dll" 
rem pause
