'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization

'
'This source code was auto-generated by xsd, Version=4.6.1055.0.
'
Namespace wsTravelTalk


    '''<remarks/,
    ''''[Namespace]:="http://www.iata.org/IATA/EDIST",
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),
     System.SerializableAttribute(),
     System.Xml.Serialization.XmlRootAttribute(IsNullable:=False)>
    Partial Public Class AggregateRS

        '''<remarks/> 
        '''
        <System.Xml.Serialization.XmlArrayItemAttribute("AirShoppingRS", GetType(AirShoppingRS))>
        Public AirShoppingResponses() As AirShoppingRS
    End Class


    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"),
 System.SerializableAttribute()>
    Partial Public Class AirShoppingRS

        Private itemsField() As Object

        Private echoTokenField As String

        Private timeStampField As Date

        Private timeStampFieldSpecified As Boolean

        Private targetField As AirShoppingRSTarget

        Private versionField As String

        Private transactionIdentifierField As String

        Private sequenceNmbrField As String

        Private transactionStatusCodeField As AirShoppingRSTransactionStatusCode

        Private transactionStatusCodeFieldSpecified As Boolean

        Private retransmissionIndicatorField As Boolean

        Private retransmissionIndicatorFieldSpecified As Boolean

        Private correlationIDField As String

        Private asynchronousAllowedIndField As Boolean

        Private asynchronousAllowedIndFieldSpecified As Boolean

        Public Sub New()
            MyBase.New
            Me.targetField = AirShoppingRSTarget.Production
        End Sub

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("AirShoppingProcessing", GetType(OrdViewProcessType)),
     System.Xml.Serialization.XmlElementAttribute("Commission", GetType(CommissionType)),
     System.Xml.Serialization.XmlElementAttribute("DataLists", GetType(AirShoppingRSDataLists)),
     System.Xml.Serialization.XmlElementAttribute("Document", GetType(MsgDocumentType)),
     System.Xml.Serialization.XmlElementAttribute("Errors", GetType(ErrorsType)),
     System.Xml.Serialization.XmlElementAttribute("Metadata", GetType(AirShopResMetadataType)),
     System.Xml.Serialization.XmlElementAttribute("OffersGroup", GetType(AirShoppingRSOffersGroup)),
     System.Xml.Serialization.XmlElementAttribute("Payments", GetType(AirShoppingRSPayments)),
     System.Xml.Serialization.XmlElementAttribute("Policies", GetType(Policies)),
     System.Xml.Serialization.XmlElementAttribute("Promotions", GetType(AirShoppingRSPromotions)),
     System.Xml.Serialization.XmlElementAttribute("ShoppingResponseID", GetType(ShoppingResponseID_Type)),
     System.Xml.Serialization.XmlElementAttribute("Success", GetType(SuccessType)),
     System.Xml.Serialization.XmlElementAttribute("Warnings", GetType(WarningsType))>
        Public Property Items() As Object()
            Get
                Return Me.itemsField
            End Get
            Set
                Me.itemsField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public Property EchoToken() As String
            Get
                Return Me.echoTokenField
            End Get
            Set
                Me.echoTokenField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public Property TimeStamp() As Date
            Get
                Return Me.timeStampField
            End Get
            Set
                Me.timeStampField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>
        Public Property TimeStampSpecified() As Boolean
            Get
                Return Me.timeStampFieldSpecified
            End Get
            Set
                Me.timeStampFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(),
     System.ComponentModel.DefaultValueAttribute(AirShoppingRSTarget.Production)>
        Public Property Target() As AirShoppingRSTarget
            Get
                Return Me.targetField
            End Get
            Set
                Me.targetField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public Property Version() As String
            Get
                Return Me.versionField
            End Get
            Set
                Me.versionField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public Property TransactionIdentifier() As String
            Get
                Return Me.transactionIdentifierField
            End Get
            Set
                Me.transactionIdentifierField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="nonNegativeInteger")>
        Public Property SequenceNmbr() As String
            Get
                Return Me.sequenceNmbrField
            End Get
            Set
                Me.sequenceNmbrField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public Property TransactionStatusCode() As AirShoppingRSTransactionStatusCode
            Get
                Return Me.transactionStatusCodeField
            End Get
            Set
                Me.transactionStatusCodeField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>
        Public Property TransactionStatusCodeSpecified() As Boolean
            Get
                Return Me.transactionStatusCodeFieldSpecified
            End Get
            Set
                Me.transactionStatusCodeFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public Property RetransmissionIndicator() As Boolean
            Get
                Return Me.retransmissionIndicatorField
            End Get
            Set
                Me.retransmissionIndicatorField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>
        Public Property RetransmissionIndicatorSpecified() As Boolean
            Get
                Return Me.retransmissionIndicatorFieldSpecified
            End Get
            Set
                Me.retransmissionIndicatorFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public Property CorrelationID() As String
            Get
                Return Me.correlationIDField
            End Get
            Set
                Me.correlationIDField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public Property AsynchronousAllowedInd() As Boolean
            Get
                Return Me.asynchronousAllowedIndField
            End Get
            Set
                Me.asynchronousAllowedIndField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>
        Public Property AsynchronousAllowedIndSpecified() As Boolean
            Get
                Return Me.asynchronousAllowedIndFieldSpecified
            End Get
            Set
                Me.asynchronousAllowedIndFieldSpecified = Value
            End Set
        End Property
    End Class


    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"),
 System.SerializableAttribute()>
    Partial Public Class WarningsType

        Private warningField() As WarningType

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Warning")>
        Public Property Warning() As WarningType()
            Get
                Return Me.warningField
            End Get
            Set
                Me.warningField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"),
 System.SerializableAttribute()>
    Partial Public Class AirShoppingRSDataLists

        Private passengerListField() As PassengerType

        Private contactListField() As ContactInformationType

        Private bagDisclosureListField() As ListOfBagDisclosureTypeBagDisclosure

        Private baggageAllowanceListField() As AirShoppingRSDataListsBaggageAllowance

        Private classOfServiceListField() As ListOfClassOfServiceTypeServiceClass

        Private contentSourceListField() As ListOfContentSourceTypeContentSource

        Private descriptionListField() As Description

        Private disclosureListField() As ListOfDisclosureTypeDisclosures

        Private fareListField() As FareListFareGroup

        Private flightSegmentListField() As ListOfFlightSegmentType

        Private flightListField() As AirShoppingRSDataListsFlight

        Private originDestinationListField() As OriginDestination

        Private instructionsListField() As ListOfOfferInstructionsTypeInstruction

        Private mediaListField() As ListOfMediaTypeMedia

        Private penaltyListField() As ListOfOfferPenaltyTypePenalty

        Private priceClassListField() As PriceClassType

        Private serviceDefinitionListField() As ServiceDefinitionType

        Private termsListField As ListOfOfferTermsType

        Private seatDefinitionListField() As AirShoppingRSDataListsSeatDefinition

        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("Passenger", IsNullable:=False)>
        Public Property PassengerList() As PassengerType()
            Get
                Return Me.passengerListField
            End Get
            Set
                Me.passengerListField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("ContactInformation", IsNullable:=False)>
        Public Property ContactList() As ContactInformationType()
            Get
                Return Me.contactListField
            End Get
            Set
                Me.contactListField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("BagDisclosure", IsNullable:=False)>
        Public Property BagDisclosureList() As ListOfBagDisclosureTypeBagDisclosure()
            Get
                Return Me.bagDisclosureListField
            End Get
            Set
                Me.bagDisclosureListField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("BaggageAllowance", IsNullable:=False)>
        Public Property BaggageAllowanceList() As AirShoppingRSDataListsBaggageAllowance()
            Get
                Return Me.baggageAllowanceListField
            End Get
            Set
                Me.baggageAllowanceListField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("ServiceClass", IsNullable:=False)>
        Public Property ClassOfServiceList() As ListOfClassOfServiceTypeServiceClass()
            Get
                Return Me.classOfServiceListField
            End Get
            Set
                Me.classOfServiceListField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("ContentSource", IsNullable:=False)>
        Public Property ContentSourceList() As ListOfContentSourceTypeContentSource()
            Get
                Return Me.contentSourceListField
            End Get
            Set
                Me.contentSourceListField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("Description", IsNullable:=False)>
        Public Property DescriptionList() As Description()
            Get
                Return Me.descriptionListField
            End Get
            Set
                Me.descriptionListField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("Disclosures", IsNullable:=False)>
        Public Property DisclosureList() As ListOfDisclosureTypeDisclosures()
            Get
                Return Me.disclosureListField
            End Get
            Set
                Me.disclosureListField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("FareGroup", IsNullable:=False)>
        Public Property FareList() As FareListFareGroup()
            Get
                Return Me.fareListField
            End Get
            Set
                Me.fareListField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("FlightSegment", IsNullable:=False)>
        Public Property FlightSegmentList() As ListOfFlightSegmentType()
            Get
                Return Me.flightSegmentListField
            End Get
            Set
                Me.flightSegmentListField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("Flight", IsNullable:=False)>
        Public Property FlightList() As AirShoppingRSDataListsFlight()
            Get
                Return Me.flightListField
            End Get
            Set
                Me.flightListField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("OriginDestination", IsNullable:=False)>
        Public Property OriginDestinationList() As OriginDestination()
            Get
                Return Me.originDestinationListField
            End Get
            Set
                Me.originDestinationListField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("Instruction", IsNullable:=False)>
        Public Property InstructionsList() As ListOfOfferInstructionsTypeInstruction()
            Get
                Return Me.instructionsListField
            End Get
            Set
                Me.instructionsListField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("Media", IsNullable:=False)>
        Public Property MediaList() As ListOfMediaTypeMedia()
            Get
                Return Me.mediaListField
            End Get
            Set
                Me.mediaListField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("Penalty", IsNullable:=False)>
        Public Property PenaltyList() As ListOfOfferPenaltyTypePenalty()
            Get
                Return Me.penaltyListField
            End Get
            Set
                Me.penaltyListField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("PriceClass", IsNullable:=False)>
        Public Property PriceClassList() As PriceClassType()
            Get
                Return Me.priceClassListField
            End Get
            Set
                Me.priceClassListField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("ServiceDefinition", IsNullable:=False)>
        Public Property ServiceDefinitionList() As ServiceDefinitionType()
            Get
                Return Me.serviceDefinitionListField
            End Get
            Set
                Me.serviceDefinitionListField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property TermsList() As ListOfOfferTermsType
            Get
                Return Me.termsListField
            End Get
            Set
                Me.termsListField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("SeatDefinition", IsNullable:=False)>
        Public Property SeatDefinitionList() As AirShoppingRSDataListsSeatDefinition()
            Get
                Return Me.seatDefinitionListField
            End Get
            Set
                Me.seatDefinitionListField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"),
 System.SerializableAttribute()>
    Partial Public Class AirShoppingRSDataListsBaggageAllowance

        Private baggageCategoryField As BaggageCategoryListType

        Private allowanceDescriptionField As BagAllowanceDescType

        Private dimensionAllowanceField As BagAllowanceDimensionType

        Private pieceAllowanceField() As PieceAllowance

        Private weightAllowanceField As WeightAllowance

        Private baggageDeterminingCarrierField As BaggageDeterminingCarrierType

        Private baggageAllowanceIDField As String

        '''<remarks/>
        Public Property BaggageCategory() As BaggageCategoryListType
            Get
                Return Me.baggageCategoryField
            End Get
            Set
                Me.baggageCategoryField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property AllowanceDescription() As BagAllowanceDescType
            Get
                Return Me.allowanceDescriptionField
            End Get
            Set
                Me.allowanceDescriptionField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property DimensionAllowance() As BagAllowanceDimensionType
            Get
                Return Me.dimensionAllowanceField
            End Get
            Set
                Me.dimensionAllowanceField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("PieceAllowance")>
        Public Property PieceAllowance() As PieceAllowance()
            Get
                Return Me.pieceAllowanceField
            End Get
            Set
                Me.pieceAllowanceField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property WeightAllowance() As WeightAllowance
            Get
                Return Me.weightAllowanceField
            End Get
            Set
                Me.weightAllowanceField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property BaggageDeterminingCarrier() As BaggageDeterminingCarrierType
            Get
                Return Me.baggageDeterminingCarrierField
            End Get
            Set
                Me.baggageDeterminingCarrierField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="ID")>
        Public Property BaggageAllowanceID() As String
            Get
                Return Me.baggageAllowanceIDField
            End Get
            Set
                Me.baggageAllowanceIDField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"),
 System.SerializableAttribute()>
    Partial Public Class AirShoppingRSDataListsFlight

        Private journeyField As TotalJourneyType

        Private segmentReferencesField As SegmentReferences

        Private settlementField As AirShoppingRSDataListsFlightSettlement

        Private refsField As String

        Private flightKeyField As String

        '''<remarks/>
        Public Property Journey() As TotalJourneyType
            Get
                Return Me.journeyField
            End Get
            Set
                Me.journeyField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property SegmentReferences() As SegmentReferences
            Get
                Return Me.segmentReferencesField
            End Get
            Set
                Me.segmentReferencesField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Settlement() As AirShoppingRSDataListsFlightSettlement
            Get
                Return Me.settlementField
            End Get
            Set
                Me.settlementField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="IDREFS")>
        Public Property refs() As String
            Get
                Return Me.refsField
            End Get
            Set
                Me.refsField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="ID")>
        Public Property FlightKey() As String
            Get
                Return Me.flightKeyField
            End Get
            Set
                Me.flightKeyField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"),
 System.SerializableAttribute()>
    Partial Public Class AirShoppingRSDataListsFlightSettlement

        Private methodField As String

        Private interlineSettlementValueField As CurrencyAmountOptType

        '''<remarks/>
        Public Property Method() As String
            Get
                Return Me.methodField
            End Get
            Set
                Me.methodField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property InterlineSettlementValue() As CurrencyAmountOptType
            Get
                Return Me.interlineSettlementValueField
            End Get
            Set
                Me.interlineSettlementValueField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"),
 System.SerializableAttribute()>
    Partial Public Class AirShoppingRSDataListsSeatDefinition

        Private descriptionField() As AirShoppingRSDataListsSeatDefinitionDescription

        Private marketingField As AirShoppingRSDataListsSeatDefinitionMarketing

        Private seatCharacteristicCodeField() As String

        Private uOMField As SizeUnitSimpleType

        Private uOMFieldSpecified As Boolean

        Private seatWidthLowField As Decimal

        Private seatWidthLowFieldSpecified As Boolean

        Private seatPitchLowField As Decimal

        Private seatPitchLowFieldSpecified As Boolean

        Private keywordsField() As KeyWordType

        Private seatDefinitionIDField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Description")>
        Public Property Description() As AirShoppingRSDataListsSeatDefinitionDescription()
            Get
                Return Me.descriptionField
            End Get
            Set
                Me.descriptionField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Marketing() As AirShoppingRSDataListsSeatDefinitionMarketing
            Get
                Return Me.marketingField
            End Get
            Set
                Me.marketingField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("SeatCharacteristicCode")>
        Public Property SeatCharacteristicCode() As String()
            Get
                Return Me.seatCharacteristicCodeField
            End Get
            Set
                Me.seatCharacteristicCodeField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property UOM() As SizeUnitSimpleType
            Get
                Return Me.uOMField
            End Get
            Set
                Me.uOMField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>
        Public Property UOMSpecified() As Boolean
            Get
                Return Me.uOMFieldSpecified
            End Get
            Set
                Me.uOMFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property SeatWidthLow() As Decimal
            Get
                Return Me.seatWidthLowField
            End Get
            Set
                Me.seatWidthLowField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>
        Public Property SeatWidthLowSpecified() As Boolean
            Get
                Return Me.seatWidthLowFieldSpecified
            End Get
            Set
                Me.seatWidthLowFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property SeatPitchLow() As Decimal
            Get
                Return Me.seatPitchLowField
            End Get
            Set
                Me.seatPitchLowField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>
        Public Property SeatPitchLowSpecified() As Boolean
            Get
                Return Me.seatPitchLowFieldSpecified
            End Get
            Set
                Me.seatPitchLowFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("KeyWord", IsNullable:=False)>
        Public Property Keywords() As KeyWordType()
            Get
                Return Me.keywordsField
            End Get
            Set
                Me.keywordsField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="ID")>
        Public Property SeatDefinitionID() As String
            Get
                Return Me.seatDefinitionIDField
            End Get
            Set
                Me.seatDefinitionIDField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"),
 System.SerializableAttribute()>
    Partial Public Class AirShoppingRSDataListsSeatDefinitionDescription

        Private textField As AirShoppingRSDataListsSeatDefinitionDescriptionText

        Private markupStyleField As String

        Private linkField As String

        Private mediaField() As AirShoppingRSDataListsSeatDefinitionDescriptionMedia

        '''<remarks/>
        Public Property Text() As AirShoppingRSDataListsSeatDefinitionDescriptionText
            Get
                Return Me.textField
            End Get
            Set
                Me.textField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property MarkupStyle() As String
            Get
                Return Me.markupStyleField
            End Get
            Set
                Me.markupStyleField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Link() As String
            Get
                Return Me.linkField
            End Get
            Set
                Me.linkField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Media")>
        Public Property Media() As AirShoppingRSDataListsSeatDefinitionDescriptionMedia()
            Get
                Return Me.mediaField
            End Get
            Set
                Me.mediaField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"),
 System.SerializableAttribute()>
    Partial Public Class AirShoppingRSDataListsSeatDefinitionDescriptionText

        Private refsField As String

        Private valueField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="IDREFS")>
        Public Property refs() As String
            Get
                Return Me.refsField
            End Get
            Set
                Me.refsField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()>
        Public Property Value() As String
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"),
 System.SerializableAttribute()>
    Partial Public Class AirShoppingRSDataListsSeatDefinitionDescriptionMedia

        Private itemField As Object

        Private itemElementNameField As ItemChoiceType10_extended

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("AttachmentID", GetType(MediaID_Type)),
     System.Xml.Serialization.XmlElementAttribute("MediaLink", GetType(MediaLink)),
     System.Xml.Serialization.XmlElementAttribute("ObjectID", GetType(MediaID_Type)),
     System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")>
        Public Property Item() As Object
            Get
                Return Me.itemField
            End Get
            Set
                Me.itemField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>
        Public Property ItemElementName() As ItemChoiceType10_extended
            Get
                Return Me.itemElementNameField
            End Get
            Set
                Me.itemElementNameField = Value
            End Set
        End Property
    End Class




    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"),
 System.SerializableAttribute()>
    Partial Public Class AirShoppingRSDataListsSeatDefinitionMarketing
        Inherits SeatMapMessageType
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"),
 System.SerializableAttribute()>
    Partial Public Class AirShoppingRSOffersGroup

        Private allOffersSnapshotField As AirlineOffersSnapshotType

        Private airlineOffersField() As AirShoppingRSOffersGroupAirlineOffers

        '''<remarks/>
        Public Property AllOffersSnapshot() As AirlineOffersSnapshotType
            Get
                Return Me.allOffersSnapshotField
            End Get
            Set
                Me.allOffersSnapshotField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("AirlineOffers")>
        Public Property AirlineOffers() As AirShoppingRSOffersGroupAirlineOffers()
            Get
                Return Me.airlineOffersField
            End Get
            Set
                Me.airlineOffersField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"),
 System.SerializableAttribute()>
    Partial Public Class AirShoppingRSOffersGroupAirlineOffers

        Private airlineOfferSnapshotField As AirlineOffersSnapshotType

        Private offerField() As AirShoppingRSOffersGroupAirlineOffersOffer

        Private aLaCarteOfferField As AirShoppingRSOffersGroupAirlineOffersALaCarteOffer

        Private priceCalendarField() As AirShoppingRSOffersGroupAirlineOffersPriceCalendar

        '''<remarks/>
        Public Property AirlineOfferSnapshot() As AirlineOffersSnapshotType
            Get
                Return Me.airlineOfferSnapshotField
            End Get
            Set
                Me.airlineOfferSnapshotField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Offer")>
        Public Property Offer() As AirShoppingRSOffersGroupAirlineOffersOffer()
            Get
                Return Me.offerField
            End Get
            Set
                Me.offerField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property ALaCarteOffer() As AirShoppingRSOffersGroupAirlineOffersALaCarteOffer
            Get
                Return Me.aLaCarteOfferField
            End Get
            Set
                Me.aLaCarteOfferField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("PriceCalendar")>
        Public Property PriceCalendar() As AirShoppingRSOffersGroupAirlineOffersPriceCalendar()
            Get
                Return Me.priceCalendarField
            End Get
            Set
                Me.priceCalendarField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"),
 System.SerializableAttribute()>
    Partial Public Class AirShoppingRSOffersGroupAirlineOffersOffer
        Inherits OfferType

        Private flightsOverviewField As AirShoppingRSOffersGroupAirlineOffersOfferFlightsOverview

        Private offerItemField() As OfferItemType

        Private baggageAllowanceField() As AirShoppingRSOffersGroupAirlineOffersOfferBaggageAllowance

        '''<remarks/>
        Public Property FlightsOverview() As AirShoppingRSOffersGroupAirlineOffersOfferFlightsOverview
            Get
                Return Me.flightsOverviewField
            End Get
            Set
                Me.flightsOverviewField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("OfferItem")>
        Public Property OfferItem() As OfferItemType()
            Get
                Return Me.offerItemField
            End Get
            Set
                Me.offerItemField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("BaggageAllowance")>
        Public Property BaggageAllowance() As AirShoppingRSOffersGroupAirlineOffersOfferBaggageAllowance()
            Get
                Return Me.baggageAllowanceField
            End Get
            Set
                Me.baggageAllowanceField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"),
 System.SerializableAttribute()>
    Partial Public Class AirShoppingRSOffersGroupAirlineOffersOfferFlightsOverview

        Private flightRefField() As AirShoppingRSOffersGroupAirlineOffersOfferFlightsOverviewFlightRef

        Private itineraryPriceClassRefField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("FlightRef")>
        Public Property FlightRef() As AirShoppingRSOffersGroupAirlineOffersOfferFlightsOverviewFlightRef()
            Get
                Return Me.flightRefField
            End Get
            Set
                Me.flightRefField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="IDREF")>
        Public Property ItineraryPriceClassRef() As String
            Get
                Return Me.itineraryPriceClassRefField
            End Get
            Set
                Me.itineraryPriceClassRefField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"),
 System.SerializableAttribute()>
    Partial Public Class AirShoppingRSOffersGroupAirlineOffersOfferFlightsOverviewFlightRef

        Private oDRefField As String

        Private priceClassRefField As String

        Private valueField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="IDREF")>
        Public Property ODRef() As String
            Get
                Return Me.oDRefField
            End Get
            Set
                Me.oDRefField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="IDREF")>
        Public Property PriceClassRef() As String
            Get
                Return Me.priceClassRefField
            End Get
            Set
                Me.priceClassRefField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute(DataType:="IDREF")>
        Public Property Value() As String
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"),
 System.SerializableAttribute()>
    Partial Public Class AirShoppingRSOffersGroupAirlineOffersOfferBaggageAllowance

        Private flightRefsField As String

        Private passengerRefsField As String

        Private baggageAllowanceRefField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="IDREFS")>
        Public Property FlightRefs() As String
            Get
                Return Me.flightRefsField
            End Get
            Set
                Me.flightRefsField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="IDREFS")>
        Public Property PassengerRefs() As String
            Get
                Return Me.passengerRefsField
            End Get
            Set
                Me.passengerRefsField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="IDREF")>
        Public Property BaggageAllowanceRef() As String
            Get
                Return Me.baggageAllowanceRefField
            End Get
            Set
                Me.baggageAllowanceRefField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"),
 System.SerializableAttribute()>
    Partial Public Class AirShoppingRSOffersGroupAirlineOffersALaCarteOffer
        Inherits OfferType

        Private aLaCarteOfferItemField() As ALaCarteOfferItemType

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("ALaCarteOfferItem")>
        Public Property ALaCarteOfferItem() As ALaCarteOfferItemType()
            Get
                Return Me.aLaCarteOfferItemField
            End Get
            Set
                Me.aLaCarteOfferItemField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"),
 System.SerializableAttribute()>
    Partial Public Class AirShoppingRSOffersGroupAirlineOffersPriceCalendar

        Private priceCalendarDateField() As AirShoppingRSOffersGroupAirlineOffersPriceCalendarPriceCalendarDate

        Private totalPriceField As EncodedPriceType

        Private pTCField() As AirShoppingRSOffersGroupAirlineOffersPriceCalendarPTC

        Private leadPriceIndField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("PriceCalendarDate")>
        Public Property PriceCalendarDate() As AirShoppingRSOffersGroupAirlineOffersPriceCalendarPriceCalendarDate()
            Get
                Return Me.priceCalendarDateField
            End Get
            Set
                Me.priceCalendarDateField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property TotalPrice() As EncodedPriceType
            Get
                Return Me.totalPriceField
            End Get
            Set
                Me.totalPriceField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("PTC")>
        Public Property PTC() As AirShoppingRSOffersGroupAirlineOffersPriceCalendarPTC()
            Get
                Return Me.pTCField
            End Get
            Set
                Me.pTCField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public Property LeadPriceInd() As String
            Get
                Return Me.leadPriceIndField
            End Get
            Set
                Me.leadPriceIndField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"),
 System.SerializableAttribute()>
    Partial Public Class AirShoppingRSOffersGroupAirlineOffersPriceCalendarPriceCalendarDate

        Private originDestinationReferenceField As String

        Private valueField As Date

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="IDREF")>
        Public Property OriginDestinationReference() As String
            Get
                Return Me.originDestinationReferenceField
            End Get
            Set
                Me.originDestinationReferenceField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute(DataType:="date")>
        Public Property Value() As Date
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"),
 System.SerializableAttribute()>
    Partial Public Class AirShoppingRSOffersGroupAirlineOffersPriceCalendarPTC

        Private quantityField As String

        Private valueField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="integer")>
        Public Property Quantity() As String
            Get
                Return Me.quantityField
            End Get
            Set
                Me.quantityField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()>
        Public Property Value() As String
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"),
 System.SerializableAttribute()>
    Partial Public Class AirShoppingRSPayments

        Private paymentField() As AirShoppingRSPaymentsPayment

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Payment")>
        Public Property Payment() As AirShoppingRSPaymentsPayment()
            Get
                Return Me.paymentField
            End Get
            Set
                Me.paymentField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"),
 System.SerializableAttribute()>
    Partial Public Class AirShoppingRSPaymentsPayment
        Inherits OrderPaymentFormType

        Private offersField() As AirShoppingRSPaymentsPaymentOffer

        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("Offer", IsNullable:=False)>
        Public Property Offers() As AirShoppingRSPaymentsPaymentOffer()
            Get
                Return Me.offersField
            End Get
            Set
                Me.offersField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"),
 System.SerializableAttribute()>
    Partial Public Class AirShoppingRSPaymentsPaymentOffer

        Private offerItemIDField() As String

        Private offerIDField As String

        Private ownerField As String

        Private responseIDField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("OfferItemID")>
        Public Property OfferItemID() As String()
            Get
                Return Me.offerItemIDField
            End Get
            Set
                Me.offerItemIDField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public Property OfferID() As String
            Get
                Return Me.offerIDField
            End Get
            Set
                Me.offerIDField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public Property Owner() As String
            Get
                Return Me.ownerField
            End Get
            Set
                Me.ownerField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public Property ResponseID() As String
            Get
                Return Me.responseIDField
            End Get
            Set
                Me.responseIDField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"),
 System.SerializableAttribute()>
    Partial Public Class AirShoppingRSPromotions

        Private promotionField() As PromotionType

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Promotion")>
        Public Property Promotion() As PromotionType()
            Get
                Return Me.promotionField
            End Get
            Set
                Me.promotionField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"),
 System.SerializableAttribute()>
    Public Enum AirShoppingRSTarget

        '''<remarks/>
        Test

        '''<remarks/>
        Production
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"),
 System.SerializableAttribute()>
    Public Enum AirShoppingRSTransactionStatusCode

        '''<remarks/>
        Start

        '''<remarks/>
        [End]

        '''<remarks/>
        Rollback

        '''<remarks/>
        InSeries

        '''<remarks/>
        Continuation

        '''<remarks/>
        Subsequent
    End Enum



    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"),
 System.SerializableAttribute()>
    Partial Public Class AirShopResMetadataType

        Private shoppingField As AirShopResMetadataTypeShopping

        Private passengerField As AirShopResMetadataTypePassenger

        Private otherField() As AirShopResMetadataTypeOtherMetadata

        '''<remarks/>
        Public Property Shopping() As AirShopResMetadataTypeShopping
            Get
                Return Me.shoppingField
            End Get
            Set
                Me.shoppingField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Passenger() As AirShopResMetadataTypePassenger
            Get
                Return Me.passengerField
            End Get
            Set
                Me.passengerField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("OtherMetadata", IsNullable:=False)>
        Public Property Other() As AirShopResMetadataTypeOtherMetadata()
            Get
                Return Me.otherField
            End Get
            Set
                Me.otherField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"),
 System.SerializableAttribute()>
    Partial Public Class AirShopResMetadataTypeShopping

        Private shopMetadataGroupField As ShopMetadataGroup

        '''<remarks/>
        Public Property ShopMetadataGroup() As ShopMetadataGroup
            Get
                Return Me.shopMetadataGroupField
            End Get
            Set
                Me.shopMetadataGroupField = Value
            End Set
        End Property
    End Class


    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"),
 System.SerializableAttribute()>
    Partial Public Class AirShopResMetadataTypePassenger

        Private passengerMetadataField As PassengerMetadataType

        '''<remarks/>
        Public Property PassengerMetadata() As PassengerMetadataType
            Get
                Return Me.passengerMetadataField
            End Get
            Set
                Me.passengerMetadataField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"),
 System.SerializableAttribute()>
    Partial Public Class AirShopResMetadataTypeOtherMetadata

        Private itemField As Object

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("AddressMetadatas", GetType(AddressMetadatas)),
     System.Xml.Serialization.XmlElementAttribute("AircraftMetadatas", GetType(AircraftMetadatas)),
     System.Xml.Serialization.XmlElementAttribute("AirportMetadatas", GetType(AirportMetadatas)),
     System.Xml.Serialization.XmlElementAttribute("CityMetadatas", GetType(CityMetadatas)),
     System.Xml.Serialization.XmlElementAttribute("CodesetMetadatas", GetType(CodesetMetadatas)),
     System.Xml.Serialization.XmlElementAttribute("ContactMetadatas", GetType(ContactMetadatas)),
     System.Xml.Serialization.XmlElementAttribute("CountryMetadatas", GetType(CountryMetadatas)),
     System.Xml.Serialization.XmlElementAttribute("CurrencyMetadatas", GetType(CurrencyMetadatas)),
     System.Xml.Serialization.XmlElementAttribute("DescriptionMetadatas", GetType(DescriptionMetadatas)),
     System.Xml.Serialization.XmlElementAttribute("EquivalentID_Metadatas", GetType(EquivalentID_Metadatas)),
     System.Xml.Serialization.XmlElementAttribute("LanguageMetadatas", GetType(LanguageMetadatas)),
     System.Xml.Serialization.XmlElementAttribute("PaymentCardMetadatas", GetType(PaymentCardMetadatas)),
     System.Xml.Serialization.XmlElementAttribute("PaymentFormMetadatas", GetType(PaymentFormMetadatas)),
     System.Xml.Serialization.XmlElementAttribute("PriceMetadatas", GetType(PriceMetadatas)),
     System.Xml.Serialization.XmlElementAttribute("RuleMetadatas", GetType(RuleMetadatas)),
     System.Xml.Serialization.XmlElementAttribute("StateProvMetadatas", GetType(StateProvMetadatas)),
     System.Xml.Serialization.XmlElementAttribute("ZoneMetadatas", GetType(ZoneMetadatas))>
        Public Property Item() As Object
            Get
                Return Me.itemField
            End Get
            Set
                Me.itemField = Value
            End Set
        End Property
    End Class


    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"),
     System.SerializableAttribute()>
    Partial Public Class OrdViewProcessType
        Inherits OrderProcessResultType

        Private alertsField() As AlertsTypeAlert

        Private noticesField() As NoticesNotice

        Private remarksField As RemarkType

        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("Alert", IsNullable:=False)>
        Public Property Alerts() As AlertsTypeAlert()
            Get
                Return Me.alertsField
            End Get
            Set
                Me.alertsField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("Notice", IsNullable:=False)>
        Public Property Notices() As NoticesNotice()
            Get
                Return Me.noticesField
            End Get
            Set
                Me.noticesField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Remarks() As RemarkType
            Get
                Return Me.remarksField
            End Get
            Set
                Me.remarksField = Value
            End Set
        End Property
    End Class

End Namespace
