// ------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// Runtime Version:4.0.30319.42000
// 
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.81.0.
// 
namespace wsTripXML.wsTravelTalk
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCode("xsd", "4.0.30319.33440")]
    [Serializable()]
    [XmlRoot(IsNullable = false)]
    public partial class SeatAvailabilityRQ
    {

        private PointOfSaleType pointOfSaleField;

        private MsgDocumentType documentField;

        private MsgPartiesType partyField;

        private SeatAvailReqParamsType parametersField;

        private QualifiersTypeQualifier[] qualifiersField;

        private ShoppingResponseID_Type shoppingResponseIDField;

        private SeatAvailabilityRQQuery queryField;

        private ItineraryType journeyDataField;

        private SeatAvailabilityRQDataLists dataListsField;

        private SeatAvailReqMetadataType metadataField;

        private PoliciesPolicy[] policiesField;

        private string echoTokenField;

        private DateTime timeStampField;

        private bool timeStampFieldSpecified;

        private SeatAvailabilityRQTarget targetField;

        private string versionField;

        private string transactionIdentifierField;

        private string sequenceNmbrField;

        private SeatAvailabilityRQTransactionStatusCode transactionStatusCodeField;

        private bool transactionStatusCodeFieldSpecified;

        private bool retransmissionIndicatorField;

        private bool retransmissionIndicatorFieldSpecified;

        private string correlationIDField;

        private bool asynchronousAllowedIndField;

        private bool asynchronousAllowedIndFieldSpecified;

        public SeatAvailabilityRQ() : base()
        {
            targetField = SeatAvailabilityRQTarget.Production;
        }

        /// <remarks/>
        public PointOfSaleType PointOfSale
        {
            get
            {
                return pointOfSaleField;
            }
            set
            {
                pointOfSaleField = value;
            }
        }

        /// <remarks/>
        public MsgDocumentType Document
        {
            get
            {
                return documentField;
            }
            set
            {
                documentField = value;
            }
        }

        /// <remarks/>
        public MsgPartiesType Party
        {
            get
            {
                return partyField;
            }
            set
            {
                partyField = value;
            }
        }

        /// <remarks/>
        public SeatAvailReqParamsType Parameters
        {
            get
            {
                return parametersField;
            }
            set
            {
                parametersField = value;
            }
        }

        /// <remarks/>
        [XmlArrayItem("Qualifier", IsNullable = false)]
        public QualifiersTypeQualifier[] Qualifiers
        {
            get
            {
                return qualifiersField;
            }
            set
            {
                qualifiersField = value;
            }
        }

        /// <remarks/>
        public ShoppingResponseID_Type ShoppingResponseID
        {
            get
            {
                return shoppingResponseIDField;
            }
            set
            {
                shoppingResponseIDField = value;
            }
        }

        /// <remarks/>
        public SeatAvailabilityRQQuery Query
        {
            get
            {
                return queryField;
            }
            set
            {
                queryField = value;
            }
        }

        /// <remarks/>
        public ItineraryType JourneyData
        {
            get
            {
                return journeyDataField;
            }
            set
            {
                journeyDataField = value;
            }
        }

        /// <remarks/>
        public SeatAvailabilityRQDataLists DataLists
        {
            get
            {
                return dataListsField;
            }
            set
            {
                dataListsField = value;
            }
        }

        /// <remarks/>
        public SeatAvailReqMetadataType Metadata
        {
            get
            {
                return metadataField;
            }
            set
            {
                metadataField = value;
            }
        }

        /// <remarks/>
        [XmlArrayItem("Policy", IsNullable = false)]
        public PoliciesPolicy[] Policies
        {
            get
            {
                return policiesField;
            }
            set
            {
                policiesField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string EchoToken
        {
            get
            {
                return echoTokenField;
            }
            set
            {
                echoTokenField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public DateTime TimeStamp
        {
            get
            {
                return timeStampField;
            }
            set
            {
                timeStampField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool TimeStampSpecified
        {
            get
            {
                return timeStampFieldSpecified;
            }
            set
            {
                timeStampFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        [System.ComponentModel.DefaultValue(SeatAvailabilityRQTarget.Production)]
        public SeatAvailabilityRQTarget Target
        {
            get
            {
                return targetField;
            }
            set
            {
                targetField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string Version
        {
            get
            {
                return versionField;
            }
            set
            {
                versionField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string TransactionIdentifier
        {
            get
            {
                return transactionIdentifierField;
            }
            set
            {
                transactionIdentifierField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute(DataType = "nonNegativeInteger")]
        public string SequenceNmbr
        {
            get
            {
                return sequenceNmbrField;
            }
            set
            {
                sequenceNmbrField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public SeatAvailabilityRQTransactionStatusCode TransactionStatusCode
        {
            get
            {
                return transactionStatusCodeField;
            }
            set
            {
                transactionStatusCodeField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool TransactionStatusCodeSpecified
        {
            get
            {
                return transactionStatusCodeFieldSpecified;
            }
            set
            {
                transactionStatusCodeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public bool RetransmissionIndicator
        {
            get
            {
                return retransmissionIndicatorField;
            }
            set
            {
                retransmissionIndicatorField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool RetransmissionIndicatorSpecified
        {
            get
            {
                return retransmissionIndicatorFieldSpecified;
            }
            set
            {
                retransmissionIndicatorFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string CorrelationID
        {
            get
            {
                return correlationIDField;
            }
            set
            {
                correlationIDField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public bool AsynchronousAllowedInd
        {
            get
            {
                return asynchronousAllowedIndField;
            }
            set
            {
                asynchronousAllowedIndField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool AsynchronousAllowedIndSpecified
        {
            get
            {
                return asynchronousAllowedIndFieldSpecified;
            }
            set
            {
                asynchronousAllowedIndFieldSpecified = value;
            }
        }
    }



    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCode("xsd", "4.0.30319.33440")]
    [Serializable()]
    public partial class SeatAvailabilityRQQuery
    {

        private object[] itemsField;

        /// <remarks/>
        [XmlElement("BookingReference", typeof(BookingReference))]
        [XmlElement("FlightSegment", typeof(SeatAvailabilityRQQueryFlightSegment))]
        [XmlElement("Offer", typeof(SeatAvailabilityRQQueryOffer))]
        [XmlElement("Order", typeof(SeatAvailabilityRQQueryOrder))]
        public object[] Items
        {
            get
            {
                return itemsField;
            }
            set
            {
                itemsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCode("xsd", "4.0.30319.33440")]
    [Serializable()]
    public partial class SeatAvailabilityRQQueryFlightSegment
    {

        private string airlineIDField;

        private Departure departureField;

        private FlightArrivalType arrivalField;

        private FlightNumber flightNumberField;

        private SeatAvailabilityRQQueryFlightSegmentClassOfService classOfServiceField;

        /// <remarks/>
        [XmlElement(DataType = "ID")]
        public string AirlineID
        {
            get
            {
                return airlineIDField;
            }
            set
            {
                airlineIDField = value;
            }
        }

        /// <remarks/>
        public Departure Departure
        {
            get
            {
                return departureField;
            }
            set
            {
                departureField = value;
            }
        }

        /// <remarks/>
        public FlightArrivalType Arrival
        {
            get
            {
                return arrivalField;
            }
            set
            {
                arrivalField = value;
            }
        }

        /// <remarks/>
        public FlightNumber FlightNumber
        {
            get
            {
                return flightNumberField;
            }
            set
            {
                flightNumberField = value;
            }
        }

        /// <remarks/>
        public SeatAvailabilityRQQueryFlightSegmentClassOfService ClassOfService
        {
            get
            {
                return classOfServiceField;
            }
            set
            {
                classOfServiceField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCode("xsd", "4.0.30319.33440")]
    [Serializable()]
    public partial class SeatAvailabilityRQQueryFlightSegmentClassOfService
    {

        private SeatAvailabilityRQQueryFlightSegmentClassOfServiceCode codeField;

        private string fareBasisCodeField;

        /// <remarks/>
        public SeatAvailabilityRQQueryFlightSegmentClassOfServiceCode Code
        {
            get
            {
                return codeField;
            }
            set
            {
                codeField = value;
            }
        }

        /// <remarks/>
        public string FareBasisCode
        {
            get
            {
                return fareBasisCodeField;
            }
            set
            {
                fareBasisCodeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCode("xsd", "4.0.30319.33440")]
    [Serializable()]
    public partial class SeatAvailabilityRQQueryFlightSegmentClassOfServiceCode
    {

        private string valueField;

        /// <remarks/>
        [XmlText()]
        public string Value
        {
            get
            {
                return valueField;
            }
            set
            {
                valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCode("xsd", "4.0.30319.33440")]
    [Serializable()]
    public partial class SeatAvailabilityRQQueryOffer
    {

        private string[] segmentIDField;

        private string[] passengerIDField;

        private string offerIDField;

        private string ownerField;

        private string responseIDField;

        /// <remarks/>
        [XmlElement("SegmentID")]
        public string[] SegmentID
        {
            get
            {
                return segmentIDField;
            }
            set
            {
                segmentIDField = value;
            }
        }

        /// <remarks/>
        [XmlElement("PassengerID")]
        public string[] PassengerID
        {
            get
            {
                return passengerIDField;
            }
            set
            {
                passengerIDField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute(DataType = "ID")]
        public string OfferID
        {
            get
            {
                return offerIDField;
            }
            set
            {
                offerIDField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string Owner
        {
            get
            {
                return ownerField;
            }
            set
            {
                ownerField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string ResponseID
        {
            get
            {
                return responseIDField;
            }
            set
            {
                responseIDField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCode("xsd", "4.0.30319.33440")]
    [Serializable()]
    public partial class SeatAvailabilityRQQueryOrder
    {

        private string[] passengerIDField;

        private string[] segmentIDField;

        private string orderIDField;

        private string ownerField;

        /// <remarks/>
        [XmlElement("PassengerID")]
        public string[] PassengerID
        {
            get
            {
                return passengerIDField;
            }
            set
            {
                passengerIDField = value;
            }
        }

        /// <remarks/>
        [XmlElement("SegmentID")]
        public string[] SegmentID
        {
            get
            {
                return segmentIDField;
            }
            set
            {
                segmentIDField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string OrderID
        {
            get
            {
                return orderIDField;
            }
            set
            {
                orderIDField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string Owner
        {
            get
            {
                return ownerField;
            }
            set
            {
                ownerField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCode("xsd", "4.0.30319.33440")]
    [Serializable()]
    public partial class SeatAvailabilityRQDataLists
    {

        private PassengerType[] passengerListField;

        private ContactInformationType[] contactListField;

        private ListOfBagDisclosureTypeBagDisclosure[] bagDisclosureListField;

        private SeatAvailabilityRQDataListsBaggageAllowance[] baggageAllowanceListField;

        private ListOfClassOfServiceTypeServiceClass[] classOfServiceListField;

        private ListOfContentSourceTypeContentSource[] contentSourceListField;

        private Description[] descriptionListField;

        private ListOfDisclosureTypeDisclosures[] disclosureListField;

        private FareListFareGroup[] fareListField;

        private ListOfFlightSegmentType[] flightSegmentListField;

        private SeatAvailabilityRQDataListsFlight[] flightListField;

        private OriginDestination[] originDestinationListField;

        private ListOfOfferInstructionsTypeInstruction[] instructionsListField;

        private ListOfMediaTypeMedia[] mediaListField;

        private ListOfOfferPenaltyTypePenalty[] penaltyListField;

        private PriceClassType[] priceClassListField;

        private ServiceDefinitionType[] serviceDefinitionListField;

        private ListOfOfferTermsType termsListField;

        private SeatAvailabilityRQDataListsSeatDefinition[] seatDefinitionListField;

        /// <remarks/>
        [XmlArrayItem("Passenger", IsNullable = false)]
        public PassengerType[] PassengerList
        {
            get
            {
                return passengerListField;
            }
            set
            {
                passengerListField = value;
            }
        }

        /// <remarks/>
        [XmlArrayItem("ContactInformation", IsNullable = false)]
        public ContactInformationType[] ContactList
        {
            get
            {
                return contactListField;
            }
            set
            {
                contactListField = value;
            }
        }

        /// <remarks/>
        [XmlArrayItem("BagDisclosure", IsNullable = false)]
        public ListOfBagDisclosureTypeBagDisclosure[] BagDisclosureList
        {
            get
            {
                return bagDisclosureListField;
            }
            set
            {
                bagDisclosureListField = value;
            }
        }

        /// <remarks/>
        [XmlArrayItem("BaggageAllowance", IsNullable = false)]
        public SeatAvailabilityRQDataListsBaggageAllowance[] BaggageAllowanceList
        {
            get
            {
                return baggageAllowanceListField;
            }
            set
            {
                baggageAllowanceListField = value;
            }
        }

        /// <remarks/>
        [XmlArrayItem("ServiceClass", IsNullable = false)]
        public ListOfClassOfServiceTypeServiceClass[] ClassOfServiceList
        {
            get
            {
                return classOfServiceListField;
            }
            set
            {
                classOfServiceListField = value;
            }
        }

        /// <remarks/>
        [XmlArrayItem("ContentSource", IsNullable = false)]
        public ListOfContentSourceTypeContentSource[] ContentSourceList
        {
            get
            {
                return contentSourceListField;
            }
            set
            {
                contentSourceListField = value;
            }
        }

        /// <remarks/>
        [XmlArrayItem("Description", IsNullable = false)]
        public Description[] DescriptionList
        {
            get
            {
                return descriptionListField;
            }
            set
            {
                descriptionListField = value;
            }
        }

        /// <remarks/>
        [XmlArrayItem("Disclosures", IsNullable = false)]
        public ListOfDisclosureTypeDisclosures[] DisclosureList
        {
            get
            {
                return disclosureListField;
            }
            set
            {
                disclosureListField = value;
            }
        }

        /// <remarks/>
        [XmlArrayItem("FareGroup", IsNullable = false)]
        public FareListFareGroup[] FareList
        {
            get
            {
                return fareListField;
            }
            set
            {
                fareListField = value;
            }
        }

        /// <remarks/>
        [XmlArrayItem("FlightSegment", IsNullable = false)]
        public ListOfFlightSegmentType[] FlightSegmentList
        {
            get
            {
                return flightSegmentListField;
            }
            set
            {
                flightSegmentListField = value;
            }
        }

        /// <remarks/>
        [XmlArrayItem("Flight", IsNullable = false)]
        public SeatAvailabilityRQDataListsFlight[] FlightList
        {
            get
            {
                return flightListField;
            }
            set
            {
                flightListField = value;
            }
        }

        /// <remarks/>
        [XmlArrayItem("OriginDestination", IsNullable = false)]
        public OriginDestination[] OriginDestinationList
        {
            get
            {
                return originDestinationListField;
            }
            set
            {
                originDestinationListField = value;
            }
        }

        /// <remarks/>
        [XmlArrayItem("Instruction", IsNullable = false)]
        public ListOfOfferInstructionsTypeInstruction[] InstructionsList
        {
            get
            {
                return instructionsListField;
            }
            set
            {
                instructionsListField = value;
            }
        }

        /// <remarks/>
        [XmlArrayItem("Media", IsNullable = false)]
        public ListOfMediaTypeMedia[] MediaList
        {
            get
            {
                return mediaListField;
            }
            set
            {
                mediaListField = value;
            }
        }

        /// <remarks/>
        [XmlArrayItem("Penalty", IsNullable = false)]
        public ListOfOfferPenaltyTypePenalty[] PenaltyList
        {
            get
            {
                return penaltyListField;
            }
            set
            {
                penaltyListField = value;
            }
        }

        /// <remarks/>
        [XmlArrayItem("PriceClass", IsNullable = false)]
        public PriceClassType[] PriceClassList
        {
            get
            {
                return priceClassListField;
            }
            set
            {
                priceClassListField = value;
            }
        }

        /// <remarks/>
        [XmlArrayItem("ServiceDefinition", IsNullable = false)]
        public ServiceDefinitionType[] ServiceDefinitionList
        {
            get
            {
                return serviceDefinitionListField;
            }
            set
            {
                serviceDefinitionListField = value;
            }
        }

        /// <remarks/>
        public ListOfOfferTermsType TermsList
        {
            get
            {
                return termsListField;
            }
            set
            {
                termsListField = value;
            }
        }

        /// <remarks/>
        [XmlArrayItem("SeatDefinition", IsNullable = false)]
        public SeatAvailabilityRQDataListsSeatDefinition[] SeatDefinitionList
        {
            get
            {
                return seatDefinitionListField;
            }
            set
            {
                seatDefinitionListField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCode("xsd", "4.0.30319.33440")]
    [Serializable()]
    public partial class SeatAvailabilityRQDataListsBaggageAllowance
    {

        private BaggageCategoryListType baggageCategoryField;

        private BagAllowanceDescType allowanceDescriptionField;

        private BagAllowanceDimensionType dimensionAllowanceField;

        private PieceAllowance[] pieceAllowanceField;

        private WeightAllowance weightAllowanceField;

        private BaggageDeterminingCarrierType baggageDeterminingCarrierField;

        private string baggageAllowanceIDField;

        /// <remarks/>
        public BaggageCategoryListType BaggageCategory
        {
            get
            {
                return baggageCategoryField;
            }
            set
            {
                baggageCategoryField = value;
            }
        }

        /// <remarks/>
        public BagAllowanceDescType AllowanceDescription
        {
            get
            {
                return allowanceDescriptionField;
            }
            set
            {
                allowanceDescriptionField = value;
            }
        }

        /// <remarks/>
        public BagAllowanceDimensionType DimensionAllowance
        {
            get
            {
                return dimensionAllowanceField;
            }
            set
            {
                dimensionAllowanceField = value;
            }
        }

        /// <remarks/>
        [XmlElement("PieceAllowance")]
        public PieceAllowance[] PieceAllowance
        {
            get
            {
                return pieceAllowanceField;
            }
            set
            {
                pieceAllowanceField = value;
            }
        }

        /// <remarks/>
        public WeightAllowance WeightAllowance
        {
            get
            {
                return weightAllowanceField;
            }
            set
            {
                weightAllowanceField = value;
            }
        }

        /// <remarks/>
        public BaggageDeterminingCarrierType BaggageDeterminingCarrier
        {
            get
            {
                return baggageDeterminingCarrierField;
            }
            set
            {
                baggageDeterminingCarrierField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute(DataType = "ID")]
        public string BaggageAllowanceID
        {
            get
            {
                return baggageAllowanceIDField;
            }
            set
            {
                baggageAllowanceIDField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCode("xsd", "4.0.30319.33440")]
    [Serializable()]
    public partial class SeatAvailabilityRQDataListsFlight
    {

        private TotalJourneyType journeyField;

        private SegmentReferences segmentReferencesField;

        private SeatAvailabilityRQDataListsFlightSettlement settlementField;

        private string refsField;

        private string flightKeyField;

        /// <remarks/>
        public TotalJourneyType Journey
        {
            get
            {
                return journeyField;
            }
            set
            {
                journeyField = value;
            }
        }

        /// <remarks/>
        public SegmentReferences SegmentReferences
        {
            get
            {
                return segmentReferencesField;
            }
            set
            {
                segmentReferencesField = value;
            }
        }

        /// <remarks/>
        public SeatAvailabilityRQDataListsFlightSettlement Settlement
        {
            get
            {
                return settlementField;
            }
            set
            {
                settlementField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute(DataType = "IDREFS")]
        public string refs
        {
            get
            {
                return refsField;
            }
            set
            {
                refsField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute(DataType = "ID")]
        public string FlightKey
        {
            get
            {
                return flightKeyField;
            }
            set
            {
                flightKeyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCode("xsd", "4.0.30319.33440")]
    [Serializable()]
    public partial class SeatAvailabilityRQDataListsFlightSettlement
    {

        private string methodField;

        private CurrencyAmountOptType interlineSettlementValueField;

        /// <remarks/>
        public string Method
        {
            get
            {
                return methodField;
            }
            set
            {
                methodField = value;
            }
        }

        /// <remarks/>
        public CurrencyAmountOptType InterlineSettlementValue
        {
            get
            {
                return interlineSettlementValueField;
            }
            set
            {
                interlineSettlementValueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCode("xsd", "4.0.30319.33440")]
    [Serializable()]
    public partial class SeatAvailabilityRQDataListsSeatDefinition
    {

        private SeatAvailabilityRQDataListsSeatDefinitionDescription[] descriptionField;

        private SeatAvailabilityRQDataListsSeatDefinitionMarketing marketingField;

        private string[] seatCharacteristicCodeField;

        private SizeUnitSimpleType uOMField;

        private bool uOMFieldSpecified;

        private decimal seatWidthLowField;

        private bool seatWidthLowFieldSpecified;

        private decimal seatPitchLowField;

        private bool seatPitchLowFieldSpecified;

        private KeyWordType[] keywordsField;

        private string seatDefinitionIDField;

        /// <remarks/>
        [XmlElement("Description")]
        public SeatAvailabilityRQDataListsSeatDefinitionDescription[] Description
        {
            get
            {
                return descriptionField;
            }
            set
            {
                descriptionField = value;
            }
        }

        /// <remarks/>
        public SeatAvailabilityRQDataListsSeatDefinitionMarketing Marketing
        {
            get
            {
                return marketingField;
            }
            set
            {
                marketingField = value;
            }
        }

        /// <remarks/>
        [XmlElement("SeatCharacteristicCode")]
        public string[] SeatCharacteristicCode
        {
            get
            {
                return seatCharacteristicCodeField;
            }
            set
            {
                seatCharacteristicCodeField = value;
            }
        }

        /// <remarks/>
        public SizeUnitSimpleType UOM
        {
            get
            {
                return uOMField;
            }
            set
            {
                uOMField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool UOMSpecified
        {
            get
            {
                return uOMFieldSpecified;
            }
            set
            {
                uOMFieldSpecified = value;
            }
        }

        /// <remarks/>
        public decimal SeatWidthLow
        {
            get
            {
                return seatWidthLowField;
            }
            set
            {
                seatWidthLowField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool SeatWidthLowSpecified
        {
            get
            {
                return seatWidthLowFieldSpecified;
            }
            set
            {
                seatWidthLowFieldSpecified = value;
            }
        }

        /// <remarks/>
        public decimal SeatPitchLow
        {
            get
            {
                return seatPitchLowField;
            }
            set
            {
                seatPitchLowField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool SeatPitchLowSpecified
        {
            get
            {
                return seatPitchLowFieldSpecified;
            }
            set
            {
                seatPitchLowFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlArrayItem("KeyWord", IsNullable = false)]
        public KeyWordType[] Keywords
        {
            get
            {
                return keywordsField;
            }
            set
            {
                keywordsField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute(DataType = "ID")]
        public string SeatDefinitionID
        {
            get
            {
                return seatDefinitionIDField;
            }
            set
            {
                seatDefinitionIDField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCode("xsd", "4.0.30319.33440")]
    [Serializable()]
    public partial class SeatAvailabilityRQDataListsSeatDefinitionDescription
    {

        private SeatAvailabilityRQDataListsSeatDefinitionDescriptionText textField;

        private string markupStyleField;

        private string linkField;

        private SeatAvailabilityRQDataListsSeatDefinitionDescriptionMedia[] mediaField;

        /// <remarks/>
        public SeatAvailabilityRQDataListsSeatDefinitionDescriptionText Text
        {
            get
            {
                return textField;
            }
            set
            {
                textField = value;
            }
        }

        /// <remarks/>
        public string MarkupStyle
        {
            get
            {
                return markupStyleField;
            }
            set
            {
                markupStyleField = value;
            }
        }

        /// <remarks/>
        public string Link
        {
            get
            {
                return linkField;
            }
            set
            {
                linkField = value;
            }
        }

        /// <remarks/>
        [XmlElement("Media")]
        public SeatAvailabilityRQDataListsSeatDefinitionDescriptionMedia[] Media
        {
            get
            {
                return mediaField;
            }
            set
            {
                mediaField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCode("xsd", "4.0.30319.33440")]
    [Serializable()]
    public partial class SeatAvailabilityRQDataListsSeatDefinitionDescriptionText
    {

        private string refsField;

        private string valueField;

        /// <remarks/>
        [XmlAttribute(DataType = "IDREFS")]
        public string refs
        {
            get
            {
                return refsField;
            }
            set
            {
                refsField = value;
            }
        }

        /// <remarks/>
        [XmlText()]
        public string Value
        {
            get
            {
                return valueField;
            }
            set
            {
                valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCode("xsd", "4.0.30319.33440")]
    [Serializable()]
    public partial class SeatAvailabilityRQDataListsSeatDefinitionDescriptionMedia
    {

        private object itemField;

        private ItemChoiceType10_extended itemElementNameField;

        /// <remarks/>
        [XmlElement("AttachmentID", typeof(MediaID_Type))]
        [XmlElement("MediaLink", typeof(MediaLink))]
        [XmlElement("ObjectID", typeof(MediaID_Type))]
        [XmlChoiceIdentifier("ItemElementName")]
        public object Item
        {
            get
            {
                return itemField;
            }
            set
            {
                itemField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public ItemChoiceType10_extended ItemElementName
        {
            get
            {
                return itemElementNameField;
            }
            set
            {
                itemElementNameField = value;
            }
        }
    }


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCode("xsd", "4.0.30319.33440")]
    [Serializable()]
    public partial class SeatAvailabilityRQDataListsSeatDefinitionMarketing : SeatMapMessageType
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCode("xsd", "4.0.30319.33440")]
    [Serializable()]
    public enum SeatAvailabilityRQTarget
    {

        /// <remarks/>
        Test,

        /// <remarks/>
        Production
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCode("xsd", "4.0.30319.33440")]
    [Serializable()]
    public enum SeatAvailabilityRQTransactionStatusCode
    {

        /// <remarks/>
        Start,

        /// <remarks/>
        End,

        /// <remarks/>
        Rollback,

        /// <remarks/>
        InSeries,

        /// <remarks/>
        Continuation,

        /// <remarks/>
        Subsequent
    }


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCode("xsd", "4.0.30319.33440")]
    [Serializable()]
    public partial class SeatAvailReqMetadataType
    {

        private SeatAvailReqMetadataTypeShopping shoppingField;

        private SeatAvailReqMetadataTypePassenger passengerField;

        private SeatAvailReqMetadataTypeOtherMetadata[] otherField;

        /// <remarks/>
        public SeatAvailReqMetadataTypeShopping Shopping
        {
            get
            {
                return shoppingField;
            }
            set
            {
                shoppingField = value;
            }
        }

        /// <remarks/>
        public SeatAvailReqMetadataTypePassenger Passenger
        {
            get
            {
                return passengerField;
            }
            set
            {
                passengerField = value;
            }
        }

        /// <remarks/>
        [XmlArrayItem("OtherMetadata", IsNullable = false)]
        public SeatAvailReqMetadataTypeOtherMetadata[] Other
        {
            get
            {
                return otherField;
            }
            set
            {
                otherField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCode("xsd", "4.0.30319.33440")]
    [Serializable()]
    public partial class SeatAvailReqMetadataTypeShopping
    {

        private ShopMetadataGroup shopMetadataGroupField;

        /// <remarks/>
        public ShopMetadataGroup ShopMetadataGroup
        {
            get
            {
                return shopMetadataGroupField;
            }
            set
            {
                shopMetadataGroupField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCode("xsd", "4.0.30319.33440")]
    [Serializable()]
    public partial class SeatAvailReqMetadataTypePassenger
    {

        private PassengerMetadataType passengerMetadataField;

        /// <remarks/>
        public PassengerMetadataType PassengerMetadata
        {
            get
            {
                return passengerMetadataField;
            }
            set
            {
                passengerMetadataField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCode("xsd", "4.0.30319.33440")]
    [Serializable()]
    public partial class SeatAvailReqMetadataTypeOtherMetadata
    {

        private object itemField;

        /// <remarks/>
        [XmlElement("AddressMetadatas", typeof(AddressMetadatas))]
        [XmlElement("AircraftMetadatas", typeof(AircraftMetadatas))]
        [XmlElement("AirportMetadatas", typeof(AirportMetadatas))]
        [XmlElement("CityMetadatas", typeof(CityMetadatas))]
        [XmlElement("CodesetMetadatas", typeof(CodesetMetadatas))]
        [XmlElement("ContactMetadatas", typeof(ContactMetadatas))]
        [XmlElement("CountryMetadatas", typeof(CountryMetadatas))]
        [XmlElement("CurrencyMetadatas", typeof(CurrencyMetadatas))]
        [XmlElement("DescriptionMetadatas", typeof(DescriptionMetadatas))]
        [XmlElement("EquivalentID_Metadatas", typeof(EquivalentID_Metadatas))]
        [XmlElement("LanguageMetadatas", typeof(LanguageMetadatas))]
        [XmlElement("PaymentCardMetadatas", typeof(PaymentCardMetadatas))]
        [XmlElement("PaymentFormMetadatas", typeof(PaymentFormMetadatas))]
        [XmlElement("PriceMetadatas", typeof(PriceMetadatas))]
        [XmlElement("RuleMetadatas", typeof(RuleMetadatas))]
        [XmlElement("StateProvMetadatas", typeof(StateProvMetadatas))]
        [XmlElement("ZoneMetadatas", typeof(ZoneMetadatas))]
        public object Item
        {
            get
            {
                return itemField;
            }
            set
            {
                itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCode("xsd", "4.0.30319.33440")]
    [Serializable()]
    public partial class SeatAvailReqParamsType : MessageParamsBaseType
    {

        private SeatAvailReqParamsTypeInventory inventoryField;

        private SeatAvailReqParamsTypeServiceFilters serviceFiltersField;

        private SeatAvailReqParamsTypePricing pricingField;

        private SeatAvailReqParamsTypeGroup groupField;

        /// <remarks/>
        public SeatAvailReqParamsTypeInventory Inventory
        {
            get
            {
                return inventoryField;
            }
            set
            {
                inventoryField = value;
            }
        }

        /// <remarks/>
        public SeatAvailReqParamsTypeServiceFilters ServiceFilters
        {
            get
            {
                return serviceFiltersField;
            }
            set
            {
                serviceFiltersField = value;
            }
        }

        /// <remarks/>
        public SeatAvailReqParamsTypePricing Pricing
        {
            get
            {
                return pricingField;
            }
            set
            {
                pricingField = value;
            }
        }

        /// <remarks/>
        public SeatAvailReqParamsTypeGroup Group
        {
            get
            {
                return groupField;
            }
            set
            {
                groupField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCode("xsd", "4.0.30319.33440")]
    [Serializable()]
    public partial class SeatAvailReqParamsTypeInventory
    {

        private bool guaranteeIndField;

        private bool guaranteeIndFieldSpecified;

        /// <remarks/>
        public bool GuaranteeInd
        {
            get
            {
                return guaranteeIndField;
            }
            set
            {
                guaranteeIndField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool GuaranteeIndSpecified
        {
            get
            {
                return guaranteeIndFieldSpecified;
            }
            set
            {
                guaranteeIndFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCode("xsd", "4.0.30319.33440")]
    [Serializable()]
    public partial class SeatAvailReqParamsTypeServiceFilters : AssociatedObjectBaseType
    {

        private ServiceFilterType[] serviceFilterField;

        /// <remarks/>
        [XmlElement("ServiceFilter")]
        public ServiceFilterType[] ServiceFilter
        {
            get
            {
                return serviceFilterField;
            }
            set
            {
                serviceFilterField = value;
            }
        }
    }


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCode("xsd", "4.0.30319.33440")]
    [Serializable()]
    public partial class SeatAvailReqParamsTypePricing
    {

        private string overrideCurrencyField;

        private SeatAvailReqParamsTypePricingFeeExemption feeExemptionField;

        private bool autoExchangeIndField;

        private bool autoExchangeIndFieldSpecified;

        private bool awardIncludedIndField;

        private bool awardIncludedIndFieldSpecified;

        private bool awardOnlyIndField;

        private bool awardOnlyIndFieldSpecified;

        private bool simpleIndField;

        private bool simpleIndFieldSpecified;

        /// <remarks/>
        public string OverrideCurrency
        {
            get
            {
                return overrideCurrencyField;
            }
            set
            {
                overrideCurrencyField = value;
            }
        }

        /// <remarks/>
        public SeatAvailReqParamsTypePricingFeeExemption FeeExemption
        {
            get
            {
                return feeExemptionField;
            }
            set
            {
                feeExemptionField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public bool AutoExchangeInd
        {
            get
            {
                return autoExchangeIndField;
            }
            set
            {
                autoExchangeIndField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool AutoExchangeIndSpecified
        {
            get
            {
                return autoExchangeIndFieldSpecified;
            }
            set
            {
                autoExchangeIndFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public bool AwardIncludedInd
        {
            get
            {
                return awardIncludedIndField;
            }
            set
            {
                awardIncludedIndField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool AwardIncludedIndSpecified
        {
            get
            {
                return awardIncludedIndFieldSpecified;
            }
            set
            {
                awardIncludedIndFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public bool AwardOnlyInd
        {
            get
            {
                return awardOnlyIndField;
            }
            set
            {
                awardOnlyIndField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool AwardOnlyIndSpecified
        {
            get
            {
                return awardOnlyIndFieldSpecified;
            }
            set
            {
                awardOnlyIndFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public bool SimpleInd
        {
            get
            {
                return simpleIndField;
            }
            set
            {
                simpleIndField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool SimpleIndSpecified
        {
            get
            {
                return simpleIndFieldSpecified;
            }
            set
            {
                simpleIndFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCode("xsd", "4.0.30319.33440")]
    [Serializable()]
    public partial class SeatAvailReqParamsTypePricingFeeExemption : AssociatedObjectBaseType
    {

        private SeatAvailReqParamsTypePricingFeeExemptionFee[] feeField;

        private CountryCode[] countryCodeField;

        private string[] provinceCodeField;

        private string governmentBodyField;

        /// <remarks/>
        [XmlElement("Fee")]
        public SeatAvailReqParamsTypePricingFeeExemptionFee[] Fee
        {
            get
            {
                return feeField;
            }
            set
            {
                feeField = value;
            }
        }

        /// <remarks/>
        [XmlElement("CountryCode")]
        public CountryCode[] CountryCode
        {
            get
            {
                return countryCodeField;
            }
            set
            {
                countryCodeField = value;
            }
        }

        /// <remarks/>
        [XmlElement("ProvinceCode")]
        public string[] ProvinceCode
        {
            get
            {
                return provinceCodeField;
            }
            set
            {
                provinceCodeField = value;
            }
        }

        /// <remarks/>
        public string GovernmentBody
        {
            get
            {
                return governmentBodyField;
            }
            set
            {
                governmentBodyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCode("xsd", "4.0.30319.33440")]
    [Serializable()]
    public partial class SeatAvailReqParamsTypePricingFeeExemptionFee
    {

        private SeatAvailReqParamsTypePricingFeeExemptionFeeCode codeField;

        private string[] taxTypeField;

        private string refsField;

        /// <remarks/>
        public SeatAvailReqParamsTypePricingFeeExemptionFeeCode Code
        {
            get
            {
                return codeField;
            }
            set
            {
                codeField = value;
            }
        }

        /// <remarks/>
        [XmlElement("TaxType")]
        public string[] TaxType
        {
            get
            {
                return taxTypeField;
            }
            set
            {
                taxTypeField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute(DataType = "IDREFS")]
        public string refs
        {
            get
            {
                return refsField;
            }
            set
            {
                refsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCode("xsd", "4.0.30319.33440")]
    [Serializable()]
    public partial class SeatAvailReqParamsTypePricingFeeExemptionFeeCode
    {

        private string collectionPointField;

        private string valueField;

        /// <remarks/>
        [XmlAttribute()]
        public string CollectionPoint
        {
            get
            {
                return collectionPointField;
            }
            set
            {
                collectionPointField = value;
            }
        }

        /// <remarks/>
        [XmlText()]
        public string Value
        {
            get
            {
                return valueField;
            }
            set
            {
                valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCode("xsd", "4.0.30319.33440")]
    [Serializable()]
    public partial class SeatAvailReqParamsTypeGroup
    {

        private PrimaryContact primaryContactField;

        /// <remarks/>
        public PrimaryContact PrimaryContact
        {
            get
            {
                return primaryContactField;
            }
            set
            {
                primaryContactField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCode("xsd", "4.0.30319.33440")]
    [Serializable()]
    public partial class QualifiersTypeQualifier
    {

        private SeatQualifierAssignment[] seatQualifierField;

        private ServiceQualifierPriceType serviceQualifierField;

        private OrderItemAssociationType associationsField;

        private string refsField;

        /// <remarks/>
        [XmlArrayItem("Assignment", IsNullable = false)]
        public SeatQualifierAssignment[] SeatQualifier
        {
            get
            {
                return seatQualifierField;
            }
            set
            {
                seatQualifierField = value;
            }
        }

        /// <remarks/>
        public ServiceQualifierPriceType ServiceQualifier
        {
            get
            {
                return serviceQualifierField;
            }
            set
            {
                serviceQualifierField = value;
            }
        }

        /// <remarks/>
        public OrderItemAssociationType Associations
        {
            get
            {
                return associationsField;
            }
            set
            {
                associationsField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute(DataType = "IDREFS")]
        public string refs
        {
            get
            {
                return refsField;
            }
            set
            {
                refsField = value;
            }
        }
    }




}