// ------------------------------------------------------------------------------
// <autogenerated>
// This code was generated by a tool.
// Runtime Version: 1.1.4322.2407
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated.
// </autogenerated>
// ------------------------------------------------------------------------------

using System;
using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=1.1.4322.2407.
// 
namespace wsTripXML.wsTravelTalk.wmCarRulesIn
{

    // <remarks/>
    [XmlType()]
    [XmlRoot(IsNullable = false)]
    public class OTA_VehRateRuleRQ
    {

        // <remarks/>
        public POS_Type POS;

        // <remarks/>
        public UniqueID_Type Reference;

        // <remarks/>
        public OTA_VehRateRuleRQRentalInfo RentalInfo;

        // <remarks/>
        [XmlAttribute()]
        public string EchoToken;

        // <remarks/>
        [XmlAttribute()]
        public DateTime TimeStamp;

        // <remarks/>
        [XmlIgnore()]
        public bool TimeStampSpecified;

        // <remarks/>
        [XmlAttribute()]
        [System.ComponentModel.DefaultValue(OTA_VehRateRuleRQTarget.Production)]
        public OTA_VehRateRuleRQTarget Target = OTA_VehRateRuleRQTarget.Production;

        // <remarks/>
        [XmlAttribute()]
        public decimal Version;

        // <remarks/>
        [XmlAttribute()]
        public string TransactionIdentifier;

        // <remarks/>
        [XmlAttribute(DataType = "nonNegativeInteger")]
        public string SequenceNmbr;

        // <remarks/>
        [XmlAttribute()]
        public OTA_VehRateRuleRQTransactionStatusCode TransactionStatusCode;

        // <remarks/>
        [XmlIgnore()]
        public bool TransactionStatusCodeSpecified;

        // <remarks/>
        [XmlAttribute()]
        public bool RetransmissionIndicator;

        // <remarks/>
        [XmlIgnore()]
        public bool RetransmissionIndicatorSpecified;

        // <remarks/>
        [XmlAttribute()]
        public string CompanyShortName;

        // <remarks/>
        [XmlAttribute()]
        public string TravelSector;

        // <remarks/>
        [XmlAttribute()]
        public string Code;

        // <remarks/>
        [XmlAttribute()]
        public string CodeContext;
    }

    // <remarks/>
    [XmlType()]
    public class POS_Type
    {

        // <remarks/>
        [XmlElement("Source")]
        public SourceType[] Source;

        // <remarks/>
        public TPA_Extensions TPA_Extensions;
    }

    // <remarks/>
    [XmlType()]
    public class SourceType
    {

        // <remarks/>
        public SourceTypeRequestorID RequestorID;

        // <remarks/>
        public SourceTypePosition Position;

        // <remarks/>
        public SourceTypeBookingChannel BookingChannel;

        // <remarks/>
        [XmlAttribute()]
        public string AgentSine;

        // <remarks/>
        [XmlAttribute()]
        public string PseudoCityCode;

        // <remarks/>
        [XmlAttribute()]
        public string ISOCountry;

        // <remarks/>
        [XmlAttribute()]
        public string ISOCurrency;

        // <remarks/>
        [XmlAttribute()]
        public string AgentDutyCode;

        // <remarks/>
        [XmlAttribute()]
        public string AirlineVendorID;

        // <remarks/>
        [XmlAttribute()]
        public string AirportCode;

        // <remarks/>
        [XmlAttribute()]
        public string FirstDepartPoint;

        // <remarks/>
        [XmlAttribute()]
        public string ERSP_UserID;

        // <remarks/>
        [XmlAttribute()]
        public string TerminalID;
    }

    // <remarks/>
    [XmlType()]
    public class SourceTypeRequestorID : UniqueID_Type
    {

        // <remarks/>
        [XmlAttribute()]
        public string MessagePassword;
    }

    // <remarks/>
    [XmlType()]
    [XmlInclude(typeof(SourceTypeRequestorID))]
    public class UniqueID_Type
    {

        // <remarks/>
        public CompanyNameType CompanyName;

        // <remarks/>
        [XmlAttribute(DataType = "anyURI")]
        public string URL;

        // <remarks/>
        [XmlAttribute()]
        public string Type;

        // <remarks/>
        [XmlAttribute()]
        public string Instance;

        // <remarks/>
        [XmlAttribute()]
        public string ID;

        // <remarks/>
        [XmlAttribute()]
        public string ID_Context;
    }

    // <remarks/>
    [XmlType()]
    public class CompanyNameType
    {

        // <remarks/>
        [XmlAttribute()]
        public string CompanyShortName;

        // <remarks/>
        [XmlAttribute()]
        public string TravelSector;

        // <remarks/>
        [XmlAttribute()]
        public string Code;

        // <remarks/>
        [XmlAttribute()]
        public string CodeContext;

        // <remarks/>
        [XmlAttribute()]
        public string Division;

        // <remarks/>
        [XmlAttribute()]
        public string Department;

        // <remarks/>
        [XmlText()]
        public string Value;
    }

    // <remarks/>
    [XmlType()]
    public class VehicleTourInfoType
    {

        // <remarks/>
        public CompanyNameType TourOperator;

        // <remarks/>
        [XmlAttribute()]
        public string TourNumber;
    }

    // <remarks/>
    [XmlType()]
    public class VehicleArrivalDetailsType
    {

        // <remarks/>
        public LocationType ArrivalLocation;

        // <remarks/>
        public CompanyNameType MarketingCompany;

        // <remarks/>
        public CompanyNameType OperatingCompany;

        // <remarks/>
        [XmlAttribute()]
        public string TransportationCode;

        // <remarks/>
        [XmlAttribute()]
        public string Number;

        // <remarks/>
        [XmlAttribute()]
        public DateTime ArrivalDateTime;

        // <remarks/>
        [XmlIgnore()]
        public bool ArrivalDateTimeSpecified;
    }

    // <remarks/>
    [XmlType()]
    [XmlInclude(typeof(VehicleRentalCoreTypeReturnLocation))]
    [XmlInclude(typeof(VehicleRentalCoreTypePickUpLocation))]
    public class LocationType
    {

        // <remarks/>
        [XmlAttribute()]
        public string LocationCode;

        // <remarks/>
        [XmlAttribute()]
        [System.ComponentModel.DefaultValue("IATA")]
        public string CodeContext = "IATA";

        // <remarks/>
        [XmlText()]
        public string Value;
    }

    // <remarks/>
    [XmlType()]
    public class VehicleRentalCoreTypeReturnLocation : LocationType
    {

        // <remarks/>
        [XmlAttribute()]
        public string ExtendedLocationCode;

        // <remarks/>
        [XmlAttribute()]
        public string CounterLocation;
    }

    // <remarks/>
    [XmlType()]
    public class VehicleRentalCoreTypePickUpLocation : LocationType
    {

        // <remarks/>
        [XmlAttribute()]
        public string ExtendedLocationCode;

        // <remarks/>
        [XmlAttribute()]
        public string CounterLocation;
    }

    // <remarks/>
    [XmlType()]
    public class OffLocationServiceTypeTelephone
    {
    }

    // <remarks/>
    [XmlType()]
    public class PersonNameType
    {

        // <remarks/>
        [XmlElement("NamePrefix")]
        public string[] NamePrefix;

        // <remarks/>
        [XmlElement("GivenName")]
        public string[] GivenName;

        // <remarks/>
        [XmlElement("MiddleName")]
        public string[] MiddleName;

        // <remarks/>
        public string SurnamePrefix;

        // <remarks/>
        public string Surname;

        // <remarks/>
        [XmlElement("NameSuffix")]
        public string[] NameSuffix;

        // <remarks/>
        [XmlElement("NameTitle")]
        public string[] NameTitle;

        // <remarks/>
        [XmlAttribute()]
        public AddressTypeShareSynchInd ShareSynchInd;

        // <remarks/>
        [XmlIgnore()]
        public bool ShareSynchIndSpecified;

        // <remarks/>
        [XmlAttribute()]
        public AddressTypeShareMarketInd ShareMarketInd;

        // <remarks/>
        [XmlIgnore()]
        public bool ShareMarketIndSpecified;

        // <remarks/>
        [XmlAttribute()]
        public string NameType;
    }

    // <remarks/>
    [XmlType()]
    public enum AddressTypeShareSynchInd
    {

        // <remarks/>
        Yes,

        // <remarks/>
        No,

        // <remarks/>
        Inherit
    }

    // <remarks/>
    [XmlType()]
    public enum AddressTypeShareMarketInd
    {

        // <remarks/>
        Yes,

        // <remarks/>
        No,

        // <remarks/>
        Inherit
    }

    // <remarks/>
    [XmlType()]
    public class CountryNameType
    {

        // <remarks/>
        [XmlAttribute()]
        public string Code;

        // <remarks/>
        [XmlText()]
        public string Value;
    }

    // <remarks/>
    [XmlType()]
    public class StateProvType
    {

        // <remarks/>
        [XmlAttribute()]
        public string StateCode;

        // <remarks/>
        [XmlText()]
        public string Value;
    }

    // <remarks/>
    [XmlType()]
    public class AddressTypeBldgRoom
    {

        // <remarks/>
        [XmlAttribute()]
        public bool BldgNameIndicator;

        // <remarks/>
        [XmlIgnore()]
        public bool BldgNameIndicatorSpecified;

        // <remarks/>
        [XmlText()]
        public string Value;
    }

    // <remarks/>
    [XmlType()]
    [XmlInclude(typeof(AddressTypeStreetNmbr))]
    public class StreetNmbrType
    {

        // <remarks/>
        [XmlAttribute()]
        public string PO_Box;

        // <remarks/>
        [XmlText()]
        public string Value;
    }

    // <remarks/>
    [XmlType()]
    public class AddressTypeStreetNmbr : StreetNmbrType
    {

        // <remarks/>
        [XmlAttribute()]
        public string StreetNmbrSuffix;

        // <remarks/>
        [XmlAttribute()]
        public string StreetDirection;

        // <remarks/>
        [XmlAttribute()]
        public string RuralRouteNmbr;
    }

    // <remarks/>
    [XmlType()]
    [XmlInclude(typeof(OffLocationServiceCoreTypeAddress))]
    public class AddressType
    {

        // <remarks/>
        public AddressTypeStreetNmbr StreetNmbr;

        // <remarks/>
        [XmlElement("BldgRoom")]
        public AddressTypeBldgRoom[] BldgRoom;

        // <remarks/>
        [XmlElement("AddressLine")]
        public string[] AddressLine;

        // <remarks/>
        public string CityName;

        // <remarks/>
        public string PostalCode;

        // <remarks/>
        public string County;

        // <remarks/>
        public StateProvType StateProv;

        // <remarks/>
        public CountryNameType CountryName;

        // <remarks/>
        [XmlAttribute()]
        [System.ComponentModel.DefaultValue(false)]
        public bool FormattedInd = false;

        // <remarks/>
        [XmlAttribute()]
        public AddressTypeShareSynchInd ShareSynchInd;

        // <remarks/>
        [XmlIgnore()]
        public bool ShareSynchIndSpecified;

        // <remarks/>
        [XmlAttribute()]
        public AddressTypeShareMarketInd ShareMarketInd;

        // <remarks/>
        [XmlIgnore()]
        public bool ShareMarketIndSpecified;

        // <remarks/>
        [XmlAttribute()]
        public string Type;
    }

    // <remarks/>
    [XmlType()]
    public class OffLocationServiceCoreTypeAddress : AddressType
    {

        // <remarks/>
        [XmlAttribute()]
        public string SiteID;

        // <remarks/>
        [XmlAttribute()]
        public string SiteName;
    }

    // <remarks/>
    [XmlType()]
    [XmlInclude(typeof(OffLocationServiceType))]
    public class OffLocationServiceCoreType
    {

        // <remarks/>
        public OffLocationServiceCoreTypeAddress Address;

        // <remarks/>
        [XmlAttribute()]
        public OffLocationServiceID_Type Type;
    }

    // <remarks/>
    [XmlType()]
    public enum OffLocationServiceID_Type
    {

        // <remarks/>
        CustPickUp,

        // <remarks/>
        VehDelivery,

        // <remarks/>
        CustDropOff,

        // <remarks/>
        VehCollection,

        // <remarks/>
        Exchange
    }

    // <remarks/>
    [XmlType()]
    public class OffLocationServiceType : OffLocationServiceCoreType
    {

        // <remarks/>
        public PersonNameType PersonName;

        // <remarks/>
        public OffLocationServiceTypeTelephone Telephone;

        // <remarks/>
        [XmlAttribute()]
        public string SpecInstructions;
    }

    // <remarks/>
    [XmlType()]
    public class OTA_VehRateRuleRQRentalInfoRateQualifier
    {

        // <remarks/>
        [XmlAttribute()]
        public string TravelPurpose;

        // <remarks/>
        [XmlAttribute()]
        public string RateCategory;

        // <remarks/>
        [XmlAttribute()]
        public string CorpDiscountNmbr;

        // <remarks/>
        [XmlAttribute()]
        public string RateQualifier;

        // <remarks/>
        [XmlAttribute(DataType = "NMTOKEN")]
        public string RatePeriod;

        // <remarks/>
        [XmlAttribute()]
        public bool GuaranteedInd;

        // <remarks/>
        [XmlIgnore()]
        public bool GuaranteedIndSpecified;

        // <remarks/>
        [XmlAttribute()]
        public string RateAuthorizationCode;

        // <remarks/>
        [XmlAttribute()]
        public string VendorRateID;

        // <remarks/>
        [XmlAttribute()]
        public bool RateModifiedInd;

        // <remarks/>
        [XmlIgnore()]
        public bool RateModifiedIndSpecified;
    }

    // <remarks/>
    [XmlType()]
    public class OTA_VehRateRuleRQRentalInfoCustLoyalty
    {

        // <remarks/>
        [XmlAttribute()]
        public string ProgramID;

        // <remarks/>
        [XmlAttribute()]
        public string MembershipID;

        // <remarks/>
        [XmlAttribute()]
        public string TravelSector;

        // <remarks/>
        [XmlAttribute()]
        public string RPH;

        // <remarks/>
        [XmlAttribute()]
        public string[] VendorCode;
    }

    // <remarks/>
    [XmlType()]
    public class OTA_VehRateRuleRQRentalInfoSpecialEquipPref
    {

        // <remarks/>
        [XmlAttribute()]
        public ActionType Action;

        // <remarks/>
        [XmlIgnore()]
        public bool ActionSpecified;
    }

    // <remarks/>
    [XmlType()]
    public enum ActionType
    {

        // <remarks/>
        [XmlEnum("Add-Update")]
        AddUpdate,

        // <remarks/>
        Cancel,

        // <remarks/>
        Delete,

        // <remarks/>
        Add,

        // <remarks/>
        Replace
    }

    // <remarks/>
    [XmlType()]
    public class VehicleCoreTypeVehClass
    {

        // <remarks/>
        [XmlAttribute()]
        public string Size;
    }

    // <remarks/>
    [XmlType()]
    public class VehicleCoreTypeVehType
    {

        // <remarks/>
        [XmlAttribute()]
        public string VehicleCategory;

        // <remarks/>
        [XmlAttribute()]
        public string DoorCount;
    }

    // <remarks/>
    [XmlType()]
    [XmlInclude(typeof(VehiclePrefType))]
    public class VehicleCoreType
    {

        // <remarks/>
        public VehicleCoreTypeVehType VehType;

        // <remarks/>
        public VehicleCoreTypeVehClass VehClass;

        // <remarks/>
        [XmlAttribute()]
        public bool AirConditionInd;

        // <remarks/>
        [XmlIgnore()]
        public bool AirConditionIndSpecified;

        // <remarks/>
        [XmlAttribute()]
        public VehicleTransmissionType TransmissionType;

        // <remarks/>
        [XmlIgnore()]
        public bool TransmissionTypeSpecified;

        // <remarks/>
        [XmlAttribute()]
        public VehicleCoreTypeFuelType FuelType;

        // <remarks/>
        [XmlIgnore()]
        public bool FuelTypeSpecified;

        // <remarks/>
        [XmlAttribute()]
        public VehicleCoreTypeDriveType DriveType;

        // <remarks/>
        [XmlIgnore()]
        public bool DriveTypeSpecified;
    }

    // <remarks/>
    [XmlType()]
    public enum VehicleTransmissionType
    {

        // <remarks/>
        Automatic,

        // <remarks/>
        Manual
    }

    // <remarks/>
    [XmlType()]
    public enum VehicleCoreTypeFuelType
    {

        // <remarks/>
        Unspecified,

        // <remarks/>
        Diesel,

        // <remarks/>
        Hybrid,

        // <remarks/>
        Electric,

        // <remarks/>
        LPG_CompressedGas,

        // <remarks/>
        Hydrogen,

        // <remarks/>
        MultiFuel,

        // <remarks/>
        Petrol,

        // <remarks/>
        Ethanol
    }

    // <remarks/>
    [XmlType()]
    public enum VehicleCoreTypeDriveType
    {

        // <remarks/>
        AWD,

        // <remarks/>
        [XmlEnum("4WD")]
        Item4WD,

        // <remarks/>
        Unspecified
    }

    // <remarks/>
    [XmlType()]
    public class VehiclePrefType : VehicleCoreType
    {

        // <remarks/>
        [XmlAttribute()]
        public PreferLevelType TypePref;

        // <remarks/>
        [XmlIgnore()]
        public bool TypePrefSpecified;

        // <remarks/>
        [XmlAttribute()]
        public PreferLevelType ClassPref;

        // <remarks/>
        [XmlIgnore()]
        public bool ClassPrefSpecified;

        // <remarks/>
        [XmlAttribute()]
        public PreferLevelType AirConditionPref;

        // <remarks/>
        [XmlIgnore()]
        public bool AirConditionPrefSpecified;

        // <remarks/>
        [XmlAttribute()]
        public PreferLevelType TransmissionPref;

        // <remarks/>
        [XmlIgnore()]
        public bool TransmissionPrefSpecified;

        // <remarks/>
        [XmlAttribute()]
        public string VendorCarType;

        // <remarks/>
        [XmlAttribute(DataType = "nonNegativeInteger")]
        public string VehicleQty;

        // <remarks/>
        [XmlAttribute()]
        public string Code;

        // <remarks/>
        [XmlAttribute()]
        public string CodeContext;
    }

    // <remarks/>
    [XmlType()]
    public enum PreferLevelType
    {

        // <remarks/>
        Only,

        // <remarks/>
        Unacceptable,

        // <remarks/>
        Preferred,

        // <remarks/>
        Required,

        // <remarks/>
        NoPreference
    }

    // <remarks/>
    [XmlType()]
    public class VehicleRentalCoreType
    {

        // <remarks/>
        [XmlElement("PickUpLocation")]
        public VehicleRentalCoreTypePickUpLocation[] PickUpLocation;

        // <remarks/>
        public VehicleRentalCoreTypeReturnLocation ReturnLocation;

        // <remarks/>
        [XmlAttribute()]
        public DateTime PickUpDateTime;

        // <remarks/>
        [XmlIgnore()]
        public bool PickUpDateTimeSpecified;

        // <remarks/>
        [XmlAttribute()]
        public DateTime ReturnDateTime;

        // <remarks/>
        [XmlIgnore()]
        public bool ReturnDateTimeSpecified;

        // <remarks/>
        [XmlAttribute()]
        public DateTime StartChargesDateTime;

        // <remarks/>
        [XmlIgnore()]
        public bool StartChargesDateTimeSpecified;

        // <remarks/>
        [XmlAttribute()]
        public DateTime StopChargesDateTime;

        // <remarks/>
        [XmlIgnore()]
        public bool StopChargesDateTimeSpecified;

        // <remarks/>
        [XmlAttribute()]
        public bool OneWayIndicator;

        // <remarks/>
        [XmlIgnore()]
        public bool OneWayIndicatorSpecified;

        // <remarks/>
        [XmlAttribute(DataType = "integer")]
        public string MultiIslandRentalDays;

        // <remarks/>
        [XmlAttribute(DataType = "nonNegativeInteger")]
        public string Quantity;

        // <remarks/>
        [XmlAttribute()]
        public DistanceUnitNameType DistUnitName;

        // <remarks/>
        [XmlIgnore()]
        public bool DistUnitNameSpecified;
    }

    // <remarks/>
    [XmlType()]
    public enum DistanceUnitNameType
    {

        // <remarks/>
        Mile,

        // <remarks/>
        Km,

        // <remarks/>
        Block
    }

    // <remarks/>
    [XmlType()]
    public class OTA_VehRateRuleRQRentalInfo
    {

        // <remarks/>
        public VehicleRentalCoreType VehRentalCore;

        // <remarks/>
        public VehiclePrefType VehicleInfo;

        // <remarks/>
        [XmlArrayItem("SpecialEquipPref", IsNullable = false)]
        public OTA_VehRateRuleRQRentalInfoSpecialEquipPref[] SpecialEquipPrefs;

        // <remarks/>
        [XmlElement("CustLoyalty")]
        public OTA_VehRateRuleRQRentalInfoCustLoyalty[] CustLoyalty;

        // <remarks/>
        public OTA_VehRateRuleRQRentalInfoRateQualifier RateQualifier;

        // <remarks/>
        public OffLocationServiceType OffLocService;

        // <remarks/>
        public VehicleArrivalDetailsType ArrivalDetails;

        // <remarks/>
        public VehicleTourInfoType TourInfo;

        // <remarks/>
        public UniqueID_Type CustomerID;

        // <remarks/>
        public TPA_Extensions TPA_Extensions;
    }

    // <remarks/>
    [XmlType()]
    [XmlRoot(IsNullable = false)]
    public class TPA_Extensions
    {

        // <remarks/>
        public Provider Provider;
    }

    // <remarks/>
    [XmlType()]
    [XmlRoot(IsNullable = false)]
    public class Provider
    {

        // <remarks/>
        public Name Name;

        // <remarks/>
        public string System;

        // <remarks/>
        public string Userid;

        // <remarks/>
        public string Password;
    }

    // <remarks/>
    [XmlType()]
    [XmlRoot(IsNullable = false)]
    public class Name
    {

        // <remarks/>
        [XmlAttribute()]
        public string PseudoCityCode;

        // <remarks/>
        [XmlText()]
        public string Value;
    }

    // <remarks/>
    [XmlType()]
    public class SourceTypeBookingChannel
    {

        // <remarks/>
        public CompanyNameType CompanyName;

        // <remarks/>
        [XmlAttribute()]
        public string Type;

        // <remarks/>
        [XmlAttribute()]
        public bool Primary;

        // <remarks/>
        [XmlIgnore()]
        public bool PrimarySpecified;
    }

    // <remarks/>
    [XmlType()]
    public class SourceTypePosition
    {

        // <remarks/>
        [XmlAttribute()]
        public string Latitude;

        // <remarks/>
        [XmlAttribute()]
        public string Longitude;

        // <remarks/>
        [XmlAttribute()]
        public string Altitude;

        // <remarks/>
        [XmlAttribute()]
        public string AltitudeUnitOfMeasureCode;
    }

    // <remarks/>
    [XmlType()]
    public enum OTA_VehRateRuleRQTarget
    {

        // <remarks/>
        Test,

        // <remarks/>
        Production
    }

    // <remarks/>
    [XmlType()]
    public enum OTA_VehRateRuleRQTransactionStatusCode
    {

        // <remarks/>
        Start,

        // <remarks/>
        End,

        // <remarks/>
        Rollback,

        // <remarks/>
        InSeries,

        // <remarks/>
        Continuation,

        // <remarks/>
        Subsequent
    }
}