// ------------------------------------------------------------------------------
// <autogenerated>
// This code was generated by a tool.
// Runtime Version: 1.1.4322.2300
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated.
// </autogenerated>
// ------------------------------------------------------------------------------

using System;
using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=1.1.4322.2300.
// 
namespace wsTripXML.wsTravelTalk.wmETicketVerifyIn
{

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class AirItinerary
    {

        // <remarks/>
        [XmlArrayItem("OriginDestinationOption", IsNullable = false)]
        [XmlArrayItem(IsNullable = false, NestingLevel = 1)]
        public FlightSegment[][] OriginDestinationOptions;

        // <remarks/>
        [XmlAttribute()]
        public AirItineraryDirectionInd DirectionInd;

        // <remarks/>
        [XmlIgnore()]
        public bool DirectionIndSpecified;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class FlightSegment
    {

        // <remarks/>
        public DepartureAirport DepartureAirport;

        // <remarks/>
        public ArrivalAirport ArrivalAirport;

        // <remarks/>
        public OperatingAirline OperatingAirline;

        // <remarks/>
        [XmlElement("Equipment")]
        public Equipment[] Equipment;

        // <remarks/>
        public MarketingAirline MarketingAirline;

        // <remarks/>
        public string MarriageGrp;

        // <remarks/>
        [XmlAttribute()]
        public string DepartureDateTime;

        // <remarks/>
        [XmlAttribute()]
        public string ArrivalDateTime;

        // <remarks/>
        [XmlIgnore()]
        public bool ArrivalDateTimeSpecified;

        // <remarks/>
        [XmlAttribute()]
        public int StopQuantity;

        // <remarks/>
        [XmlIgnore()]
        public bool StopQuantitySpecified;

        // <remarks/>
        [XmlAttribute()]
        public string RPH;

        // <remarks/>
        [XmlAttribute()]
        public string InfoSource;

        // <remarks/>
        [XmlAttribute()]
        public string FlightNumber;

        // <remarks/>
        [XmlAttribute()]
        public string TourOperatorFlightID;

        // <remarks/>
        [XmlAttribute()]
        public string ResBookDesigCode;

        // <remarks/>
        [XmlAttribute()]
        public FlightSegmentActionCode ActionCode;

        // <remarks/>
        [XmlIgnore()]
        public bool ActionCodeSpecified;

        // <remarks/>
        [XmlAttribute()]
        public int NumberInParty;

        // <remarks/>
        [XmlIgnore()]
        public bool NumberInPartySpecified;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class DepartureAirport
    {

        // <remarks/>
        [XmlAttribute()]
        public string LocationCode;

        // <remarks/>
        [XmlAttribute()]
        [System.ComponentModel.DefaultValue("IATA")]
        public string CodeContext = "IATA";

        // <remarks/>
        [XmlText()]
        public string Value;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class MarketingAirline
    {

        // <remarks/>
        [XmlAttribute()]
        public string CompanyShortName;

        // <remarks/>
        [XmlAttribute()]
        public string TravelSector;

        // <remarks/>
        [XmlAttribute()]
        public string Code;

        // <remarks/>
        [XmlAttribute()]
        public string CodeContext;

        // <remarks/>
        [XmlText()]
        public string Value;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class Equipment
    {

        // <remarks/>
        [XmlAttribute()]
        public string AirEquipType;

        // <remarks/>
        [XmlAttribute()]
        [System.ComponentModel.DefaultValue(false)]
        public bool ChangeofGauge = false;

        // <remarks/>
        [XmlText()]
        public string Value;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class OperatingAirline
    {

        // <remarks/>
        [XmlAttribute()]
        public string CompanyShortName;

        // <remarks/>
        [XmlAttribute()]
        public string TravelSector;

        // <remarks/>
        [XmlAttribute()]
        public string Code;

        // <remarks/>
        [XmlAttribute()]
        public string CodeContext;

        // <remarks/>
        [XmlAttribute()]
        public string FlightNumber;

        // <remarks/>
        [XmlText()]
        public string Value;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class ArrivalAirport
    {

        // <remarks/>
        [XmlAttribute()]
        public string LocationCode;

        // <remarks/>
        [XmlAttribute()]
        [System.ComponentModel.DefaultValue("IATA")]
        public string CodeContext = "IATA";

        // <remarks/>
        [XmlText()]
        public string Value;
    }

    // <remarks/>
    public enum FlightSegmentActionCode
    {

        // <remarks/>
        OK,

        // <remarks/>
        Waitlist,

        // <remarks/>
        Other
    }

    // <remarks/>
    public enum AirItineraryDirectionInd
    {

        // <remarks/>
        OneWay,

        // <remarks/>
        Return,

        // <remarks/>
        Circle,

        // <remarks/>
        OpenJaw,

        // <remarks/>
        Other
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class BookingChannel
    {

        // <remarks/>
        public string CompanyName;

        // <remarks/>
        [XmlAttribute()]
        public string Type;

        // <remarks/>
        [XmlAttribute()]
        public bool Primary;

        // <remarks/>
        [XmlIgnore()]
        public bool PrimarySpecified;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class FlightSegmentRPHs
    {

        // <remarks/>
        [XmlElement("FlightSegmentRPH")]
        public string[] FlightSegmentRPH;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class OTA_ETicketVerifyRQ
    {

        // <remarks/>
        public POS POS;

        // <remarks/>
        public AirItinerary AirItinerary;

        // <remarks/>
        [XmlAttribute()]
        public string EchoToken;

        // <remarks/>
        [XmlAttribute()]
        public DateTime TimeStamp;

        // <remarks/>
        [XmlIgnore()]
        public bool TimeStampSpecified;

        // <remarks/>
        [XmlAttribute()]
        [System.ComponentModel.DefaultValue(OTA_ETicketVerifyRQTarget.Production)]
        public OTA_ETicketVerifyRQTarget Target = OTA_ETicketVerifyRQTarget.Production;

        // <remarks/>
        [XmlAttribute()]
        public double Version;

        // <remarks/>
        [XmlIgnore()]
        public bool VersionSpecified;

        // <remarks/>
        [XmlAttribute()]
        public string TransactionIdentifier;

        // <remarks/>
        [XmlAttribute()]
        public int SequenceNmbr;

        // <remarks/>
        [XmlIgnore()]
        public bool SequenceNmbrSpecified;

        // <remarks/>
        [XmlAttribute()]
        public OTA_ETicketVerifyRQTransactionStatusCode TransactionStatusCode;

        // <remarks/>
        [XmlIgnore()]
        public bool TransactionStatusCodeSpecified;

        // <remarks/>
        [XmlAttribute()]
        public string PrimaryLangID;

        // <remarks/>
        [XmlAttribute()]
        public string AltLangID;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class POS : Code.IPOS
    {

        // <remarks/>
        [XmlElement("Source")]
        public Source[] Source;

        // <remarks/>
        public TPA_Extensions TPA_Extensions;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class Source
    {

        // <remarks/>
        public RequestorID RequestorID;

        // <remarks/>
        public object Position;

        // <remarks/>
        public BookingChannel BookingChannel;

        // <remarks/>
        [XmlAttribute()]
        public string AgentSine;

        // <remarks/>
        [XmlAttribute()]
        public string PseudoCityCode;

        // <remarks/>
        [XmlAttribute()]
        public string ISOCountry;

        // <remarks/>
        [XmlAttribute()]
        public string ISOCurrency;

        // <remarks/>
        [XmlAttribute()]
        public string AgentDutyCode;

        // <remarks/>
        [XmlAttribute()]
        public string AirlineVendorID;

        // <remarks/>
        [XmlAttribute()]
        public string AirportCode;

        // <remarks/>
        [XmlAttribute()]
        public string FirstDepartPoint;

        // <remarks/>
        [XmlAttribute()]
        public string ERSP_UserID;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class RequestorID
    {

        // <remarks/>
        public string CompanyName;

        // <remarks/>
        [XmlAttribute(DataType = "anyURI")]
        public string URL;

        // <remarks/>
        [XmlAttribute()]
        public string Type;

        // <remarks/>
        [XmlAttribute()]
        public string Instance;

        // <remarks/>
        [XmlAttribute()]
        public string ID;

        // <remarks/>
        [XmlAttribute()]
        public string ID_Context;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class TPA_Extensions
    {

        // <remarks/>
        public Provider Provider;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class Provider
    {

        // <remarks/>
        public object Name;

        // <remarks/>
        public string System;

        // <remarks/>
        public string Userid;

        // <remarks/>
        public string Password;
    }

    // <remarks/>
    public enum OTA_ETicketVerifyRQTarget
    {

        // <remarks/>
        Test,

        // <remarks/>
        Production
    }

    // <remarks/>
    public enum OTA_ETicketVerifyRQTransactionStatusCode
    {

        // <remarks/>
        Start,

        // <remarks/>
        End,

        // <remarks/>
        Rollback,

        // <remarks/>
        InSeries
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class OriginDestinationOption
    {

        // <remarks/>
        [XmlElement("FlightSegment")]
        public FlightSegment[] FlightSegment;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class OriginDestinationOptions
    {

        // <remarks/>
        [XmlArrayItem(typeof(FlightSegment), IsNullable = false)]
        public FlightSegment[][] OriginDestinationOption;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class UniqueID
    {

        // <remarks/>
        public string CompanyName;

        // <remarks/>
        [XmlAttribute(DataType = "anyURI")]
        public string URL;

        // <remarks/>
        [XmlAttribute()]
        public string Type;

        // <remarks/>
        [XmlAttribute()]
        public string Instance;

        // <remarks/>
        [XmlAttribute()]
        public string ID;

        // <remarks/>
        [XmlAttribute()]
        public string ID_Context;
    }
}