// ------------------------------------------------------------------------------
// <autogenerated>
// This code was generated by a tool.
// Runtime Version: 1.1.4322.573
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated.
// </autogenerated>
// ------------------------------------------------------------------------------


using System.Xml.Serialization;
using wsTripXML.wsTravelTalk.wmDisplayFares;

// 
// This source code was auto-generated by xsd, Version=1.1.4322.573.
// 
namespace wsTripXML.wsTravelTalk.wmFareDisplayIn
{

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class ArrivalDateTime
    {

        // <remarks/>
        [XmlAttribute()]
        public string WindowBefore;

        // <remarks/>
        [XmlAttribute()]
        public string WindowAfter;

        // <remarks/>
        [XmlAttribute()]
        public string CrossDateAllowedIndicator;

        // <remarks/>
        [XmlText()]
        public string Value;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class BookingChannel
    {

        // <remarks/>
        public CompanyName CompanyName;

        // <remarks/>
        [XmlAttribute()]
        public string Type;

        // <remarks/>
        [XmlAttribute()]
        public string Primary;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class CompanyName
    {

        // <remarks/>
        [XmlAttribute()]
        public string CompanyShortName;

        // <remarks/>
        [XmlAttribute()]
        public string TravelSector;

        // <remarks/>
        [XmlAttribute()]
        public string Code;

        // <remarks/>
        [XmlAttribute()]
        public string CodeContext;

        // <remarks/>
        [XmlText()]
        public string Value;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class BookingClassPref
    {

        // <remarks/>
        [XmlAttribute()]
        public string ResBookDesigCode;

        // <remarks/>
        [XmlAttribute(DataType = "NMTOKEN")]
        public string PreferLevel;

        // <remarks/>
        [XmlAttribute(DataType = "NMTOKEN")]
        public string ResBookDesigCodeType;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class CabinPref
    {

        // <remarks/>
        [XmlAttribute(DataType = "NMTOKEN")]
        public string PreferLevel;

        // <remarks/>
        [XmlAttribute(DataType = "NMTOKEN")]
        public string Cabin;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class ConnectionLocation
    {

        // <remarks/>
        [XmlAttribute()]
        public string LocationCode;

        // <remarks/>
        [XmlAttribute()]
        public string CodeContext;

        // <remarks/>
        [XmlAttribute()]
        public string Inclusive;

        // <remarks/>
        [XmlAttribute(DataType = "NMTOKEN")]
        public string PreferLevel;

        // <remarks/>
        [XmlAttribute()]
        public string MinChangeTime;

        // <remarks/>
        [XmlAttribute()]
        public ConnectionLocationConnectionInfo ConnectionInfo;

        // <remarks/>
        [XmlIgnore()]
        public bool ConnectionInfoSpecified;

        // <remarks/>
        [XmlText()]
        public string Value;
    }

    // <remarks/>
    public enum ConnectionLocationConnectionInfo
    {

        // <remarks/>
        Via,

        // <remarks/>
        Stop,

        // <remarks/>
        Change
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class ConnectionLocations
    {

        // <remarks/>
        [XmlElement("ConnectionLocation")]
        public ConnectionLocation[] ConnectionLocation;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class DepartureDateTime
    {

        // <remarks/>
        [XmlAttribute()]
        public string WindowBefore;

        // <remarks/>
        [XmlAttribute()]
        public string WindowAfter;

        // <remarks/>
        [XmlAttribute()]
        public string CrossDateAllowedIndicator;

        // <remarks/>
        [XmlText()]
        public string Value;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class DestinationLocation
    {

        // <remarks/>
        [XmlAttribute()]
        public string LocationCode;

        // <remarks/>
        [XmlAttribute()]
        public string CodeContext;

        // <remarks/>
        [XmlAttribute()]
        public string MultiAirportCityInd;

        // <remarks/>
        [XmlText()]
        public string Value;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class EquipPref
    {

        // <remarks/>
        [XmlAttribute()]
        public string AirEquipType;

        // <remarks/>
        [XmlAttribute()]
        public string ChangeofGauge;

        // <remarks/>
        [XmlAttribute(DataType = "NMTOKEN")]
        public string PreferLevel;

        // <remarks/>
        [XmlAttribute()]
        public string WideBody;

        // <remarks/>
        [XmlText()]
        public string Value;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class FareAccessTypePref
    {

        // <remarks/>
        [XmlArrayItem(IsNullable = false)]
        public NegotiatedFareCode[] NegotiatedFareCodes;

        // <remarks/>
        [XmlAttribute()]
        public FareAccessTypePrefFareAccess FareAccess;

        // <remarks/>
        [XmlIgnore()]
        public bool FareAccessSpecified;

        // <remarks/>
        [XmlAttribute(DataType = "NMTOKEN")]
        public string PreferLevel;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class NegotiatedFareCode
    {

        // <remarks/>
        [XmlAttribute()]
        public string Code;

        // <remarks/>
        [XmlAttribute()]
        public string CodeContext;

        // <remarks/>
        [XmlText()]
        public string Value;
    }

    // <remarks/>
    public enum FareAccessTypePrefFareAccess
    {

        // <remarks/>
        PointToPoint,

        // <remarks/>
        Through,

        // <remarks/>
        Joint,

        // <remarks/>
        Private,

        // <remarks/>
        Negotiated,

        // <remarks/>
        Net
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class FareApplicationTypePref
    {

        // <remarks/>
        [XmlAttribute()]
        public FareApplicationTypePrefFareApplicationType FareApplicationType;

        // <remarks/>
        [XmlAttribute(DataType = "NMTOKEN")]
        public string PreferLevel;
    }

    // <remarks/>
    public enum FareApplicationTypePrefFareApplicationType
    {

        // <remarks/>
        OneWay,

        // <remarks/>
        Return,

        // <remarks/>
        HalfReturn
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class FareRestrictPref
    {

        // <remarks/>
        public AdvResTicketing AdvResTicketing;

        // <remarks/>
        public StayRestrictions StayRestrictions;

        // <remarks/>
        public VoluntaryChanges VoluntaryChanges;

        // <remarks/>
        [XmlAttribute(DataType = "NMTOKEN")]
        public string PreferLevel;

        // <remarks/>
        [XmlAttribute()]
        public string FareRestriction;

        // <remarks/>
        [XmlAttribute()]
        public string FareDisplayCurrency;

        // <remarks/>
        [XmlAttribute()]
        public string CurrencyOverride;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class StayRestrictions
    {

        // <remarks/>
        public MinimumStay MinimumStay;

        // <remarks/>
        public MaximumStay MaximumStay;

        // <remarks/>
        [XmlAttribute()]
        public string StayRestrictionsInd;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class FareTypePref
    {

        // <remarks/>
        [XmlAttribute()]
        public string FareType;

        // <remarks/>
        [XmlAttribute(DataType = "NMTOKEN")]
        public string PreferLevel;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class FlightTypePref
    {

        // <remarks/>
        [XmlAttribute(DataType = "NMTOKEN")]
        public string PreferLevel;

        // <remarks/>
        [XmlAttribute(DataType = "NMTOKEN")]
        public string FlightType;

        // <remarks/>
        [XmlAttribute()]
        public string MaxConnections;

        // <remarks/>
        [XmlAttribute(DataType = "NMTOKEN")]
        public string NonScheduledFltInfo;

        // <remarks/>
        [XmlAttribute()]
        public string BackhaulIndicator;

        // <remarks/>
        [XmlAttribute()]
        public string GroundTransportIndicator;

        // <remarks/>
        [XmlAttribute()]
        public string DirectAndNonStopOnlyInd;

        // <remarks/>
        [XmlAttribute()]
        public string NonStopsOnlyInd;

        // <remarks/>
        [XmlAttribute()]
        public string OnlineConnectionsOnlyInd;

        // <remarks/>
        [XmlAttribute(DataType = "NMTOKEN")]
        public string RoutingType;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class GlobalIndicatorPref
    {

        // <remarks/>
        [XmlAttribute(DataType = "NMTOKEN")]
        public string GlobalIndicatorCode;

        // <remarks/>
        [XmlAttribute()]
        public string CodeContext;

        // <remarks/>
        [XmlAttribute(DataType = "NMTOKEN")]
        public string PreferLevel;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class NegotiatedFareCodes
    {

        // <remarks/>
        [XmlElement("NegotiatedFareCode")]
        public NegotiatedFareCode[] NegotiatedFareCode;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class OTA_AirFareDisplayRQ
    {

        // <remarks/>
        public POS POS;

        // <remarks/>
        public TPA_Extensions TPA_Extensions;

        // <remarks/>
        [XmlElement("OriginDestinationInformation")]
        public OriginDestinationInformation[] OriginDestinationInformation;

        // <remarks/>
        public SpecificFlightInfo SpecificFlightInfo;

        // <remarks/>
        public TravelPreferences TravelPreferences;

        // <remarks/>
        [XmlArrayItem(IsNullable = false)]
        public PassengerTypeQuantity[] TravelerInfoSummary;

        // <remarks/>
        [XmlAttribute()]
        public string EchoToken;

        // <remarks/>
        [XmlAttribute()]
        public string TimeStamp;

        // <remarks/>
        [XmlAttribute(DataType = "NMTOKEN")]
        public string Target;

        // <remarks/>
        [XmlAttribute()]
        public string Version;

        // <remarks/>
        [XmlAttribute()]
        public string TransactionIdentifier;

        // <remarks/>
        [XmlAttribute()]
        public string SequenceNmbr;

        // <remarks/>
        [XmlAttribute(DataType = "NMTOKEN")]
        public string TransactionStatusCode;

        // <remarks/>
        [XmlAttribute()]
        public string PrimaryLangID;

        // <remarks/>
        [XmlAttribute()]
        public string AltLangID;

        // <remarks/>
        [XmlAttribute()]
        public string MaxResponses;

        // <remarks/>
        [XmlAttribute()]
        public string DirectFlightsOnly;

        // <remarks/>
        [XmlAttribute()]
        public string AvailableFlightsOnly;

        // <remarks/>
        [XmlAttribute(DataType = "NMTOKEN")]
        public string DisplayOrder;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class POS : Code.IPOS
    {

        // <remarks/>
        [XmlElement("Source")]
        public Source[] Source;

        // <remarks/>
        public TPA_Extensions TPA_Extensions;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class Source
    {

        // <remarks/>
        public RequestorID RequestorID;

        // <remarks/>
        public Position Position;

        // <remarks/>
        public BookingChannel BookingChannel;

        // <remarks/>
        [XmlAttribute()]
        public string AgentSine;

        // <remarks/>
        [XmlAttribute()]
        public string PseudoCityCode;

        // <remarks/>
        [XmlAttribute()]
        public string ISOCountry;

        // <remarks/>
        [XmlAttribute()]
        public string ISOCurrency;

        // <remarks/>
        [XmlAttribute()]
        public string AgentDutyCode;

        // <remarks/>
        [XmlAttribute()]
        public string AirlineVendorID;

        // <remarks/>
        [XmlAttribute()]
        public string AirportCode;

        // <remarks/>
        [XmlAttribute()]
        public string FirstDepartPoint;

        // <remarks/>
        [XmlAttribute()]
        public string ERSP_UserID;

        // <remarks/>
        [XmlAttribute()]
        public string TerminalID;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class RequestorID
    {

        // <remarks/>
        public CompanyName CompanyName;

        // <remarks/>
        [XmlAttribute()]
        public string URL;

        // <remarks/>
        [XmlAttribute()]
        public string Type;

        // <remarks/>
        [XmlAttribute()]
        public string Instance;

        // <remarks/>
        [XmlAttribute()]
        public string ID;

        // <remarks/>
        [XmlAttribute()]
        public string ID_Context;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class Position
    {

        // <remarks/>
        [XmlAttribute()]
        public string Latitude;

        // <remarks/>
        [XmlAttribute()]
        public string Longitude;

        // <remarks/>
        [XmlAttribute()]
        public string Altitude;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class TPA_Extensions
    {

        // <remarks/>
        public Provider Provider;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class Provider
    {

        // <remarks/>
        public string Name;

        // <remarks/>
        public string System;

        // <remarks/>
        public string Userid;

        // <remarks/>
        public string Password;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class OriginDestinationInformation
    {

        // <remarks/>
        [XmlElement("DepartureDateTime", typeof(DepartureDateTime))]
        [XmlElement("ArrivalDateTime", typeof(ArrivalDateTime))]
        public object Item;

        // <remarks/>
        public OriginLocation OriginLocation;

        // <remarks/>
        public DestinationLocation DestinationLocation;

        // <remarks/>
        [XmlArrayItem(IsNullable = false)]
        public ConnectionLocation[] ConnectionLocations;

        // <remarks/>
        [XmlAttribute()]
        public string RPH;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class OriginLocation
    {

        // <remarks/>
        [XmlAttribute()]
        public string LocationCode;

        // <remarks/>
        [XmlAttribute()]
        public string CodeContext;

        // <remarks/>
        [XmlAttribute()]
        public string MultiAirportCityInd;

        // <remarks/>
        [XmlText()]
        public string Value;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class SpecificFlightInfo
    {

        // <remarks/>
        public string FlightNumber;

        // <remarks/>
        public Airline Airline;

        // <remarks/>
        public BookingClassPref BookingClassPref;

        // <remarks/>
        [XmlAttribute()]
        public string BookingReferenceID;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class TravelPreferences
    {

        // <remarks/>
        [XmlElement("VendorPref")]
        public VendorPref[] VendorPref;

        // <remarks/>
        [XmlElement("FlightTypePref")]
        public FlightTypePref[] FlightTypePref;

        // <remarks/>
        [XmlElement("FareRestrictPref")]
        public FareRestrictPref[] FareRestrictPref;

        // <remarks/>
        [XmlElement("EquipPref")]
        public EquipPref[] EquipPref;

        // <remarks/>
        [XmlElement("CabinPref")]
        public CabinPref[] CabinPref;

        // <remarks/>
        [XmlElement("TicketDistribPref")]
        public TicketDistribPref[] TicketDistribPref;

        // <remarks/>
        public FareApplicationTypePref FareApplicationTypePref;

        // <remarks/>
        [XmlElement("FareTypePref")]
        public FareTypePref[] FareTypePref;

        // <remarks/>
        [XmlElement("FareAccessTypePref")]
        public FareAccessTypePref[] FareAccessTypePref;

        // <remarks/>
        [XmlElement("BookingClassPref")]
        public BookingClassPref[] BookingClassPref;

        // <remarks/>
        public PricingPrefs PricingPrefs;

        // <remarks/>
        [XmlElement("GlobalIndicatorPref")]
        public GlobalIndicatorPref[] GlobalIndicatorPref;

        // <remarks/>
        [XmlAttribute()]
        public string SmokingAllowed;

        // <remarks/>
        [XmlAttribute()]
        public string OnTimeRate;

        // <remarks/>
        [XmlAttribute()]
        public string ETicketDesired;

        // <remarks/>
        [XmlAttribute()]
        public string MaxStopsQuantity;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class VendorPref
    {

        // <remarks/>
        [XmlAttribute()]
        public string CompanyShortName;

        // <remarks/>
        [XmlAttribute()]
        public string TravelSector;

        // <remarks/>
        [XmlAttribute()]
        public string Code;

        // <remarks/>
        [XmlAttribute()]
        public string CodeContext;

        // <remarks/>
        [XmlAttribute(DataType = "NMTOKEN")]
        public string PreferLevel;

        // <remarks/>
        [XmlText()]
        public string Value;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class TicketDistribPref
    {

        // <remarks/>
        [XmlAttribute(DataType = "NMTOKEN")]
        public string PreferLevel;

        // <remarks/>
        [XmlAttribute()]
        public string DistribType;

        // <remarks/>
        [XmlAttribute()]
        public string TicketTime;

        // <remarks/>
        [XmlAttribute()]
        public string LastTicketDate;

        // <remarks/>
        [XmlAttribute()]
        public string FirstTicketDate;

        // <remarks/>
        [XmlText()]
        public string Value;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class PricingPrefs
    {

        // <remarks/>
        [XmlArrayItem(IsNullable = false)]
        public ExchangeRate[] ExchangeRates;

        // <remarks/>
        [XmlAttribute()]
        public string IncludeTaxInd;

        // <remarks/>
        [XmlAttribute()]
        public string IncludeServiceFeesInd;

        // <remarks/>
        [XmlAttribute()]
        public string OverrideCurrency;

        // <remarks/>
        [XmlAttribute()]
        public string AlternateCurrency;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class PassengerTypeQuantity
    {

        // <remarks/>
        public ReductionPref ReductionPref;

        // <remarks/>
        [XmlAttribute()]
        public string Age;

        // <remarks/>
        [XmlAttribute()]
        public string Code;

        // <remarks/>
        [XmlAttribute()]
        public string CodeContext;

        // <remarks/>
        [XmlAttribute()]
        public string URI;

        // <remarks/>
        [XmlAttribute()]
        public string Quantity;

        // <remarks/>
        [XmlAttribute()]
        public string Changeable;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class ReductionPref
    {

        // <remarks/>
        [XmlAttribute()]
        public string Amount;

        // <remarks/>
        [XmlAttribute()]
        public string Currency;

        // <remarks/>
        [XmlAttribute()]
        public string Percent;

        // <remarks/>
        [XmlAttribute(DataType = "NMTOKEN")]
        public string PreferLevel;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class TravelerInfoSummary
    {

        // <remarks/>
        [XmlElement("PassengerTypeQuantity")]
        public PassengerTypeQuantity[] PassengerTypeQuantity;
    }
}