// ------------------------------------------------------------------------------
// <autogenerated>
// This code was generated by a tool.
// Runtime Version: 1.1.4322.573
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated.
// </autogenerated>
// ------------------------------------------------------------------------------

using System;
using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=1.1.4322.573.
// 
namespace wsTripXML.wsTravelTalk.wmLowFareFlightsOut
{

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class AdvResTicketingRS
    {

        // <remarks/>
        public AdvReservationRS AdvReservation;

        // <remarks/>
        public AdvTicketingRS AdvTicketing;

        // <remarks/>
        [XmlAttribute()]
        public bool AdvResInd;

        // <remarks/>
        [XmlIgnore()]
        public bool AdvResIndSpecified;

        // <remarks/>
        [XmlAttribute()]
        public bool AdvTicketingInd;

        // <remarks/>
        [XmlIgnore()]
        public bool AdvTicketingIndSpecified;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class AdvReservationRS
    {

        // <remarks/>
        [XmlAttribute()]
        public DateTime LatestTimeOfDay;

        // <remarks/>
        [XmlIgnore()]
        public bool LatestTimeOfDaySpecified;

        // <remarks/>
        [XmlAttribute()]
        public string LatestPeriod;

        // <remarks/>
        [XmlAttribute()]
        public AdvReservationLatestUnit LatestUnit;

        // <remarks/>
        [XmlIgnore()]
        public bool LatestUnitSpecified;
    }

    // <remarks/>
    public enum AdvReservationLatestUnit
    {

        // <remarks/>
        Minutes,

        // <remarks/>
        Hours,

        // <remarks/>
        Days,

        // <remarks/>
        Months,

        // <remarks/>
        MON,

        // <remarks/>
        TUES,

        // <remarks/>
        WED,

        // <remarks/>
        THU,

        // <remarks/>
        FRI,

        // <remarks/>
        SAT,

        // <remarks/>
        SUN
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class AdvTicketingRS
    {

        // <remarks/>
        [XmlAttribute()]
        public DateTime FromResTimeOfDay;

        // <remarks/>
        [XmlIgnore()]
        public bool FromResTimeOfDaySpecified;

        // <remarks/>
        [XmlAttribute()]
        public string FromResPeriod;

        // <remarks/>
        [XmlAttribute()]
        public AdvTicketingFromResUnit FromResUnit;

        // <remarks/>
        [XmlIgnore()]
        public bool FromResUnitSpecified;

        // <remarks/>
        [XmlAttribute()]
        public DateTime FromDepartTimeOfDay;

        // <remarks/>
        [XmlIgnore()]
        public bool FromDepartTimeOfDaySpecified;

        // <remarks/>
        [XmlAttribute()]
        public string FromDepartPeriod;

        // <remarks/>
        [XmlAttribute()]
        public AdvTicketingFromDepartUnit FromDepartUnit;

        // <remarks/>
        [XmlIgnore()]
        public bool FromDepartUnitSpecified;

        // <remarks/>
        [XmlText()]
        public string Value;
    }

    // <remarks/>
    public enum AdvTicketingFromResUnit
    {

        // <remarks/>
        Minutes,

        // <remarks/>
        Hours,

        // <remarks/>
        Days,

        // <remarks/>
        Months,

        // <remarks/>
        MON,

        // <remarks/>
        TUES,

        // <remarks/>
        WED,

        // <remarks/>
        THU,

        // <remarks/>
        FRI,

        // <remarks/>
        SAT,

        // <remarks/>
        SUN
    }

    // <remarks/>
    public enum AdvTicketingFromDepartUnit
    {

        // <remarks/>
        Minutes,

        // <remarks/>
        Hours,

        // <remarks/>
        Days,

        // <remarks/>
        Months,

        // <remarks/>
        MON,

        // <remarks/>
        TUES,

        // <remarks/>
        WED,

        // <remarks/>
        THU,

        // <remarks/>
        FRI,

        // <remarks/>
        SAT,

        // <remarks/>
        SUN
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class AirItinerary
    {

        // '<remarks/>
        // <System.Xml.Serialization.XmlArrayItemAttribute("OriginDestinationOption", IsNullable:=False), _
        // System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=False, NestingLevel:=1)> _
        // Public OriginDestinationOptions()() As FlightSegment

        // <remarks/>
        [XmlArrayItem(IsNullable = false)]
        public OriginDestinationOption[] OriginDestinationOptions;

        // <remarks/>
        [XmlAttribute()]
        public AirItineraryDirectionInd DirectionInd;

        // <remarks/>
        [XmlIgnore()]
        public bool DirectionIndSpecified;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class FlightSegment
    {

        // <remarks/>
        public DepartureAirport DepartureAirport;

        // <remarks/>
        public ArrivalAirport ArrivalAirport;

        // <remarks/>
        public OperatingAirline OperatingAirline;

        // <remarks/>
        [XmlElement("Equipment")]
        public Equipment[] Equipment;

        // <remarks/>
        public MarketingAirline MarketingAirline;

        // <remarks/>
        public string MarriageGrp;

        // <remarks/>
        public TPA_ExtensionsRS TPA_Extensions;

        // <remarks/>
        [XmlAttribute()]
        public string DepartureDateTime;

        // <remarks/>
        [XmlAttribute()]
        public string ArrivalDateTime;

        // <remarks/>
        [XmlIgnore()]
        public bool ArrivalDateTimeSpecified;

        // <remarks/>
        [XmlAttribute()]
        public int StopQuantity;

        // <remarks/>
        [XmlIgnore()]
        public bool StopQuantitySpecified;

        // <remarks/>
        [XmlAttribute()]
        public string RPH;

        // <remarks/>
        [XmlAttribute()]
        public string InfoSource;

        // <remarks/>
        [XmlAttribute()]
        public string FlightNumber;

        // <remarks/>
        [XmlAttribute()]
        public string ResBookDesigCode;

        // <remarks/>
        [XmlAttribute()]
        public FlightSegmentActionCode ActionCode;

        // <remarks/>
        [XmlIgnore()]
        public bool ActionCodeSpecified;

        // <remarks/>
        [XmlAttribute()]
        public int NumberInParty;

        // <remarks/>
        [XmlIgnore()]
        public bool NumberInPartySpecified;

        // <remarks/>
        [XmlAttribute()]
        public E_TicketEligibilityType E_TicketEligibility;

        // <remarks/>
        [XmlIgnore()]
        public bool E_TicketEligibilitySpecified;
    }

    // <remarks/>
    public enum E_TicketEligibilityType
    {

        // <remarks/>
        Eligible,

        // <remarks/>
        NotEligible,

        // <remarks/>
        Required
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class DepartureAirport
    {

        // <remarks/>
        [XmlAttribute()]
        public string LocationCode;

        // <remarks/>
        [XmlAttribute()]
        [System.ComponentModel.DefaultValue("IATA")]
        public string CodeContext = "IATA";

        // <remarks/>
        [XmlText()]
        public string Value;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class ArrivalAirport
    {

        // <remarks/>
        [XmlAttribute()]
        public string LocationCode;

        // <remarks/>
        [XmlAttribute()]
        [System.ComponentModel.DefaultValue("IATA")]
        public string CodeContext = "IATA";

        // <remarks/>
        [XmlText()]
        public string Value;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class OperatingAirline
    {

        // <remarks/>
        [XmlAttribute()]
        public string CompanyShortName;

        // <remarks/>
        [XmlAttribute()]
        public string TravelSector;

        // <remarks/>
        [XmlAttribute()]
        public string Code;

        // <remarks/>
        [XmlAttribute()]
        public string CodeContext;

        // <remarks/>
        [XmlAttribute()]
        public string FlightNumber;

        // <remarks/>
        [XmlText()]
        public string Value;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class Equipment
    {

        // <remarks/>
        [XmlAttribute()]
        public string AirEquipType;

        // <remarks/>
        [XmlAttribute()]
        [System.ComponentModel.DefaultValue(false)]
        public bool ChangeofGauge = false;

        // <remarks/>
        [XmlText()]
        public string Value;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class MarketingAirline
    {

        // <remarks/>
        [XmlAttribute()]
        public string CompanyShortName;

        // <remarks/>
        [XmlAttribute()]
        public string TravelSector;

        // <remarks/>
        [XmlAttribute()]
        public string Code;

        // <remarks/>
        [XmlAttribute()]
        public string CodeContext;

        // <remarks/>
        [XmlText()]
        public string Value;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class TPA_ExtensionsRS
    {

        // <remarks/>
        public CabinType CabinType;

        // <remarks/>
        public string JourneyTotalDuration;

        // <remarks/>
        public string JourneyDuration;

        // <remarks/>
        public string PricedCode;

        // <remarks/>
        public string Text;

        // <remarks/>
        public string FlightContext;

        // <remarks/>
        public BaseFare BaseFare;

        // <remarks/>
        public Taxes Taxes;

        // <remarks/>
        public TotalFare TotalBaseFare;

        // <remarks/>
        public TotalFare TotalTax;

        // <remarks/>
        public TotalFare TotalFare;

        // <remarks/>
        public TotalFare FromTotalBaseFare;

        // <remarks/>
        public TotalFare FromTotalTax;

        // <remarks/>
        public TotalFare FromTotalFare;




        // <remarks/>
        public Fees Fees;

        // <remarks/>
        [XmlElement("OriginClass")]
        public OriginClass[] OriginClass;

        // <remarks/>
        [XmlElement("FareBasisCodes")]
        public FareBasisCodes[] FareBasisCodes;

        // <remarks/>
        [XmlAttribute()]
        public AirItineraryPricingInfoPricingSource PricingSource;

        // <remarks/>
        [XmlIgnore()]
        public bool PricingSourceSpecified;

        // <remarks/>
        [XmlAttribute()]
        public string ValidatingAirlineCode;

        // <remarks/>
        [XmlAttribute()]
        public string NegotiatedFareCode;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class OriginClass
    {

        // <remarks/>
        [XmlAttribute()]
        public string Index;

        // <remarks/>
        [XmlText()]
        public string Value;

        // <remarks/>
        [XmlAttribute()]
        public CabinTypeCabin Cabin;

    }

    // <remarks/>
    public enum FlightSegmentActionCode
    {

        // <remarks/>
        OK,

        // <remarks/>
        Waitlist,

        // <remarks/>
        Other
    }

    // <remarks/>
    public enum AirItineraryDirectionInd
    {

        // <remarks/>
        OneWay,

        // <remarks/>
        Return,

        // <remarks/>
        Circle,

        // <remarks/>
        OpenJaw,

        // <remarks/>
        Other
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class AirItineraryPricingInfo
    {

        // <remarks/>
        public ItinTotalFare ItinTotalFare;

        // <remarks/>
        [XmlArrayItem(IsNullable = false)]
        public PTC_FareBreakdown[] PTC_FareBreakdowns;

        // <remarks/>
        [XmlArrayItem(IsNullable = false)]
        public FareInfo[] FareInfos;

        // <remarks/>
        [XmlAttribute()]
        public AirItineraryPricingInfoPricingSource PricingSource;

        // <remarks/>
        [XmlIgnore()]
        public bool PricingSourceSpecified;

        // <remarks/>
        [XmlAttribute()]
        public string ValidatingAirlineCode;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class ItinTotalFare
    {

        // <remarks/>
        public BaseFare BaseFare;

        // <remarks/>
        public EquivFare EquivFare;

        // <remarks/>
        [XmlArrayItem(IsNullable = false)]
        public Tax[] Taxes;

        // <remarks/>
        [XmlArrayItem(IsNullable = false)]
        public Fee[] Fees;

        // <remarks/>
        public TotalFare TotalFare;

        // <remarks/>
        [XmlAttribute()]
        [System.ComponentModel.DefaultValue(false)]
        public bool NegotiatedFare = false;

        // <remarks/>
        [XmlAttribute()]
        public string NegotiatedFareCode;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class BaseFare
    {

        // <remarks/>
        [XmlAttribute()]
        public double Amount;

        // <remarks/>
        [XmlIgnore()]
        public bool AmountSpecified;

        // <remarks/>
        [XmlAttribute()]
        public string CurrencyCode;

        // <remarks/>
        [XmlAttribute()]
        public int DecimalPlaces;

        // <remarks/>
        [XmlIgnore()]
        public bool DecimalPlacesSpecified;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class EquivFare
    {

        // <remarks/>
        [XmlAttribute()]
        public double Amount;

        // <remarks/>
        [XmlIgnore()]
        public bool AmountSpecified;

        // <remarks/>
        [XmlAttribute()]
        public string CurrencyCode;

        // <remarks/>
        [XmlAttribute()]
        public int DecimalPlaces;

        // <remarks/>
        [XmlIgnore()]
        public bool DecimalPlacesSpecified;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class Tax
    {

        // <remarks/>
        [XmlAttribute()]
        public string TaxCode;

        // <remarks/>
        [XmlAttribute()]
        public double Amount;

        // <remarks/>
        [XmlIgnore()]
        public bool AmountSpecified;

        // <remarks/>
        [XmlAttribute()]
        public string CurrencyCode;

        // <remarks/>
        [XmlAttribute()]
        public int DecimalPlaces;

        // <remarks/>
        [XmlIgnore()]
        public bool DecimalPlacesSpecified;

        // <remarks/>
        [XmlText()]
        public string Value;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class Fee
    {

        // <remarks/>
        [XmlAttribute()]
        public string FeeCode;

        // <remarks/>
        [XmlAttribute()]
        public string FeeType;

        // <remarks/>
        [XmlAttribute()]
        public double Amount;

        // <remarks/>
        [XmlIgnore()]
        public bool AmountSpecified;

        // <remarks/>
        [XmlAttribute()]
        public string CurrencyCode;

        // <remarks/>
        [XmlAttribute()]
        public int DecimalPlaces;

        // <remarks/>
        [XmlIgnore()]
        public bool DecimalPlacesSpecified;

        // <remarks/>
        [XmlText()]
        public string Value;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class TotalFare
    {

        // <remarks/>
        [XmlAttribute()]
        public double Amount;

        // <remarks/>
        [XmlIgnore()]
        public bool AmountSpecified;

        // <remarks/>
        [XmlAttribute()]
        public string CurrencyCode;

        // <remarks/>
        [XmlAttribute()]
        public int DecimalPlaces;

        // <remarks/>
        [XmlIgnore()]
        public bool DecimalPlacesSpecified;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class PTC_FareBreakdown
    {

        // <remarks/>
        public PassengerTypeQuantityRS PassengerTypeQuantity;

        // <remarks/>
        [XmlArrayItem("FareBasisCode", IsNullable = false)]
        public string[] FareBasisCodes;

        // <remarks/>
        public PassengerFare PassengerFare;

        // <remarks/>
        public TPA_ExtensionsRS TPA_Extensions;

        // <remarks/>
        [XmlAttribute()]
        public PTC_FareBreakdownPricingSource PricingSource;

        // <remarks/>
        [XmlIgnore()]
        public bool PricingSourceSpecified;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class PassengerTypeQuantityRS
    {

        // <remarks/>
        [XmlAttribute()]
        public int Age;

        // <remarks/>
        [XmlIgnore()]
        public bool AgeSpecified;

        // <remarks/>
        [XmlAttribute()]
        public string Code;

        // <remarks/>
        [XmlAttribute()]
        public string CodeContext;

        // <remarks/>
        [XmlAttribute(DataType = "anyURI")]
        public string URI;

        // <remarks/>
        [XmlAttribute()]
        public int Quantity;

        // <remarks/>
        [XmlIgnore()]
        public bool QuantitySpecified;

        // <remarks/>
        [XmlAttribute()]
        [System.ComponentModel.DefaultValue(true)]
        public bool Changeable = true;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class PassengerFare
    {

        // <remarks/>
        public BaseFare BaseFare;

        // <remarks/>
        public EquivFare EquivFare;

        // <remarks/>
        [XmlArrayItem(IsNullable = false)]
        public Tax[] Taxes;

        // <remarks/>
        [XmlArrayItem(IsNullable = false)]
        public Fee[] Fees;

        // <remarks/>
        public TotalFare TotalFare;

        // <remarks/>
        [XmlAttribute()]
        [System.ComponentModel.DefaultValue(false)]
        public bool NegotiatedFare = false;

        // <remarks/>
        [XmlAttribute()]
        public string NegotiatedFareCode;
    }

    // <remarks/>
    public enum PTC_FareBreakdownPricingSource
    {

        // <remarks/>
        Published,

        // <remarks/>
        Private,

        // <remarks/>
        Both
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class FareInfo
    {

        // <remarks/>
        public string DepartureDate;

        // <remarks/>
        [XmlIgnore()]
        public bool DepartureDateSpecified;

        // <remarks/>
        public string FareReference;

        // <remarks/>
        public RuleInfo RuleInfo;

        // <remarks/>
        public FilingAirline FilingAirline;

        // <remarks/>
        [XmlElement("MarketingAirline")]
        public MarketingAirline[] MarketingAirline;

        // <remarks/>
        public DepartureAirport DepartureAirport;

        // <remarks/>
        public ArrivalAirport ArrivalAirport;

        // <remarks/>
        [XmlAttribute()]
        [System.ComponentModel.DefaultValue(false)]
        public bool NegotiatedFare = false;

        // <remarks/>
        [XmlAttribute()]
        public string NegotiatedFareCode;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class RuleInfo
    {

        // <remarks/>
        public ResTicketingRules ResTicketingRules;

        // <remarks/>
        public LengthOfStayRules LengthOfStayRules;

        // <remarks/>
        public ChargesRules ChargesRules;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class ResTicketingRules
    {

        // <remarks/>
        public AdvResTicketingRS AdvResTicketing;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class LengthOfStayRules
    {

        // <remarks/>
        public MinimumStayRS MinimumStay;

        // <remarks/>
        public MaximumStayRS MaximumStay;

        // <remarks/>
        [XmlAttribute()]
        public bool StayRestrictionsInd;

        // <remarks/>
        [XmlIgnore()]
        public bool StayRestrictionsIndSpecified;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class MinimumStayRS
    {

        // <remarks/>
        [XmlAttribute()]
        public DateTime ReturnTimeOfDay;

        // <remarks/>
        [XmlIgnore()]
        public bool ReturnTimeOfDaySpecified;

        // <remarks/>
        [XmlAttribute()]
        public string MinStay;

        // <remarks/>
        [XmlAttribute()]
        public MinimumStayStayUnit StayUnit;

        // <remarks/>
        [XmlIgnore()]
        public bool StayUnitSpecified;

        // <remarks/>
        [XmlAttribute()]
        public DateTime MinStayDate;

        // <remarks/>
        [XmlIgnore()]
        public bool MinStayDateSpecified;
    }

    // <remarks/>
    public enum MinimumStayStayUnit
    {

        // <remarks/>
        Minutes,

        // <remarks/>
        Hours,

        // <remarks/>
        Days,

        // <remarks/>
        Months,

        // <remarks/>
        MON,

        // <remarks/>
        TUES,

        // <remarks/>
        WED,

        // <remarks/>
        THU,

        // <remarks/>
        FRI,

        // <remarks/>
        SAT,

        // <remarks/>
        SUN
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class MaximumStayRS
    {

        // <remarks/>
        [XmlAttribute()]
        public string ReturnType;

        // <remarks/>
        [XmlAttribute()]
        public DateTime ReturnTimeOfDay;

        // <remarks/>
        [XmlIgnore()]
        public bool ReturnTimeOfDaySpecified;

        // <remarks/>
        [XmlAttribute()]
        public string MaxStay;

        // <remarks/>
        [XmlAttribute()]
        public MaximumStayStayUnit StayUnit;

        // <remarks/>
        [XmlIgnore()]
        public bool StayUnitSpecified;

        // <remarks/>
        [XmlAttribute()]
        public DateTime MaxStayDate;

        // <remarks/>
        [XmlIgnore()]
        public bool MaxStayDateSpecified;
    }

    // <remarks/>
    public enum MaximumStayStayUnit
    {

        // <remarks/>
        Minutes,

        // <remarks/>
        Hours,

        // <remarks/>
        Days,

        // <remarks/>
        Months,

        // <remarks/>
        MON,

        // <remarks/>
        TUES,

        // <remarks/>
        WED,

        // <remarks/>
        THU,

        // <remarks/>
        FRI,

        // <remarks/>
        SAT,

        // <remarks/>
        SUN
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class CabinType
    {

        // <remarks/>
        [XmlAttribute()]
        public CabinTypeCabin Cabin;
    }

    // <remarks/>
    public enum CabinTypeCabin
    {

        // <remarks/>
        First,

        // <remarks/>
        Business,

        // <remarks/>
        Economy
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class ChargesRules
    {

        // <remarks/>
        public VoluntaryChangesRS VoluntaryChanges;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class VoluntaryChangesRS
    {

        // <remarks/>
        public PenaltyRS Penalty;

        // <remarks/>
        [XmlAttribute()]
        public bool VolChangeInd;

        // <remarks/>
        [XmlIgnore()]
        public bool VolChangeIndSpecified;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class PenaltyRS
    {

        // <remarks/>
        [XmlAttribute()]
        public string PenaltyType;

        // <remarks/>
        [XmlAttribute()]
        public string DepartureStatus;

        // <remarks/>
        [XmlAttribute()]
        public double Amount;

        // <remarks/>
        [XmlIgnore()]
        public bool AmountSpecified;

        // <remarks/>
        [XmlAttribute()]
        public string CurrencyCode;

        // <remarks/>
        [XmlAttribute()]
        public int DecimalPlaces;

        // <remarks/>
        [XmlIgnore()]
        public bool DecimalPlacesSpecified;

        // <remarks/>
        [XmlAttribute()]
        public double Percent;

        // <remarks/>
        [XmlIgnore()]
        public bool PercentSpecified;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class FilingAirline
    {

        // <remarks/>
        [XmlAttribute()]
        public string CompanyShortName;

        // <remarks/>
        [XmlAttribute()]
        public string TravelSector;

        // <remarks/>
        [XmlAttribute()]
        public string Code;

        // <remarks/>
        [XmlAttribute()]
        public string CodeContext;

        // <remarks/>
        [XmlText()]
        public string Value;
    }

    // <remarks/>
    public enum AirItineraryPricingInfoPricingSource
    {

        // <remarks/>
        Published,

        // <remarks/>
        Private,

        // <remarks/>
        Both
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class Error
    {

        // <remarks/>
        [XmlAttribute()]
        public string Language;

        // <remarks/>
        [XmlAttribute()]
        public string Type;

        // <remarks/>
        [XmlAttribute()]
        public string ShortText;

        // <remarks/>
        [XmlAttribute()]
        public string Code;

        // <remarks/>
        [XmlAttribute(DataType = "anyURI")]
        public string DocURL;

        // <remarks/>
        [XmlAttribute()]
        public string Status;

        // <remarks/>
        [XmlAttribute()]
        public string Tag;

        // <remarks/>
        [XmlAttribute()]
        public string RecordID;

        // <remarks/>
        [XmlAttribute()]
        public string NodeList;

        // <remarks/>
        [XmlText()]
        public string Value;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class Errors
    {

        // <remarks/>
        [XmlElement("Error")]
        public Error[] Error;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class FareBasisCodes
    {

        // <remarks/>
        [XmlElement("FareBasisCode")]
        public string[] FareBasisCode;

        // <remarks/>
        [XmlAttribute()]
        public string PassengerType;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class FareInfos
    {

        // <remarks/>
        [XmlElement("FareInfo")]
        public FareInfo[] FareInfo;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class Fees
    {

        // <remarks/>
        [XmlElement("Fee")]
        public Fee[] Fee;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class Notes
    {

        // <remarks/>
        [XmlAttribute()]
        public string Language;

        // <remarks/>
        [XmlText()]
        public string Value;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class OTA_AirLowFareSearchFlightsRS
    {

        // <remarks/>
        public Success Success;

        // <remarks/>
        [XmlArrayItem(IsNullable = false)]
        public Warning[] Warnings;

        // <remarks/>
        [XmlArrayItem(IsNullable = false)]
        public PricedItinerary[] PricedItineraries;

        // <remarks/>
        [XmlArrayItem(IsNullable = false)]
        public Error[] Errors;

        // <remarks/>
        [XmlAttribute()]
        public string EchoToken;

        // <remarks/>
        [XmlAttribute()]
        public DateTime TimeStamp;

        // <remarks/>
        [XmlIgnore()]
        public bool TimeStampSpecified;

        // <remarks/>
        [XmlAttribute()]
        [System.ComponentModel.DefaultValue(OTA_AirLowFareSearchPlusRSTarget.Production)]
        public OTA_AirLowFareSearchPlusRSTarget Target = OTA_AirLowFareSearchPlusRSTarget.Production;

        // <remarks/>
        [XmlAttribute()]
        public double Version;

        // <remarks/>
        [XmlAttribute()]
        public string TransactionIdentifier;

        // <remarks/>
        [XmlAttribute()]
        public int SequenceNmbr;

        // <remarks/>
        [XmlIgnore()]
        public bool SequenceNmbrSpecified;

        // <remarks/>
        [XmlAttribute()]
        public OTA_AirLowFareSearchPlusRSTransactionStatusCode TransactionStatusCode;

        // <remarks/>
        [XmlIgnore()]
        public bool TransactionStatusCodeSpecified;

        // <remarks/>
        [XmlAttribute()]
        public string PrimaryLangID;

        // <remarks/>
        [XmlAttribute()]
        public string AltLangID;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class Success
    {
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class Warning
    {

        // <remarks/>
        [XmlAttribute()]
        public string Language;

        // <remarks/>
        [XmlAttribute()]
        public string Type;

        // <remarks/>
        [XmlAttribute()]
        public string ShortText;

        // <remarks/>
        [XmlAttribute()]
        public string Code;

        // <remarks/>
        [XmlAttribute(DataType = "anyURI")]
        public string DocURL;

        // <remarks/>
        [XmlAttribute()]
        public string Status;

        // <remarks/>
        [XmlAttribute()]
        public string Tag;

        // <remarks/>
        [XmlAttribute()]
        public string RecordID;

        // <remarks/>
        [XmlText()]
        public string Value;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class PricedItinerary
    {

        // <remarks/>
        public AirItinerary AirItinerary;

        // <remarks/>
        public AirItineraryPricingInfo AirItineraryPricingInfo;

        // <remarks/>
        [XmlElement("Notes")]
        public Notes[] Notes;

        // <remarks/>
        public TicketingInfo TicketingInfo;

        // <remarks/>
        [XmlAttribute()]
        public int SequenceNumber;

        // <remarks/>
        [XmlAttribute()]
        public string Provider;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class TicketingInfo
    {

        // <remarks/>
        [XmlElement("TicketAdvisory")]
        public TicketAdvisory[] TicketAdvisory;

        // <remarks/>
        [XmlAttribute()]
        public string TicketTimeLimit;

        // <remarks/>
        [XmlIgnore()]
        public bool TicketTimeLimitSpecified;

        // <remarks/>
        [XmlAttribute()]
        public TicketingInfoTicketType TicketType;

        // <remarks/>
        [XmlIgnore()]
        public bool TicketTypeSpecified;

        // <remarks/>
        [XmlAttribute()]
        public string eTicketNumber;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class TicketAdvisory
    {

        // <remarks/>
        [XmlAttribute()]
        public string Language;

        // <remarks/>
        [XmlText()]
        public string Value;
    }

    // <remarks/>
    public enum TicketingInfoTicketType
    {

        // <remarks/>
        eTicket,

        // <remarks/>
        Paper
    }

    // <remarks/>
    public enum OTA_AirLowFareSearchPlusRSTarget
    {

        // <remarks/>
        Test,

        // <remarks/>
        Production
    }

    // <remarks/>
    public enum OTA_AirLowFareSearchPlusRSTransactionStatusCode
    {

        // <remarks/>
        Start,

        // <remarks/>
        End,

        // <remarks/>
        Rollback,

        // <remarks/>
        InSeries
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class OriginDestinationOption
    {

        // <remarks/>
        [XmlElement("FlightSegment")]
        public FlightSegment[] FlightSegment;

        // <remarks/>
        [XmlAttribute()]
        public string SectorSequence;
    }

    // <remarks/>
    // <System.Xml.Serialization.XmlRootAttribute(IsNullable:=False)> _
    // Public Class OriginDestinationOptions

    // '<remarks/>
    // <System.Xml.Serialization.XmlArrayItemAttribute(GetType(FlightSegment), IsNullable:=False)> _
    // Public OriginDestinationOption()() As FlightSegment
    // End Class

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class PTC_FareBreakdowns
    {

        // <remarks/>
        [XmlElement("PTC_FareBreakdown")]
        public PTC_FareBreakdown[] PTC_FareBreakdown;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class PricedItineraries
    {

        // <remarks/>
        [XmlElement("PricedItinerary")]
        public PricedItinerary[] PricedItinerary;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class Taxes
    {

        // <remarks/>
        [XmlElement("Tax")]
        public Tax[] Tax;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class Warnings
    {

        // <remarks/>
        [XmlElement("Warning")]
        public Warning[] Warning;
    }
}