// ------------------------------------------------------------------------------
// <autogenerated>
// This code was generated by a tool.
// Runtime Version: 1.1.4322.573
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated.
// </autogenerated>
// ------------------------------------------------------------------------------

using System;
using System.Xml.Serialization;
using wsTripXML.wsTravelTalk.wmTravelItinerary;

// 
// This source code was auto-generated by xsd, Version=1.1.4322.573.
// 
namespace wsTripXML.wsTravelTalk.wmTravelModifyIn
{

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class AcceptedPayment
    {

        // <remarks/>
        public PaymentCard PaymentCard;

        // <remarks/>
        public BankAcct BankAcct;

        // <remarks/>
        public DirectBill DirectBill;

        // <remarks/>
        public Voucher Voucher;

        // <remarks/>
        [XmlAttribute()]
        public AcceptedPaymentShareSynchInd ShareSynchInd;

        // <remarks/>
        [XmlIgnore()]
        public bool ShareSynchIndSpecified;

        // <remarks/>
        [XmlAttribute()]
        public AcceptedPaymentShareMarketInd ShareMarketInd;

        // <remarks/>
        [XmlIgnore()]
        public bool ShareMarketIndSpecified;

        // <remarks/>
        [XmlAttribute()]
        public string CostCenterId;

        // <remarks/>
        [XmlAttribute()]
        public string RPH;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class PaymentCard
    {

        // <remarks/>
        public string CardHolderName;

        // <remarks/>
        public CardIssuerName CardIssuerName;

        // <remarks/>
        public Address Address;

        // <remarks/>
        [XmlAttribute()]
        public PaymentCardShareSynchInd ShareSynchInd;

        // <remarks/>
        [XmlIgnore()]
        public bool ShareSynchIndSpecified;

        // <remarks/>
        [XmlAttribute()]
        public PaymentCardShareMarketInd ShareMarketInd;

        // <remarks/>
        [XmlIgnore()]
        public bool ShareMarketIndSpecified;

        // <remarks/>
        [XmlAttribute()]
        public string CardType;

        // <remarks/>
        [XmlAttribute()]
        public PaymentCardCardCode CardCode;

        // <remarks/>
        [XmlIgnore()]
        public bool CardCodeSpecified;

        // <remarks/>
        [XmlAttribute()]
        public string CardNumber;

        // <remarks/>
        [XmlAttribute()]
        public string SeriesCode;

        // <remarks/>
        [XmlAttribute()]
        public string EffectiveDate;

        // <remarks/>
        [XmlAttribute()]
        public string ExpireDate;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class CardIssuerName
    {

        // <remarks/>
        [XmlAttribute()]
        public string BankID;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class Voucher
    {

        // <remarks/>
        [XmlAttribute(DataType = "date")]
        public DateTime EffectiveDate;

        // <remarks/>
        [XmlIgnore()]
        public bool EffectiveDateSpecified;

        // <remarks/>
        [XmlAttribute(DataType = "date")]
        public DateTime ExpireDate;

        // <remarks/>
        [XmlIgnore()]
        public bool ExpireDateSpecified;

        // <remarks/>
        [XmlAttribute()]
        public string SeriesCode;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class DirectBill
    {

        // <remarks/>
        public Address Address;

        // <remarks/>
        [XmlAttribute()]
        public DirectBillShareSynchInd ShareSynchInd;

        // <remarks/>
        [XmlIgnore()]
        public bool ShareSynchIndSpecified;

        // <remarks/>
        [XmlAttribute()]
        public DirectBillShareMarketInd ShareMarketInd;

        // <remarks/>
        [XmlIgnore()]
        public bool ShareMarketIndSpecified;

        // <remarks/>
        [XmlAttribute()]
        public string DirectBill_ID;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class Address
    {

        // <remarks/>
        public StreetNmbr StreetNmbr;

        // <remarks/>
        public string BldgRoom;

        // <remarks/>
        [XmlElement("AddressLine")]
        public string[] AddressLine;

        // <remarks/>
        public string CityName;

        // <remarks/>
        public string PostalCode;

        // <remarks/>
        public string County;

        // <remarks/>
        public StateProv StateProv;

        // <remarks/>
        public CountryName CountryName;

        // <remarks/>
        [XmlAttribute()]
        [System.ComponentModel.DefaultValue(false)]
        public bool FormattedInd = false;

        // <remarks/>
        [XmlAttribute()]
        public AddressShareSynchInd ShareSynchInd;

        // <remarks/>
        [XmlIgnore()]
        public bool ShareSynchIndSpecified;

        // <remarks/>
        [XmlAttribute()]
        public AddressShareMarketInd ShareMarketInd;

        // <remarks/>
        [XmlIgnore()]
        public bool ShareMarketIndSpecified;

        // <remarks/>
        [XmlAttribute()]
        public string Type;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class AcceptedPayments
    {

        // <remarks/>
        [XmlElement("AcceptedPayment")]
        public AcceptedPayment[] AcceptedPayment;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class Additional
    {

        // <remarks/>
        public PersonName PersonName;

        // <remarks/>
        [XmlElement("Telephone")]
        public Telephone[] Telephone;

        // <remarks/>
        [XmlElement("Email")]
        public Email[] Email;

        // <remarks/>
        [XmlElement("Address")]
        public Address[] Address;

        // <remarks/>
        [XmlElement("CitizenCountryName")]
        public CitizenCountryName[] CitizenCountryName;

        // <remarks/>
        [XmlElement("Document")]
        public Document[] Document;

        // <remarks/>
        [XmlElement("CustLoyalty")]
        public CustLoyalty[] CustLoyalty;

        // <remarks/>
        public TPA_Extensions TPA_Extensions;

        // <remarks/>
        [XmlAttribute()]
        public string BirthDate;

        // <remarks/>
        [XmlAttribute()]
        public string CurrencyCode;

        // <remarks/>
        [XmlAttribute()]
        public int DecimalPlaces;

        // <remarks/>
        [XmlIgnore()]
        public bool DecimalPlacesSpecified;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class Telephone
    {

        // <remarks/>
        [XmlAttribute()]
        public TelephoneShareSynchInd ShareSynchInd;

        // <remarks/>
        [XmlIgnore()]
        public bool ShareSynchIndSpecified;

        // <remarks/>
        [XmlAttribute()]
        public TelephoneShareMarketInd ShareMarketInd;

        // <remarks/>
        [XmlIgnore()]
        public bool ShareMarketIndSpecified;

        // <remarks/>
        [XmlAttribute()]
        public string PhoneLocationType;

        // <remarks/>
        [XmlAttribute()]
        public string PhoneTechType;

        // <remarks/>
        [XmlAttribute()]
        public string CountryAccessCode;

        // <remarks/>
        [XmlAttribute()]
        public string AreaCityCode;

        // <remarks/>
        [XmlAttribute()]
        public string PhoneNumber;

        // <remarks/>
        [XmlAttribute()]
        public string Extension;

        // <remarks/>
        [XmlAttribute()]
        public string PIN;

        // <remarks/>
        [XmlAttribute()]
        [System.ComponentModel.DefaultValue(false)]
        public bool FormattedInd = false;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class CitizenCountryName
    {

        // <remarks/>
        [XmlAttribute()]
        [System.ComponentModel.DefaultValue(false)]
        public bool DefaultInd = false;

        // <remarks/>
        [XmlAttribute()]
        public string Code;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class Document
    {

        // <remarks/>
        public string DocHolderName;

        // <remarks/>
        public string DocLimitations;

        // <remarks/>
        [XmlAttribute()]
        public DocumentShareSynchInd ShareSynchInd;

        // <remarks/>
        [XmlIgnore()]
        public bool ShareSynchIndSpecified;

        // <remarks/>
        [XmlAttribute()]
        public DocumentShareMarketInd ShareMarketInd;

        // <remarks/>
        [XmlIgnore()]
        public bool ShareMarketIndSpecified;

        // <remarks/>
        [XmlAttribute()]
        public string DocIssueAuthority;

        // <remarks/>
        [XmlAttribute()]
        public string DocIssueLocation;

        // <remarks/>
        [XmlAttribute()]
        public string DocID;

        // <remarks/>
        [XmlAttribute()]
        public string DocType;

        // <remarks/>
        [XmlAttribute()]
        public DocumentGender Gender;

        // <remarks/>
        [XmlIgnore()]
        public bool GenderSpecified;

        // <remarks/>
        [XmlAttribute(DataType = "date")]
        public DateTime BirthDate;

        // <remarks/>
        [XmlIgnore()]
        public bool BirthDateSpecified;

        // <remarks/>
        [XmlAttribute(DataType = "date")]
        public DateTime EffectiveDate;

        // <remarks/>
        [XmlIgnore()]
        public bool EffectiveDateSpecified;

        // <remarks/>
        [XmlAttribute(DataType = "date")]
        public DateTime ExpireDate;

        // <remarks/>
        [XmlIgnore()]
        public bool ExpireDateSpecified;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class CustLoyalty
    {

        // <remarks/>
        [XmlAttribute()]
        public CustLoyaltyShareSynchInd ShareSynchInd;

        // <remarks/>
        [XmlIgnore()]
        public bool ShareSynchIndSpecified;

        // <remarks/>
        [XmlAttribute()]
        public CustLoyaltyShareMarketInd ShareMarketInd;

        // <remarks/>
        [XmlIgnore()]
        public bool ShareMarketIndSpecified;

        // <remarks/>
        [XmlAttribute()]
        public string ProgramID;

        // <remarks/>
        [XmlAttribute()]
        public string MembershipID;

        // <remarks/>
        [XmlAttribute()]
        public string TravelSector;

        // <remarks/>
        [XmlAttribute()]
        public string LoyalLevel;

        // <remarks/>
        [XmlAttribute()]
        public CustLoyaltySingleVendorInd SingleVendorInd;

        // <remarks/>
        [XmlIgnore()]
        public bool SingleVendorIndSpecified;

        // <remarks/>
        [XmlAttribute(DataType = "date")]
        public DateTime SignupDate;

        // <remarks/>
        [XmlIgnore()]
        public bool SignupDateSpecified;

        // <remarks/>
        [XmlAttribute(DataType = "date")]
        public DateTime EffectiveDate;

        // <remarks/>
        [XmlIgnore()]
        public bool EffectiveDateSpecified;

        // <remarks/>
        [XmlAttribute(DataType = "date")]
        public DateTime ExpireDate;

        // <remarks/>
        [XmlIgnore()]
        public bool ExpireDateSpecified;

        // <remarks/>
        [XmlAttribute()]
        public string RPH;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class TPA_Extensions
    {

        // <remarks/>
        public Provider Provider;

        // <remarks/>
        public PNRData PNRData;

        // <remarks/>
        public CarData CarData;

        // <remarks/>
        public HotelData HotelData;

        // <remarks/>
        public PriceData PriceData;

        // <remarks/>
        public AgencyData AgencyData;

        // <remarks/>
        [XmlAttribute()]
        public string FlightType;

        // <remarks/>
        [XmlAttribute()]
        public string DateChange;

        // <remarks/>
        [XmlAttribute()]
        public bool FlownIndicator;

        // <remarks/>
        [XmlIgnore()]
        public bool FlownIndicatorSpecified;

        // <remarks/>
        [XmlAttribute()]
        public string FOPType;

    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class Provider
    {

        // <remarks/>
        public string Name;

        // <remarks/>
        public string System;

        // <remarks/>
        public string Userid;

        // <remarks/>
        public string Password;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class PNRData
    {

        // <remarks/>
        [XmlElement("Traveler")]
        public Traveler[] Traveler;

        // <remarks/>
        [XmlElement("Telephone")]
        public Telephone[] Telephone;

        // <remarks/>
        [XmlElement("Email")]
        public Email[] Email;

        // <remarks/>
        public Address Address;

        // <remarks/>
        public Ticketing Ticketing;

        // <remarks/>
        [XmlElement("AccountingLine")]
        public string[] AccountingLine;

        // <remarks/>
        public Queue Queue;

    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class Traveler
    {

        // <remarks/>
        public PersonName PersonName;

        // <remarks/>
        [XmlElement("CustLoyalty")]
        public CustLoyalty[] CustLoyalty;

        // <remarks/>
        [XmlElement("Document")]
        public Document[] Document;

        // <remarks/>
        public TravelerRefNumber TravelerRefNumber;

        // <remarks/>
        [XmlArrayItem("FlightSegmentRPH", IsNullable = false)]
        public string[] FlightSegmentRPHs;

        // <remarks/>
        public string Age;

        // <remarks/>
        [XmlAttribute()]
        public TravelerGender Gender;

        // <remarks/>
        [XmlIgnore()]
        public bool GenderSpecified;

        // <remarks/>
        [XmlAttribute(DataType = "date")]
        public DateTime BirthDate;

        // <remarks/>
        [XmlIgnore()]
        public bool BirthDateSpecified;

        // <remarks/>
        [XmlAttribute()]
        public string PassengerTypeCode;

        // <remarks/>
        [XmlAttribute()]
        public bool AccompaniedByInfant;

        // <remarks/>
        [XmlIgnore()]
        public bool AccompaniedByInfantSpecified;
    }

    // <remarks/>
    public enum TravelerGender
    {

        // <remarks/>
        Male,

        // <remarks/>
        Female,

        // <remarks/>
        Unknown
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class Ticketing
    {

        // <remarks/>
        [XmlElement("TicketAdvisory")]
        public TicketAdvisory[] TicketAdvisory;

        // <remarks/>
        [XmlAttribute()]
        public DateTime TicketTimeLimit;

        // <remarks/>
        [XmlIgnore()]
        public bool TicketTimeLimitSpecified;

        // <remarks/>
        [XmlAttribute()]
        public TicketingTicketType TicketType;
    }

    // <remarks/>
    public enum TicketingTicketType
    {

        // <remarks/>
        eTicket,

        // <remarks/>
        Paper,

        // <remarks/>
        None
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class CarData
    {

        // <remarks/>
        public CarLocation CarLocation;

        // <remarks/>
        public CarRate CarRate;

        // <remarks/>
        [XmlAttribute()]
        public string NumCars;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class CarLocation
    {

        // <remarks/>
        [XmlAttribute()]
        public string Category;

        // <remarks/>
        [XmlAttribute()]
        public string Number;

        // <remarks/>
        [XmlText()]
        public string Value;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class CarRate
    {

        // <remarks/>
        [XmlAttribute()]
        public string Rate;

        // <remarks/>
        [XmlAttribute()]
        public string Currency;

        // <remarks/>
        [XmlText()]
        public string Value;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class HotelData
    {

        // <remarks/>
        public string ExtraAdult;

        // <remarks/>
        public string ExtraChild;

        // <remarks/>
        public string Crib;

        // <remarks/>
        public string RollawayAdult;

        // <remarks/>
        public string RollawayChild;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class PriceData
    {

        // <remarks/>
        public PublishedFares PublishedFares;

        // <remarks/>
        public NegoFares NegoFares;

        // <remarks/>
        [XmlElement("FareDiscount")]
        public FareDiscount[] FareDiscount;

        // <remarks/>
        [XmlAttribute()]
        public PriceDataPriceType PriceType;

        // <remarks/>
        [XmlIgnore()]
        public bool PriceTypeSpecified;


        // <remarks/>
        [XmlAttribute()]
        public string FlightRefNumberRPHList;

        // <remarks/>
        [XmlAttribute()]
        public string TravelerRefNumberRPHList;

        // <remarks/>
        [XmlAttribute()]
        public bool AutoTicketing;

    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class FareDiscount
    {

        // <remarks/>
        public BaseFare BaseFare;

        [XmlArrayItem(IsNullable = false)]
        public Tax[] Taxes;

        // <remarks/>
        public TotalFare TotalFare;

        // <remarks/>
        [XmlAttribute()]
        public string TravelerRefNumberRPHList;

        // <remarks/>
        [XmlAttribute()]
        public string DiscountCode;

    }

    // <remarks/>
    public class AgencyData
    {

        // <remarks/>
        public AgencyDataCommission Commission;

        // <remarks/>
        public AgencyDataServiceFee ServiceFee;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class PublishedFares
    {

        // <remarks/>
        public FareRestrictPref FareRestrictPref;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class FareRestrictPref
    {

        // <remarks/>
        public AdvResTicketing AdvResTicketing;

        // <remarks/>
        public MinimumStay MinimumStay;

        // <remarks/>
        public MaximumStay MaximumStay;

        // <remarks/>
        public VoluntaryChanges VoluntaryChanges;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class AdvResTicketing
    {

        // <remarks/>
        public AdvReservation AdvReservation;

        // <remarks/>
        public AdvTicketing AdvTicketing;

        // <remarks/>
        [XmlAttribute()]
        public bool AdvResInd;

        // <remarks/>
        [XmlIgnore()]
        public bool AdvResIndSpecified;

        // <remarks/>
        [XmlAttribute()]
        public bool AdvTicketingInd;

        // <remarks/>
        [XmlIgnore()]
        public bool AdvTicketingIndSpecified;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class AdvTicketing
    {

        // <remarks/>
        [XmlAttribute()]
        public DateTime FromResTimeOfDay;

        // <remarks/>
        [XmlIgnore()]
        public bool FromResTimeOfDaySpecified;

        // <remarks/>
        [XmlAttribute()]
        public string FromResPeriod;

        // <remarks/>
        [XmlAttribute()]
        public AdvTicketingFromResUnit FromResUnit;

        // <remarks/>
        [XmlIgnore()]
        public bool FromResUnitSpecified;

        // <remarks/>
        [XmlAttribute()]
        public DateTime FromDepartTimeOfDay;

        // <remarks/>
        [XmlIgnore()]
        public bool FromDepartTimeOfDaySpecified;

        // <remarks/>
        [XmlAttribute()]
        public string FromDepartPeriod;

        // <remarks/>
        [XmlAttribute()]
        public AdvTicketingFromDepartUnit FromDepartUnit;

        // <remarks/>
        [XmlIgnore()]
        public bool FromDepartUnitSpecified;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class MinimumStay
    {

        // <remarks/>
        [XmlAttribute()]
        public string ReturnTimeOfDay;

        // <remarks/>
        [XmlAttribute()]
        public string MinStay;

        // <remarks/>
        [XmlAttribute()]
        public string StayUnit;

        // <remarks/>
        [XmlAttribute()]
        public string MinStayDate;

        // <remarks/>
        [XmlText()]
        public string Value;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class MaximumStay
    {

        // <remarks/>
        [XmlAttribute()]
        public string ReturnType;

        // <remarks/>
        [XmlAttribute()]
        public string ReturnTimeOfDay;

        // <remarks/>
        [XmlAttribute()]
        public string MaxStay;

        // <remarks/>
        [XmlAttribute()]
        public string StayUnit;

        // <remarks/>
        [XmlAttribute()]
        public string MaxStayDate;

        // <remarks/>
        [XmlText()]
        public string Value;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class VoluntaryChanges
    {

        // <remarks/>
        public Penalty Penalty;

        // <remarks/>
        [XmlAttribute()]
        public bool VolChangeInd;

        // <remarks/>
        [XmlIgnore()]
        public bool VolChangeIndSpecified;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class Penalty
    {

        // <remarks/>
        [XmlAttribute()]
        public string PenaltyType;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class NegoFares
    {

        // <remarks/>
        public PriceRequestInformation PriceRequestInformation;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class PriceRequestInformation
    {

        // <remarks/>
        [XmlElement("NegotiatedFareCode")]
        public NegotiatedFareCode[] NegotiatedFareCode;

        // <remarks/>
        [XmlAttribute()]
        public PriceRequestInformationPricingSource PricingSource;

        // <remarks/>
        [XmlIgnore()]
        public bool PricingSourceSpecified;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class NegotiatedFareCode
    {

        // <remarks/>
        [XmlAttribute()]
        public string Code;

        // <remarks/>
        [XmlAttribute()]
        public int Quantity;

        // <remarks/>
        [XmlIgnore()]
        public bool QuantitySpecified;

        // <remarks/>
        [XmlAttribute()]
        public string SecondaryCode;

        // <remarks/>
        [XmlAttribute()]
        public string SupplierCode;

        // <remarks/>
        [XmlText()]
        public string Value;
    }

    // <remarks/>
    public enum PriceRequestInformationPricingSource
    {

        // <remarks/>
        Published,

        // <remarks/>
        Private
    }

    // <remarks/>
    public enum PriceDataPriceType
    {

        // <remarks/>
        Published,

        // <remarks/>
        Private
    }

    // <remarks/>
    public class AgencyDataCommission
    {

        // <remarks/>
        [XmlAttribute()]
        public decimal Percent;

        // <remarks/>
        [XmlIgnore()]
        public bool PercentSpecified;
    }

    // <remarks/>
    public class AgencyDataServiceFee
    {

        // <remarks/>
        [XmlAttribute()]
        public decimal Amount;

        // <remarks/>
        [XmlIgnore()]
        public bool AmountSpecified;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class AdditionalDetail
    {

        // <remarks/>
        public DetailDescription DetailDescription;

        // <remarks/>
        [XmlAttribute()]
        public string Type;

        // <remarks/>
        [XmlAttribute()]
        public string Code;

        // <remarks/>
        [XmlAttribute()]
        public double Amount;

        // <remarks/>
        [XmlIgnore()]
        public bool AmountSpecified;

        // <remarks/>
        [XmlAttribute()]
        public string CurrencyCode;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class DetailDescription
    {

        // <remarks/>
        public string Text;

        // <remarks/>
        public string Image;

        // <remarks/>
        [XmlElement(DataType = "anyURI")]
        public string URL;

        // <remarks/>
        [XmlAttribute()]
        public int ParagraphNumber;

        // <remarks/>
        [XmlIgnore()]
        public bool ParagraphNumberSpecified;

        // <remarks/>
        [XmlAttribute()]
        public DateTime CreateDateTime;

        // <remarks/>
        [XmlIgnore()]
        public bool CreateDateTimeSpecified;

        // <remarks/>
        [XmlAttribute()]
        public string CreatorID;

        // <remarks/>
        [XmlAttribute()]
        public DateTime LastModifyDateTime;

        // <remarks/>
        [XmlIgnore()]
        public bool LastModifyDateTimeSpecified;

        // <remarks/>
        [XmlAttribute()]
        public string LastModifierID;

        // <remarks/>
        [XmlAttribute()]
        public string Language;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class AdditionalDetails
    {

        // <remarks/>
        [XmlElement("AdditionalDetail")]
        public AdditionalDetail[] AdditionalDetail;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class AirItinerary
    {

        // <remarks/>
        [XmlArrayItem("OriginDestinationOption", IsNullable = false)]
        [XmlArrayItem(IsNullable = false, NestingLevel = 1)]
        public FlightSegment[][] OriginDestinationOptions;

        // <remarks/>
        [XmlAttribute()]
        public AirItineraryDirectionInd DirectionInd;

        // <remarks/>
        [XmlIgnore()]
        public bool DirectionIndSpecified;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class FlightSegment
    {

        // <remarks/>
        public DepartureAirport DepartureAirport;

        // <remarks/>
        public ArrivalAirport ArrivalAirport;

        // <remarks/>
        public OperatingAirline OperatingAirline;

        // <remarks/>
        [XmlElement("Equipment")]
        public Equipment[] Equipment;

        // <remarks/>
        public MarketingAirline MarketingAirline;

        // <remarks/>
        public string MarriageGrp;

        // <remarks/>
        [XmlAttribute()]
        public string DepartureDateTime;

        // <remarks/>
        [XmlAttribute()]
        public string ArrivalDateTime;

        // <remarks/>
        [XmlIgnore()]
        public bool ArrivalDateTimeSpecified;

        // <remarks/>
        [XmlAttribute()]
        public int StopQuantity;

        // <remarks/>
        [XmlIgnore()]
        public bool StopQuantitySpecified;

        // <remarks/>
        [XmlAttribute()]
        public string RPH;

        // <remarks/>
        [XmlAttribute()]
        public string InfoSource;

        // <remarks/>
        [XmlAttribute()]
        public string FlightNumber;

        // <remarks/>
        [XmlAttribute()]
        public string TourOperatorFlightID;

        // <remarks/>
        [XmlAttribute()]
        public string ResBookDesigCode;

        // <remarks/>
        [XmlAttribute()]
        public FlightSegmentActionCode ActionCode;

        // <remarks/>
        [XmlIgnore()]
        public bool ActionCodeSpecified;

        // <remarks/>
        [XmlAttribute()]
        public int NumberInParty;

        // <remarks/>
        [XmlIgnore()]
        public bool NumberInPartySpecified;
    }

    // <remarks/>
    public enum FlightSegmentActionCode
    {

        // <remarks/>
        OK,

        // <remarks/>
        Waitlist,

        // <remarks/>
        Other
    }

    // <remarks/>
    public enum AirItineraryDirectionInd
    {

        // <remarks/>
        OneWay,

        // <remarks/>
        Return,

        // <remarks/>
        Circle,

        // <remarks/>
        OpenJaw,

        // <remarks/>
        Other
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class AirTraveler
    {

        // <remarks/>
        public ProfileRef ProfileRef;

        // <remarks/>
        public PersonName PersonName;

        // <remarks/>
        [XmlElement("Telephone")]
        public Telephone[] Telephone;

        // <remarks/>
        [XmlElement("Email")]
        public Email[] Email;

        // <remarks/>
        [XmlElement("Address")]
        public Address[] Address;

        // <remarks/>
        [XmlElement("CustLoyalty")]
        public CustLoyalty[] CustLoyalty;

        // <remarks/>
        [XmlElement("Document")]
        public Document[] Document;

        // <remarks/>
        public PassengerTypeQuantity PassengerTypeQuantity;

        // <remarks/>
        public TravelerRefNumber TravelerRefNumber;

        // <remarks/>
        [XmlArrayItem("FlightSegmentRPH", IsNullable = false)]
        public string[] FlightSegmentRPHs;

        // <remarks/>
        public TPA_Extensions TPA_Extensions;

        // <remarks/>
        [XmlAttribute()]
        public AirTravelerGender Gender;

        // <remarks/>
        [XmlIgnore()]
        public bool GenderSpecified;

        // <remarks/>
        [XmlAttribute()]
        public AirTravelerShareSynchInd ShareSynchInd;

        // <remarks/>
        [XmlIgnore()]
        public bool ShareSynchIndSpecified;

        // <remarks/>
        [XmlAttribute()]
        public AirTravelerShareMarketInd ShareMarketInd;

        // <remarks/>
        [XmlIgnore()]
        public bool ShareMarketIndSpecified;

        // <remarks/>
        [XmlAttribute(DataType = "date")]
        public DateTime BirthDate;

        // <remarks/>
        [XmlIgnore()]
        public bool BirthDateSpecified;

        // <remarks/>
        [XmlAttribute()]
        public string CurrencyCode;

        // <remarks/>
        [XmlAttribute()]
        public string PassengerTypeCode;

        // <remarks/>
        [XmlAttribute()]
        public bool AccompaniedByInfant;

        // <remarks/>
        [XmlIgnore()]
        public bool AccompaniedByInfantSpecified;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class ProfileRef
    {

        // <remarks/>
        public UniqueID UniqueID;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class PassengerTypeQuantity
    {

        // <remarks/>
        [XmlAttribute()]
        public int Age;

        // <remarks/>
        [XmlIgnore()]
        public bool AgeSpecified;

        // <remarks/>
        [XmlAttribute()]
        public string Code;

        // <remarks/>
        [XmlAttribute()]
        public string CodeContext;

        // <remarks/>
        [XmlAttribute(DataType = "anyURI")]
        public string URI;

        // <remarks/>
        [XmlAttribute()]
        public int Quantity;

        // <remarks/>
        [XmlIgnore()]
        public bool QuantitySpecified;

        // <remarks/>
        [XmlAttribute()]
        [System.ComponentModel.DefaultValue(true)]
        public bool Changeable = true;
    }

    // <remarks/>
    public enum AirTravelerGender
    {

        // <remarks/>
        Male,

        // <remarks/>
        Female,

        // <remarks/>
        Unknown
    }

    // <remarks/>
    public enum AirTravelerShareSynchInd
    {

        // <remarks/>
        Yes,

        // <remarks/>
        No,

        // <remarks/>
        Inherit
    }

    // <remarks/>
    public enum AirTravelerShareMarketInd
    {

        // <remarks/>
        Yes,

        // <remarks/>
        No,

        // <remarks/>
        Inherit
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class ArrivalDetails
    {

        // <remarks/>
        public ArrivalLocation ArrivalLocation;

        // <remarks/>
        public MarketingCompany MarketingCompany;

        // <remarks/>
        public OperatingCompany OperatingCompany;

        // <remarks/>
        [XmlAttribute()]
        public string TransportationCode;

        // <remarks/>
        [XmlAttribute()]
        public string Number;

        // <remarks/>
        [XmlAttribute()]
        public DateTime ArrivalDateTime;

        // <remarks/>
        [XmlIgnore()]
        public bool ArrivalDateTimeSpecified;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class ArrivalLocation
    {

        // <remarks/>
        [XmlAttribute()]
        public string LocationCode;

        // <remarks/>
        [XmlAttribute()]
        [System.ComponentModel.DefaultValue("IATA")]
        public string CodeContext = "IATA";

        // <remarks/>
        [XmlText()]
        public string Value;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class MarketingCompany
    {

        // <remarks/>
        [XmlAttribute()]
        public string CompanyShortName;

        // <remarks/>
        [XmlAttribute()]
        public string TravelSector;

        // <remarks/>
        [XmlAttribute()]
        public string Code;

        // <remarks/>
        [XmlAttribute()]
        public string CodeContext;

        // <remarks/>
        [XmlText()]
        public string Value;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class OperatingCompany
    {

        // <remarks/>
        [XmlAttribute()]
        public string CompanyShortName;

        // <remarks/>
        [XmlAttribute()]
        public string TravelSector;

        // <remarks/>
        [XmlAttribute()]
        public string Code;

        // <remarks/>
        [XmlAttribute()]
        public string CodeContext;

        // <remarks/>
        [XmlText()]
        public string Value;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class BaseFare
    {

        // <remarks/>
        [XmlAttribute()]
        public double Amount;

        // <remarks/>
        [XmlIgnore()]
        public bool AmountSpecified;

        // <remarks/>
        [XmlAttribute()]
        public string CurrencyCode;

        // <remarks/>
        [XmlAttribute()]
        public int DecimalPlaces;

        // <remarks/>
        [XmlIgnore()]
        public bool DecimalPlacesSpecified;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class BasicPropertyInfo
    {

        // <remarks/>
        public Address Address;

        // <remarks/>
        [XmlAttribute()]
        public string ChainCode;

        // <remarks/>
        [XmlAttribute()]
        public string BrandCode;

        // <remarks/>
        [XmlAttribute()]
        public string HotelCode;

        // <remarks/>
        [XmlAttribute()]
        public string HotelCityCode;

        // <remarks/>
        [XmlAttribute()]
        public string HotelName;

        // <remarks/>
        [XmlAttribute()]
        public string HotelCodeContext;

        // <remarks/>
        [XmlAttribute()]
        public string AreaId;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class BookingReferenceID
    {

        // <remarks/>
        [XmlAttribute(DataType = "anyURI")]
        public string URL;

        // <remarks/>
        [XmlAttribute()]
        public string Type;

        // <remarks/>
        [XmlAttribute()]
        public string Instance;

        // <remarks/>
        [XmlAttribute()]
        public string ID;

        // <remarks/>
        [XmlAttribute()]
        public string ID_Context;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class ChargesRules
    {

        // <remarks/>
        public VoluntaryChanges VoluntaryChanges;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class Comment
    {

        // <remarks/>
        public string Text;

        // <remarks/>
        public string Image;

        // <remarks/>
        [XmlElement(DataType = "anyURI")]
        public string URL;

        // <remarks/>
        [XmlAttribute()]
        public int ParagraphNumber;

        // <remarks/>
        [XmlIgnore()]
        public bool ParagraphNumberSpecified;

        // <remarks/>
        [XmlAttribute()]
        public DateTime CreateDateTime;

        // <remarks/>
        [XmlIgnore()]
        public bool CreateDateTimeSpecified;

        // <remarks/>
        [XmlAttribute()]
        public string CreatorID;

        // <remarks/>
        [XmlAttribute()]
        public DateTime LastModifyDateTime;

        // <remarks/>
        [XmlIgnore()]
        public bool LastModifyDateTimeSpecified;

        // <remarks/>
        [XmlAttribute()]
        public string LastModifierID;

        // <remarks/>
        [XmlAttribute()]
        public string Language;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class Comments
    {

        // <remarks/>
        [XmlElement("Comment")]
        public Comment[] Comment;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class CoveragePref
    {

        // <remarks/>
        [XmlAttribute()]
        public string CoverageType;

        // <remarks/>
        [XmlAttribute()]
        public string Code;

        // <remarks/>
        [XmlAttribute()]
        [System.ComponentModel.DefaultValue(CoveragePrefPreferLevel.Preferred)]
        public CoveragePrefPreferLevel PreferLevel = CoveragePrefPreferLevel.Preferred;
    }

    // <remarks/>
    public enum CoveragePrefPreferLevel
    {

        // <remarks/>
        Only,

        // <remarks/>
        Unacceptable,

        // <remarks/>
        Preferred
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class CoveragePrefs
    {

        // <remarks/>
        [XmlElement("CoveragePref")]
        public CoveragePref[] CoveragePref;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class Customer
    {

        // <remarks/>
        public Primary Primary;

        // <remarks/>
        [XmlElement("Additional")]
        public Additional[] Additional;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class Primary
    {

        // <remarks/>
        public PersonName PersonName;

        // <remarks/>
        [XmlElement("Telephone")]
        public Telephone[] Telephone;

        // <remarks/>
        [XmlElement("Email")]
        public Email[] Email;

        // <remarks/>
        [XmlElement("Address")]
        public Address[] Address;

        // <remarks/>
        [XmlElement("CitizenCountryName")]
        public CitizenCountryName[] CitizenCountryName;

        // <remarks/>
        [XmlElement("Document")]
        public Document[] Document;

        // <remarks/>
        [XmlElement("CustLoyalty")]
        public CustLoyalty[] CustLoyalty;

        // <remarks/>
        public TPA_Extensions TPA_Extensions;

        // <remarks/>
        [XmlAttribute()]
        public string BirthDate;

        // <remarks/>
        [XmlAttribute()]
        public string CurrencyCode;

        // <remarks/>
        [XmlAttribute()]
        public int DecimalPlaces;

        // <remarks/>
        [XmlIgnore()]
        public bool DecimalPlacesSpecified;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class DateWindowRange
    {

        // <remarks/>
        [XmlAttribute()]
        public string WindowBefore;

        // <remarks/>
        [XmlAttribute()]
        public string WindowAfter;

        // <remarks/>
        [XmlText()]
        public DateTime Value;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class DeliveryAddress
    {

        // <remarks/>
        public StreetNmbr StreetNmbr;

        // <remarks/>
        public string BldgRoom;

        // <remarks/>
        [XmlElement("AddressLine")]
        public string[] AddressLine;

        // <remarks/>
        public string CityName;

        // <remarks/>
        public string PostalCode;

        // <remarks/>
        public string County;

        // <remarks/>
        public StateProv StateProv;

        // <remarks/>
        public CountryName CountryName;

        // <remarks/>
        [XmlAttribute()]
        [System.ComponentModel.DefaultValue(false)]
        public bool FormattedInd = false;

        // <remarks/>
        [XmlAttribute()]
        public DeliveryAddressShareSynchInd ShareSynchInd;

        // <remarks/>
        [XmlIgnore()]
        public bool ShareSynchIndSpecified;

        // <remarks/>
        [XmlAttribute()]
        public DeliveryAddressShareMarketInd ShareMarketInd;

        // <remarks/>
        [XmlIgnore()]
        public bool ShareMarketIndSpecified;

        // <remarks/>
        [XmlAttribute()]
        public string Type;
    }

    // <remarks/>
    public enum DeliveryAddressShareSynchInd
    {

        // <remarks/>
        Yes,

        // <remarks/>
        No,

        // <remarks/>
        Inherit
    }

    // <remarks/>
    public enum DeliveryAddressShareMarketInd
    {

        // <remarks/>
        Yes,

        // <remarks/>
        No,

        // <remarks/>
        Inherit
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class DepositPayments
    {

        // <remarks/>
        [XmlElement("RequiredPayment")]
        public RequiredPayment[] RequiredPayment;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class RequiredPayment
    {

        // <remarks/>
        [XmlArrayItem(IsNullable = false)]
        public AcceptedPayment[] AcceptedPayments;

        // <remarks/>
        [XmlElement("PaymentDescription")]
        public PaymentDescription[] PaymentDescription;

        // <remarks/>
        [XmlAttribute()]
        public RequiredPaymentRetributionType RetributionType;

        // <remarks/>
        [XmlIgnore()]
        public bool RetributionTypeSpecified;

        // <remarks/>
        [XmlAttribute()]
        public string PaymentCode;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class PaymentDescription
    {

        // <remarks/>
        public string Text;

        // <remarks/>
        public string Image;

        // <remarks/>
        [XmlElement(DataType = "anyURI")]
        public string URL;

        // <remarks/>
        [XmlAttribute()]
        public int ParagraphNumber;

        // <remarks/>
        [XmlIgnore()]
        public bool ParagraphNumberSpecified;

        // <remarks/>
        [XmlAttribute()]
        public DateTime CreateDateTime;

        // <remarks/>
        [XmlIgnore()]
        public bool CreateDateTimeSpecified;

        // <remarks/>
        [XmlAttribute()]
        public string CreatorID;

        // <remarks/>
        [XmlAttribute()]
        public DateTime LastModifyDateTime;

        // <remarks/>
        [XmlIgnore()]
        public bool LastModifyDateTimeSpecified;

        // <remarks/>
        [XmlAttribute()]
        public string LastModifierID;

        // <remarks/>
        [XmlAttribute()]
        public string Language;
    }

    // <remarks/>
    public enum RequiredPaymentRetributionType
    {

        // <remarks/>
        ResAutoCancelled,

        // <remarks/>
        ResNotGuaranteed
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class DriverType
    {

        // <remarks/>
        [XmlAttribute()]
        public int Age;

        // <remarks/>
        [XmlIgnore()]
        public bool AgeSpecified;

        // <remarks/>
        [XmlAttribute()]
        public string Code;

        // <remarks/>
        [XmlAttribute()]
        public string CodeContext;

        // <remarks/>
        [XmlAttribute(DataType = "anyURI")]
        public string URI;

        // <remarks/>
        [XmlAttribute()]
        public int Quantity;

        // <remarks/>
        [XmlIgnore()]
        public bool QuantitySpecified;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class EndDateWindow
    {

        // <remarks/>
        [XmlAttribute(DataType = "date")]
        public DateTime EarliestDate;

        // <remarks/>
        [XmlIgnore()]
        public bool EarliestDateSpecified;

        // <remarks/>
        [XmlAttribute(DataType = "date")]
        public DateTime LatestDate;

        // <remarks/>
        [XmlIgnore()]
        public bool LatestDateSpecified;

        // <remarks/>
        [XmlAttribute()]
        public EndDateWindowDOW DOW;

        // <remarks/>
        [XmlIgnore()]
        public bool DOWSpecified;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class EquivFare
    {

        // <remarks/>
        [XmlAttribute()]
        public double Amount;

        // <remarks/>
        [XmlIgnore()]
        public bool AmountSpecified;

        // <remarks/>
        [XmlAttribute()]
        public string CurrencyCode;

        // <remarks/>
        [XmlAttribute()]
        public int DecimalPlaces;

        // <remarks/>
        [XmlIgnore()]
        public bool DecimalPlacesSpecified;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class FareInfo
    {

        // <remarks/>
        public DateTime DepartureDate;

        // <remarks/>
        [XmlIgnore()]
        public bool DepartureDateSpecified;

        // <remarks/>
        public string FareReference;

        // <remarks/>
        public RuleInfo RuleInfo;

        // <remarks/>
        public FilingAirline FilingAirline;

        // <remarks/>
        public MarketingAirline MarketingAirline;

        // <remarks/>
        public DepartureAirport DepartureAirport;

        // <remarks/>
        public ArrivalAirport ArrivalAirport;

        // <remarks/>
        [XmlAttribute()]
        [System.ComponentModel.DefaultValue(false)]
        public bool NegotiatedFare = false;

        // <remarks/>
        [XmlAttribute()]
        public string NegotiatedFareCode;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class RuleInfo
    {

        // <remarks/>
        public ResTicketingRules ResTicketingRules;

        // <remarks/>
        public LengthOfStayRules LengthOfStayRules;

        // <remarks/>
        public ChargesRules ChargesRules;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class ResTicketingRules
    {

        // <remarks/>
        public AdvResTicketing AdvResTicketing;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class LengthOfStayRules
    {

        // <remarks/>
        public MinimumStay MinimumStay;

        // <remarks/>
        public MaximumStay MaximumStay;

        // <remarks/>
        [XmlAttribute()]
        public bool StayRestrictionsInd;

        // <remarks/>
        [XmlIgnore()]
        public bool StayRestrictionsIndSpecified;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class FareInfos
    {

        // <remarks/>
        [XmlElement("FareInfo")]
        public FareInfo[] FareInfo;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class Fee
    {

        // <remarks/>
        [XmlAttribute()]
        public string FeeCode;

        // <remarks/>
        [XmlAttribute()]
        public double Amount;

        // <remarks/>
        [XmlIgnore()]
        public bool AmountSpecified;

        // <remarks/>
        [XmlAttribute()]
        public string CurrencyCode;

        // <remarks/>
        [XmlAttribute()]
        public int DecimalPlaces;

        // <remarks/>
        [XmlIgnore()]
        public bool DecimalPlacesSpecified;

        // <remarks/>
        [XmlText()]
        public string Value;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class Fees
    {

        // <remarks/>
        [XmlElement("Fee")]
        public Fee[] Fee;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class FlightSegmentRPHs
    {

        // <remarks/>
        [XmlElement("FlightSegmentRPH")]
        public string[] FlightSegmentRPH;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class Fulfillment
    {

        // <remarks/>
        [XmlArrayItem(IsNullable = false)]
        public PaymentDetail[] PaymentDetails;

        // <remarks/>
        public DeliveryAddress DeliveryAddress;

        // <remarks/>
        public string Name;

        // <remarks/>
        public Receipt Receipt;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class PaymentDetail
    {

        // <remarks/>
        public PaymentCard PaymentCard;

        // <remarks/>
        public BankAcct BankAcct;

        // <remarks/>
        public DirectBill DirectBill;

        // <remarks/>
        public Voucher Voucher;

        // <remarks/>
        public LoyaltyRedemption LoyaltyRedemption;

        // <remarks/>
        public MiscChargeOrder MiscChargeOrder;

        // <remarks/>
        public PaymentAmount PaymentAmount;

        // <remarks/>
        [XmlAttribute()]
        public PaymentDetailShareSynchInd ShareSynchInd;

        // <remarks/>
        [XmlIgnore()]
        public bool ShareSynchIndSpecified;

        // <remarks/>
        [XmlAttribute()]
        public PaymentDetailShareMarketInd ShareMarketInd;

        // <remarks/>
        [XmlIgnore()]
        public bool ShareMarketIndSpecified;

        // <remarks/>
        [XmlAttribute()]
        public string CostCenterID;

        // <remarks/>
        [XmlAttribute()]
        public string RPH;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class LoyaltyRedemption
    {

        // <remarks/>
        [XmlAttribute()]
        public string CertificateNumber;

        // <remarks/>
        [XmlAttribute()]
        public string MemberNumber;

        // <remarks/>
        [XmlAttribute()]
        public string ProgramName;

        // <remarks/>
        [XmlAttribute()]
        public string PromotionCode;

        // <remarks/>
        [XmlAttribute()]
        public int RedemptionQuantity;

        // <remarks/>
        [XmlIgnore()]
        public bool RedemptionQuantitySpecified;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class MiscChargeOrder
    {

        // <remarks/>
        [XmlAttribute()]
        public string TicketNumber;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class PaymentAmount
    {

        // <remarks/>
        [XmlAttribute()]
        public double Amount;

        // <remarks/>
        [XmlIgnore()]
        public bool AmountSpecified;

        // <remarks/>
        [XmlAttribute()]
        public string CurrencyCode;

        // <remarks/>
        [XmlAttribute()]
        public int DecimalPlaces;

        // <remarks/>
        [XmlIgnore()]
        public bool DecimalPlacesSpecified;
    }

    // <remarks/>
    public enum PaymentDetailShareSynchInd
    {

        // <remarks/>
        Yes,

        // <remarks/>
        No,

        // <remarks/>
        Inherit
    }

    // <remarks/>
    public enum PaymentDetailShareMarketInd
    {

        // <remarks/>
        Yes,

        // <remarks/>
        No,

        // <remarks/>
        Inherit
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class Receipt
    {

        // <remarks/>
        [XmlAttribute()]
        public string DistribType;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class Guarantee
    {

        // <remarks/>
        [XmlArrayItem(IsNullable = false)]
        public GuaranteeAccepted[] GuaranteesAccepted;

        // <remarks/>
        [XmlArrayItem(IsNullable = false)]
        public Comment[] Comments;

        // <remarks/>
        [XmlElement("GuaranteeDescription")]
        public GuaranteeDescription[] GuaranteeDescription;

        // <remarks/>
        [XmlAttribute()]
        public GuaranteeRetributionType RetributionType;

        // <remarks/>
        [XmlIgnore()]
        public bool RetributionTypeSpecified;

        // <remarks/>
        [XmlAttribute()]
        public string GuaranteeCode;

        // <remarks/>
        [XmlAttribute()]
        public string GuaranteeType;

        // <remarks/>
        [XmlAttribute(DataType = "time")]
        public DateTime HoldTime;

        // <remarks/>
        [XmlIgnore()]
        public bool HoldTimeSpecified;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class GuaranteeAccepted
    {

        // <remarks/>
        public PaymentCard PaymentCard;

        // <remarks/>
        public BankAcct BankAcct;

        // <remarks/>
        public DirectBill DirectBill;

        // <remarks/>
        public Voucher Voucher;

        // <remarks/>
        [XmlAttribute()]
        public GuaranteeAcceptedShareSynchInd ShareSynchInd;

        // <remarks/>
        [XmlIgnore()]
        public bool ShareSynchIndSpecified;

        // <remarks/>
        [XmlAttribute()]
        public GuaranteeAcceptedShareMarketInd ShareMarketInd;

        // <remarks/>
        [XmlIgnore()]
        public bool ShareMarketIndSpecified;

        // <remarks/>
        [XmlAttribute()]
        public string CostCenterId;

        // <remarks/>
        [XmlAttribute()]
        public string RPH;

        // <remarks/>
        [XmlAttribute()]
        public bool Default;

        // <remarks/>
        [XmlIgnore()]
        public bool DefaultSpecified;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class GuaranteeDescription
    {

        // <remarks/>
        public string Text;

        // <remarks/>
        public string Image;

        // <remarks/>
        [XmlElement(DataType = "anyURI")]
        public string URL;

        // <remarks/>
        [XmlAttribute()]
        public int ParagraphNumber;

        // <remarks/>
        [XmlIgnore()]
        public bool ParagraphNumberSpecified;

        // <remarks/>
        [XmlAttribute()]
        public DateTime CreateDateTime;

        // <remarks/>
        [XmlIgnore()]
        public bool CreateDateTimeSpecified;

        // <remarks/>
        [XmlAttribute()]
        public string CreatorID;

        // <remarks/>
        [XmlAttribute()]
        public DateTime LastModifyDateTime;

        // <remarks/>
        [XmlIgnore()]
        public bool LastModifyDateTimeSpecified;

        // <remarks/>
        [XmlAttribute()]
        public string LastModifierID;

        // <remarks/>
        [XmlAttribute()]
        public string Language;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class GuaranteesAccepted
    {

        // <remarks/>
        [XmlElement("GuaranteeAccepted")]
        public GuaranteeAccepted[] GuaranteeAccepted;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class GuestCount
    {

        // <remarks/>
        [XmlAttribute()]
        public string AgeQualifyingCode;

        // <remarks/>
        [XmlAttribute()]
        public int Age;

        // <remarks/>
        [XmlIgnore()]
        public bool AgeSpecified;

        // <remarks/>
        [XmlAttribute()]
        public int Count;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class GuestCounts
    {

        // <remarks/>
        [XmlElement("GuestCount")]
        public GuestCount[] GuestCount;

        // <remarks/>
        [XmlAttribute()]
        public bool IsPerRoom;

        // <remarks/>
        [XmlIgnore()]
        public bool IsPerRoomSpecified;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class HotelReservation
    {

        // <remarks/>
        public UniqueID UniqueId;

        // <remarks/>
        [XmlArrayItem(IsNullable = false)]
        public RoomStay[] RoomStays;

        // <remarks/>
        public TPA_Extensions TPA_Extensions;

        // <remarks/>
        [XmlAttribute()]
        public bool RoomStayReservation;

        // <remarks/>
        [XmlAttribute()]
        public DateTime CreateDateTime;

        // <remarks/>
        [XmlIgnore()]
        public bool CreateDateTimeSpecified;

        // <remarks/>
        [XmlAttribute()]
        public string CreatorID;

        // <remarks/>
        [XmlAttribute()]
        public DateTime LastModifyDateTime;

        // <remarks/>
        [XmlIgnore()]
        public bool LastModifyDateTimeSpecified;

        // <remarks/>
        [XmlAttribute()]
        public string LastModifierID;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class RoomStay
    {

        // <remarks/>
        [XmlArrayItem(IsNullable = false)]
        public RoomType[] RoomTypes;

        // <remarks/>
        [XmlArrayItem(IsNullable = false)]
        public RoomRate[] RoomRates;

        // <remarks/>
        public GuestCounts GuestCounts;

        // <remarks/>
        public TimeSpanRQ TimeSpan;

        // <remarks/>
        [XmlElement("Guarantee")]
        public Guarantee[] Guarantee;

        // <remarks/>
        [XmlArrayItem(IsNullable = false)]
        public RequiredPayment[] DepositPayments;

        // <remarks/>
        public Total Total;

        // <remarks/>
        public BasicPropertyInfo BasicPropertyInfo;

        // <remarks/>
        [XmlArrayItem(IsNullable = false)]
        public ResGuestRPH[] ResGuestRPHs;

        // <remarks/>
        [XmlArrayItem(IsNullable = false)]
        public Membership[] Memberships;

        // <remarks/>
        [XmlArrayItem(IsNullable = false)]
        public Comment[] Comments;

        // <remarks/>
        [XmlArrayItem(IsNullable = false)]
        public SpecialRequest[] SpecialRequests;

        // <remarks/>
        [XmlArrayItem(IsNullable = false)]
        public ServiceRPH[] ServiceRPHs;

        // <remarks/>
        public TPA_Extensions TPA_Extensions;

        // <remarks/>
        [XmlAttribute()]
        public string MarketCode;

        // <remarks/>
        [XmlAttribute()]
        public string SourceOfBusiness;

        // <remarks/>
        [XmlAttribute()]
        public string DiscountCode;

        // <remarks/>
        [XmlAttribute()]
        public string PromotionCode;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class RoomType
    {

        // <remarks/>
        public RoomDescription RoomDescription;

        // <remarks/>
        [XmlArrayItem(IsNullable = false)]
        public AdditionalDetail[] AdditionalDetails;

        // <remarks/>
        [XmlElement("Amenity")]
        public Amenity[] Amenity;

        // <remarks/>
        public TPA_Extensions TPA_Extensions;

        // <remarks/>
        [XmlAttribute()]
        public string RoomTypeCode;

        // <remarks/>
        [XmlAttribute()]
        public int NumberOfUnits;

        // <remarks/>
        [XmlIgnore()]
        public bool NumberOfUnitsSpecified;

        // <remarks/>
        [XmlAttribute()]
        public bool IsRoom;

        // <remarks/>
        [XmlIgnore()]
        public bool IsRoomSpecified;

        // <remarks/>
        [XmlAttribute()]
        public bool IsConverted;

        // <remarks/>
        [XmlIgnore()]
        public bool IsConvertedSpecified;

        // <remarks/>
        [XmlAttribute()]
        public bool IsAlternate;

        // <remarks/>
        [XmlIgnore()]
        public bool IsAlternateSpecified;

        // <remarks/>
        [XmlAttribute()]
        public string InvBlockCode;

        // <remarks/>
        [XmlAttribute()]
        public string ReqdGuaranteeType;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class RoomDescription
    {

        // <remarks/>
        public string Text;

        // <remarks/>
        public string Image;

        // <remarks/>
        [XmlElement(DataType = "anyURI")]
        public string URL;

        // <remarks/>
        [XmlAttribute()]
        public int ParagraphNumber;

        // <remarks/>
        [XmlIgnore()]
        public bool ParagraphNumberSpecified;

        // <remarks/>
        [XmlAttribute()]
        public DateTime CreateDateTime;

        // <remarks/>
        [XmlIgnore()]
        public bool CreateDateTimeSpecified;

        // <remarks/>
        [XmlAttribute()]
        public string CreatorID;

        // <remarks/>
        [XmlAttribute()]
        public DateTime LastModifyDateTime;

        // <remarks/>
        [XmlIgnore()]
        public bool LastModifyDateTimeSpecified;

        // <remarks/>
        [XmlAttribute()]
        public string LastModifierID;

        // <remarks/>
        [XmlAttribute()]
        public string Language;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class RoomRate
    {

        // <remarks/>
        public RoomRateDescription RoomRateDescription;

        // <remarks/>
        [XmlAttribute()]
        public string BookingCode;

        // <remarks/>
        [XmlAttribute(DataType = "date")]
        public DateTime EffectiveDate;

        // <remarks/>
        [XmlIgnore()]
        public bool EffectiveDateSpecified;

        // <remarks/>
        [XmlAttribute(DataType = "date")]
        public DateTime ExpireDate;

        // <remarks/>
        [XmlIgnore()]
        public bool ExpireDateSpecified;

        // <remarks/>
        [XmlAttribute()]
        public string RoomTypeCode;

        // <remarks/>
        [XmlAttribute()]
        public string InvBlockCode;

        // <remarks/>
        [XmlAttribute()]
        public int NumberOfUnits;

        // <remarks/>
        [XmlIgnore()]
        public bool NumberOfUnitsSpecified;

        // <remarks/>
        [XmlAttribute()]
        public string RatePlanType;

        // <remarks/>
        [XmlAttribute()]
        public string RatePlanCode;

        // <remarks/>
        [XmlAttribute()]
        public string RatePlanID;

        // <remarks/>
        [XmlAttribute()]
        public bool RatePlanQualifier;

        // <remarks/>
        [XmlIgnore()]
        public bool RatePlanQualifierSpecified;

        // <remarks/>
        [XmlAttribute()]
        public string PromotionCode;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class RoomRateDescription
    {

        // <remarks/>
        public string Text;

        // <remarks/>
        public string Image;

        // <remarks/>
        [XmlElement(DataType = "anyURI")]
        public string URL;

        // <remarks/>
        [XmlAttribute()]
        public int ParagraphNumber;

        // <remarks/>
        [XmlIgnore()]
        public bool ParagraphNumberSpecified;

        // <remarks/>
        [XmlAttribute()]
        public DateTime CreateDateTime;

        // <remarks/>
        [XmlIgnore()]
        public bool CreateDateTimeSpecified;

        // <remarks/>
        [XmlAttribute()]
        public string CreatorID;

        // <remarks/>
        [XmlAttribute()]
        public DateTime LastModifyDateTime;

        // <remarks/>
        [XmlIgnore()]
        public bool LastModifyDateTimeSpecified;

        // <remarks/>
        [XmlAttribute()]
        public string LastModifierID;

        // <remarks/>
        [XmlAttribute()]
        public string Language;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class TimeSpanRQ
    {

        // <remarks/>
        public DateWindowRange DateWindowRange;

        // <remarks/>
        public StartDateWindow StartDateWindow;

        // <remarks/>
        public EndDateWindow EndDateWindow;

        // <remarks/>
        [XmlAttribute()]
        public DateTime Start;

        // <remarks/>
        [XmlIgnore()]
        public bool StartSpecified;

        // <remarks/>
        [XmlAttribute()]
        public string Duration;

        // <remarks/>
        [XmlAttribute()]
        public DateTime End;

        // <remarks/>
        [XmlIgnore()]
        public bool EndSpecified;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class StartDateWindow
    {

        // <remarks/>
        [XmlAttribute(DataType = "date")]
        public DateTime EarliestDate;

        // <remarks/>
        [XmlIgnore()]
        public bool EarliestDateSpecified;

        // <remarks/>
        [XmlAttribute(DataType = "date")]
        public DateTime LatestDate;

        // <remarks/>
        [XmlIgnore()]
        public bool LatestDateSpecified;

        // <remarks/>
        [XmlAttribute()]
        public StartDateWindowDOW DOW;

        // <remarks/>
        [XmlIgnore()]
        public bool DOWSpecified;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class Total
    {

        // <remarks/>
        [XmlArrayItem(IsNullable = false)]
        public Tax[] Taxes;

        // <remarks/>
        [XmlAttribute()]
        public double AmountBeforeTax;

        // <remarks/>
        [XmlIgnore()]
        public bool AmountBeforeTaxSpecified;

        // <remarks/>
        [XmlAttribute()]
        public double AmountAfterTax;

        // <remarks/>
        [XmlIgnore()]
        public bool AmountAfterTaxSpecified;

        // <remarks/>
        [XmlAttribute()]
        public string CurrencyCode;

        // <remarks/>
        [XmlAttribute()]
        public int DecimalPlaces;

        // <remarks/>
        [XmlIgnore()]
        public bool DecimalPlacesSpecified;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class Tax
    {

        // <remarks/>
        [XmlAttribute()]
        public string TaxCode;

        // <remarks/>
        [XmlAttribute()]
        public double Amount;

        // <remarks/>
        [XmlIgnore()]
        public bool AmountSpecified;

        // <remarks/>
        [XmlAttribute()]
        public string CurrencyCode;

        // <remarks/>
        [XmlAttribute()]
        public int DecimalPlaces;

        // <remarks/>
        [XmlIgnore()]
        public bool DecimalPlacesSpecified;

        // <remarks/>
        [XmlText()]
        public string Value;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class ResGuestRPH
    {

        // <remarks/>
        [XmlAttribute()]
        public string RPH;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class Membership
    {

        // <remarks/>
        [XmlAttribute()]
        public string ProgramCode;

        // <remarks/>
        [XmlAttribute()]
        public string BonusCode;

        // <remarks/>
        [XmlAttribute()]
        public string AccountID;

        // <remarks/>
        [XmlAttribute()]
        public int PointsEarned;

        // <remarks/>
        [XmlIgnore()]
        public bool PointsEarnedSpecified;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class SpecialRequest
    {

        // <remarks/>
        public string Text;

        // <remarks/>
        public string Image;

        // <remarks/>
        [XmlElement(DataType = "anyURI")]
        public string URL;

        // <remarks/>
        [XmlAttribute()]
        public int ParagraphNumber;

        // <remarks/>
        [XmlIgnore()]
        public bool ParagraphNumberSpecified;

        // <remarks/>
        [XmlAttribute()]
        public DateTime CreateDateTime;

        // <remarks/>
        [XmlIgnore()]
        public bool CreateDateTimeSpecified;

        // <remarks/>
        [XmlAttribute()]
        public string CreatorID;

        // <remarks/>
        [XmlAttribute()]
        public DateTime LastModifyDateTime;

        // <remarks/>
        [XmlIgnore()]
        public bool LastModifyDateTimeSpecified;

        // <remarks/>
        [XmlAttribute()]
        public string LastModifierID;

        // <remarks/>
        [XmlAttribute()]
        public string Language;

        // <remarks/>
        [XmlAttribute()]
        public string RequestCode;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class ServiceRPH
    {

        // <remarks/>
        [XmlAttribute()]
        public string RPH;

        // <remarks/>
        [XmlAttribute()]
        public bool IsPerRoom;

        // <remarks/>
        [XmlIgnore()]
        public bool IsPerRoomSpecified;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class HotelReservations
    {

        // <remarks/>
        [XmlElement("HotelReservation")]
        public HotelReservation[] HotelReservation;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class ItinTotalFare
    {

        // <remarks/>
        public BaseFare BaseFare;

        // <remarks/>
        public EquivFare EquivFare;

        // <remarks/>
        [XmlArrayItem(IsNullable = false)]
        public Tax[] Taxes;

        // <remarks/>
        [XmlArrayItem(IsNullable = false)]
        public Fee[] Fees;

        // <remarks/>
        public TotalFare TotalFare;

        // <remarks/>
        [XmlAttribute()]
        [System.ComponentModel.DefaultValue(false)]
        public bool NegotiatedFare = false;

        // <remarks/>
        [XmlAttribute()]
        public string NegotiatedFareCode;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class TotalFare
    {

        // <remarks/>
        [XmlAttribute()]
        public double Amount;

        // <remarks/>
        [XmlIgnore()]
        public bool AmountSpecified;

        // <remarks/>
        [XmlAttribute()]
        public string CurrencyCode;

        // <remarks/>
        [XmlAttribute()]
        public int DecimalPlaces;

        // <remarks/>
        [XmlIgnore()]
        public bool DecimalPlacesSpecified;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class Memberships
    {

        // <remarks/>
        [XmlElement("Membership")]
        public Membership[] Membership;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class OTA_AirBookModifyRQ
    {

        // <remarks/>
        public AirBookModifyRQ AirBookModifyRQ;

        // <remarks/>
        public AirReservation AirReservation;

        // <remarks/>
        [XmlAttribute()]
        public string EchoToken;

        // <remarks/>
        [XmlAttribute()]
        public DateTime TimeStamp;

        // <remarks/>
        [XmlIgnore()]
        public bool TimeStampSpecified;

        // <remarks/>
        [XmlAttribute()]
        [System.ComponentModel.DefaultValue(OTA_AirBookModifyRQTarget.Production)]
        public OTA_AirBookModifyRQTarget Target = OTA_AirBookModifyRQTarget.Production;

        // <remarks/>
        [XmlAttribute()]
        public double Version;

        // <remarks/>
        [XmlIgnore()]
        public bool VersionSpecified;

        // <remarks/>
        [XmlAttribute()]
        public string TransactionIdentifier;

        // <remarks/>
        [XmlAttribute()]
        public int SequenceNmbr;

        // <remarks/>
        [XmlIgnore()]
        public bool SequenceNmbrSpecified;

        // <remarks/>
        [XmlAttribute()]
        public OTA_AirBookModifyRQTransactionStatusCode TransactionStatusCode;

        // <remarks/>
        [XmlIgnore()]
        public bool TransactionStatusCodeSpecified;

        // <remarks/>
        [XmlAttribute()]
        public string PrimaryLangID;

        // <remarks/>
        [XmlAttribute()]
        public string AltLangID;
    }
    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class AirBookModifyRQ
    {

        // <remarks/>
        public AirItinerary AirItinerary;

        // <remarks/>
        public PriceInfo PriceInfo;

        // <remarks/>
        public TravelerInfo TravelerInfo;

        // <remarks/>
        public Fulfillment Fulfillment;

        // <remarks/>
        public Ticketing Ticketing;

        // <remarks/>
        [XmlElement("Queue")]
        public Queue[] Queue;

        // <remarks/>
        [XmlAttribute()]
        public string BookingReferenceID;

        // <remarks/>
        [XmlAttribute()]
        public DateTime LastModified;

        // <remarks/>
        [XmlIgnore()]
        public bool LastModifiedSpecified;

        // <remarks/>
        [XmlAttribute()]
        public AirBookModifyRQModificationType ModificationType;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class AirReservation
    {

        // <remarks/>
        public AirItinerary AirItinerary;

        // <remarks/>
        public PriceInfo PriceInfo;

        // <remarks/>
        public TravelerInfo TravelerInfo;

        // <remarks/>
        public Fulfillment Fulfillment;

        // <remarks/>
        public Ticketing Ticketing;

        // <remarks/>
        [XmlElement("Queue")]
        public Queue[] Queue;

        // <remarks/>
        [XmlAttribute()]
        public string BookingReferenceID;

        // <remarks/>
        [XmlAttribute()]
        public DateTime LastModified;

        // <remarks/>
        [XmlIgnore()]
        public bool LastModifiedSpecified;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class PriceInfo
    {

        // <remarks/>
        public ItinTotalFare ItinTotalFare;

        // <remarks/>
        [XmlArrayItem(IsNullable = false)]
        public PTC_FareBreakdown[] PTC_FareBreakdowns;

        // <remarks/>
        [XmlArrayItem(IsNullable = false)]
        public FareInfo[] FareInfos;

        // <remarks/>
        [XmlAttribute()]
        public PriceInfoPricingSource PricingSource;

        // <remarks/>
        [XmlIgnore()]
        public bool PricingSourceSpecified;

        // <remarks/>
        [XmlAttribute()]
        [System.ComponentModel.DefaultValue(false)]
        public bool RepriceRequired = false;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class PTC_FareBreakdown
    {

        // <remarks/>
        public PassengerTypeQuantity PassengerTypeQuantity;

        // <remarks/>
        [XmlArrayItem("FareBasisCode", IsNullable = false)]
        public string[] FareBasisCodes;

        // <remarks/>
        public PassengerFare PassengerFare;

        // <remarks/>
        [XmlAttribute()]
        public PTC_FareBreakdownPricingSource PricingSource;

        // <remarks/>
        [XmlIgnore()]
        public bool PricingSourceSpecified;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class PassengerFare
    {

        // <remarks/>
        public BaseFare BaseFare;

        // <remarks/>
        public EquivFare EquivFare;

        // <remarks/>
        [XmlArrayItem(IsNullable = false)]
        public Tax[] Taxes;

        // <remarks/>
        [XmlArrayItem(IsNullable = false)]
        public Fee[] Fees;

        // <remarks/>
        public TotalFare TotalFare;

        // <remarks/>
        [XmlAttribute()]
        [System.ComponentModel.DefaultValue(false)]
        public bool NegotiatedFare = false;

        // <remarks/>
        [XmlAttribute()]
        public string NegotiatedFareCode;
    }

    // <remarks/>
    public enum PriceInfoPricingSource
    {

        // <remarks/>
        Published,

        // <remarks/>
        Private,

        // <remarks/>
        Both
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class TravelerInfo
    {

        // <remarks/>
        [XmlElement("AirTraveler")]
        public AirTraveler[] AirTraveler;

        // <remarks/>
        public SpecialReqDetails SpecialReqDetails;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class SpecialReqDetails
    {

        // <remarks/>
        [XmlArrayItem(IsNullable = false)]
        public SeatRequest[] SeatRequests;

        // <remarks/>
        [XmlArrayItem(IsNullable = false)]
        public SpecialServiceRequest[] SpecialServiceRequests;

        // <remarks/>
        [XmlArrayItem(IsNullable = false)]
        public OtherServiceInformation[] OtherServiceInformations;

        // <remarks/>
        [XmlArrayItem("Remark", IsNullable = false)]
        public string[] Remarks;

        // <remarks/>
        [XmlArrayItem(IsNullable = false)]
        public UniqueRemark[] UniqueRemarks;

        // <remarks/>
        [XmlArrayItem(IsNullable = false)]
        public SpecialRemark[] SpecialRemarks;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class SpecialRemark
    {

        // <remarks/>
        [XmlElement("TravelerRefNumber")]
        public TravelerRefNumber[] TravelerRefNumber;

        // <remarks/>
        [XmlElement("FlightRefNumber")]
        public FlightRefNumber[] FlightRefNumber;

        // <remarks/>
        public string Text;

        // <remarks/>
        [XmlAttribute()]
        public SpecialRemarkRemarkType RemarkType;
    }

    // <remarks/>
    public enum SpecialRemarkRemarkType
    {

        // <remarks/>
        Air,

        // <remarks/>
        Car,

        // <remarks/>
        Hotel,

        // <remarks/>
        Invoice,

        // <remarks/>
        Endorsement,

        // <remarks/>
        A,

        // <remarks/>
        B,

        // <remarks/>
        C,

        // <remarks/>
        D,

        // <remarks/>
        E,

        // <remarks/>
        F,

        // <remarks/>
        G,

        // <remarks/>
        H,

        // <remarks/>
        I,

        // <remarks/>
        J,

        // <remarks/>
        K,

        // <remarks/>
        L,

        // <remarks/>
        M,

        // <remarks/>
        N,

        // <remarks/>
        O,

        // <remarks/>
        P,

        // <remarks/>
        Q,

        // <remarks/>
        R,

        // <remarks/>
        S,

        // <remarks/>
        T,

        // <remarks/>
        U,

        // <remarks/>
        V,

        // <remarks/>
        W,

        // <remarks/>
        X,

        // <remarks/>
        Y,

        // <remarks/>
        Z

    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class Queue
    {

        // <remarks/>
        [XmlAttribute()]
        public string PseudoCityCode;

        // <remarks/>
        [XmlAttribute()]
        public string QueueNumber;

        // <remarks/>
        [XmlAttribute()]
        public string QueueCategory;
    }

    // <remarks/>
    public enum OTA_AirBookModifyRQTarget
    {

        // <remarks/>
        Test,

        // <remarks/>
        Production
    }

    // <remarks/>
    public enum OTA_AirBookModifyRQTransactionStatusCode
    {

        // <remarks/>
        Start,

        // <remarks/>
        End,

        // <remarks/>
        Rollback,

        // <remarks/>
        InSeries
    }

    // <remarks/>
    public enum AirBookModifyRQModificationType
    {

        // <remarks/>
        Add,

        // <remarks/>
        Delete,

        // <remarks/>
        Change
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class OTA_HotelResRQ
    {

        // <remarks/>
        public UniqueID UniqueId;

        // <remarks/>
        [XmlArrayItem(IsNullable = false)]
        public HotelReservation[] HotelReservations;

        // <remarks/>
        [XmlAttribute()]
        public string EchoToken;

        // <remarks/>
        [XmlAttribute()]
        public DateTime TimeStamp;

        // <remarks/>
        [XmlIgnore()]
        public bool TimeStampSpecified;

        // <remarks/>
        [XmlAttribute()]
        [System.ComponentModel.DefaultValue(OTA_HotelResRQTarget.Production)]
        public OTA_HotelResRQTarget Target = OTA_HotelResRQTarget.Production;

        // <remarks/>
        [XmlAttribute()]
        public string Version;

        // <remarks/>
        [XmlAttribute()]
        public int SequenceNmbr;

        // <remarks/>
        [XmlIgnore()]
        public bool SequenceNmbrSpecified;

        // <remarks/>
        [XmlAttribute()]
        public string PrimaryLangID;

        // <remarks/>
        [XmlAttribute()]
        public string AltLangID;

        // <remarks/>
        [XmlAttribute()]
        public OTA_HotelResRQResStatus ResStatus;

        // <remarks/>
        [XmlIgnore()]
        public bool ResStatusSpecified;
    }

    // <remarks/>
    public enum OTA_HotelResRQTarget
    {

        // <remarks/>
        Test,

        // <remarks/>
        Production
    }

    // <remarks/>
    public enum OTA_HotelResRQResStatus
    {

        // <remarks/>
        Book,

        // <remarks/>
        Quote,

        // <remarks/>
        Hold,

        // <remarks/>
        Initiate,

        // <remarks/>
        Ignore,

        // <remarks/>
        Modify,

        // <remarks/>
        Commit,

        // <remarks/>
        OnRequest
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class OTA_TravelModifyRQ
    {

        // <remarks/>
        public UniqueIDRQ UniqueID;

        // <remarks/>
        public string ConversationID;

        // <remarks/>
        public POS POS;

        // <remarks/>
        public OTA_AirBookModifyRQ OTA_AirBookModifyRQ;

        // <remarks/>
        public OTA_HotelResRQ OTA_HotelResRQ;

        // <remarks/>
        public OTA_VehResRQ OTA_VehResRQ;

        // <remarks/>
        public TPA_Extensions TPA_Extensions;

        // <remarks/>
        [XmlAttribute()]
        public string EchoToken;

        // <remarks/>
        [XmlAttribute()]
        public DateTime TimeStamp;

        // <remarks/>
        [XmlIgnore()]
        public bool TimeStampSpecified;

        // <remarks/>
        [XmlAttribute()]
        [System.ComponentModel.DefaultValue(OTA_TravelModifyRQTarget.Production)]
        public OTA_TravelModifyRQTarget Target = OTA_TravelModifyRQTarget.Production;

        // <remarks/>
        [XmlAttribute()]
        public string Version;

        // <remarks/>
        [XmlAttribute()]
        public int SequenceNmbr;

        // <remarks/>
        [XmlIgnore()]
        public bool SequenceNmbrSpecified;

        // <remarks/>
        [XmlAttribute()]
        public string PrimaryLangID;

        // <remarks/>
        [XmlAttribute()]
        public string AltLangID;

        // <remarks/>
        [XmlAttribute()]
        public OTA_TravelModifyRQResStatus ResStatus;

        // <remarks/>
        [XmlIgnore()]
        public bool ResStatusSpecified;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class POS
    {

        // <remarks/>
        [XmlElement("Source")]
        public Source[] Source;

        // <remarks/>
        public TPA_Extensions TPA_Extensions;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class UniqueIDRQ
    {

        // <remarks/>
        public CompanyName CompanyName;

        // <remarks/>
        [XmlAttribute(DataType = "anyURI")]
        public string URL;

        // <remarks/>
        [XmlAttribute()]
        public string Type;

        // <remarks/>
        [XmlAttribute()]
        public string Instance;

        // <remarks/>
        [XmlAttribute()]
        public string ID;

        // <remarks/>
        [XmlAttribute()]
        public string ID_Context;
    }


    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class Source
    {

        // <remarks/>
        public RequestorID RequestorID;

        // <remarks/>
        public Position Position;

        // <remarks/>
        [XmlAttribute()]
        public string AgentSine;

        // <remarks/>
        [XmlAttribute()]
        public string PseudoCityCode;

        // <remarks/>
        [XmlAttribute()]
        public string ISOCountry;

        // <remarks/>
        [XmlAttribute()]
        public string ISOCurrency;

        // <remarks/>
        [XmlAttribute()]
        public string AgentDutyCode;

        // <remarks/>
        [XmlAttribute()]
        public string AirlineVendorID;

        // <remarks/>
        [XmlAttribute()]
        public string AirportCode;

        // <remarks/>
        [XmlAttribute()]
        public string FirstDepartPoint;

        // <remarks/>
        [XmlAttribute()]
        public string ERSP_UserID;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class RequestorID
    {

        // <remarks/>
        public CompanyName CompanyName;

        // <remarks/>
        [XmlAttribute(DataType = "anyURI")]
        public string URL;

        // <remarks/>
        [XmlAttribute()]
        public string Type;

        // <remarks/>
        [XmlAttribute()]
        public string Instance;

        // <remarks/>
        [XmlAttribute()]
        public string ID;

        // <remarks/>
        [XmlAttribute()]
        public string ID_Context;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class Position
    {

        // <remarks/>
        [XmlAttribute()]
        public string Latitude;

        // <remarks/>
        [XmlAttribute()]
        public string Longitude;

        // <remarks/>
        [XmlAttribute()]
        public string Altitude;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class OTA_VehResRQ
    {

        // <remarks/>
        public VehResRQCore VehResRQCore;

        // <remarks/>
        public VehResRQInfo VehResRQInfo;

        // <remarks/>
        [XmlAttribute()]
        public string EchoToken;

        // <remarks/>
        [XmlAttribute()]
        public DateTime TimeStamp;

        // <remarks/>
        [XmlIgnore()]
        public bool TimeStampSpecified;

        // <remarks/>
        [XmlAttribute()]
        [System.ComponentModel.DefaultValue(OTA_VehResRQTarget.Production)]
        public OTA_VehResRQTarget Target = OTA_VehResRQTarget.Production;

        // <remarks/>
        [XmlAttribute()]
        public string Version;

        // <remarks/>
        [XmlAttribute()]
        public int SequenceNmbr;

        // <remarks/>
        [XmlIgnore()]
        public bool SequenceNmbrSpecified;

        // <remarks/>
        [XmlAttribute()]
        public string PrimaryLangID;

        // <remarks/>
        [XmlAttribute()]
        public string AltLangID;

        // <remarks/>
        [XmlAttribute()]
        public string ReqRespVersion;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class VehResRQCore
    {

        // <remarks/>
        public VehRentalCore VehRentalCore;

        // <remarks/>
        public Customer Customer;

        // <remarks/>
        public VendorPref VendorPref;

        // <remarks/>
        public VehPref VehPref;

        // <remarks/>
        [XmlElement("DriverType")]
        public DriverType[] DriverType;

        // <remarks/>
        public RateQualifier RateQualifier;

        // <remarks/>
        [XmlArrayItem(IsNullable = false)]
        public SpecialEquipPref[] SpecialEquipPrefs;

        // <remarks/>
        public TPA_Extensions TPA_Extensions;

        // <remarks/>
        [XmlAttribute()]
        public VehResRQCoreStatus Status;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class VendorPref
    {

        // <remarks/>
        [XmlAttribute()]
        public string CompanyShortName;

        // <remarks/>
        [XmlAttribute()]
        public string TravelSector;

        // <remarks/>
        [XmlAttribute()]
        public string Code;

        // <remarks/>
        [XmlAttribute()]
        public string CodeContext;

        // <remarks/>
        [XmlAttribute()]
        [System.ComponentModel.DefaultValue(VendorPrefPreferLevel.Preferred)]
        public VendorPrefPreferLevel PreferLevel = VendorPrefPreferLevel.Preferred;

        // <remarks/>
        [XmlText()]
        public string Value;
    }

    // <remarks/>
    public enum VendorPrefPreferLevel
    {

        // <remarks/>
        Only,

        // <remarks/>
        Unacceptable,

        // <remarks/>
        Preferred
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class VehPref
    {

        // <remarks/>
        public VehType VehType;

        // <remarks/>
        public VehClass VehClass;

        // <remarks/>
        [XmlAttribute()]
        public bool AirConditionInd;

        // <remarks/>
        [XmlIgnore()]
        public bool AirConditionIndSpecified;

        // <remarks/>
        [XmlAttribute()]
        public VehPrefTransmissionType TransmissionType;

        // <remarks/>
        [XmlIgnore()]
        public bool TransmissionTypeSpecified;

        // <remarks/>
        [XmlAttribute()]
        public VehPrefTypePref TypePref;

        // <remarks/>
        [XmlIgnore()]
        public bool TypePrefSpecified;

        // <remarks/>
        [XmlAttribute()]
        public VehPrefClassPref ClassPref;

        // <remarks/>
        [XmlIgnore()]
        public bool ClassPrefSpecified;

        // <remarks/>
        [XmlAttribute()]
        public VehPrefAirConditionPref AirConditionPref;

        // <remarks/>
        [XmlIgnore()]
        public bool AirConditionPrefSpecified;

        // <remarks/>
        [XmlAttribute()]
        public VehPrefTransmissionPref TransmissionPref;

        // <remarks/>
        [XmlIgnore()]
        public bool TransmissionPrefSpecified;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class VehType
    {

        // <remarks/>
        [XmlAttribute()]
        public string VehicleCategory;

        // <remarks/>
        [XmlAttribute()]
        public int DoorCount;

        // <remarks/>
        [XmlIgnore()]
        public bool DoorCountSpecified;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class VehClass
    {

        // <remarks/>
        [XmlAttribute()]
        public string Size;
    }

    // <remarks/>
    public enum VehPrefTransmissionType
    {

        // <remarks/>
        Automatic,

        // <remarks/>
        Manual
    }

    // <remarks/>
    public enum VehPrefTypePref
    {

        // <remarks/>
        Only,

        // <remarks/>
        Unacceptable,

        // <remarks/>
        Preferred
    }

    // <remarks/>
    public enum VehPrefClassPref
    {

        // <remarks/>
        Only,

        // <remarks/>
        Unacceptable,

        // <remarks/>
        Preferred
    }

    // <remarks/>
    public enum VehPrefAirConditionPref
    {

        // <remarks/>
        Only,

        // <remarks/>
        Unacceptable,

        // <remarks/>
        Preferred
    }

    // <remarks/>
    public enum VehPrefTransmissionPref
    {

        // <remarks/>
        Only,

        // <remarks/>
        Unacceptable,

        // <remarks/>
        Preferred
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class RateQualifier
    {

        // <remarks/>
        [XmlAttribute()]
        public string TravelPurpose;

        // <remarks/>
        [XmlAttribute()]
        public string RateCategory;

        // <remarks/>
        [XmlAttribute()]
        public string CorpDiscountNmbr;

        // <remarks/>
        [XmlAttribute()]
        public string PromotionCode;

        // <remarks/>
        [XmlAttribute("RateQualifier")]
        public string RateQualifier1;

        // <remarks/>
        [XmlAttribute()]
        public RateQualifierRatePeriod RatePeriod;

        // <remarks/>
        [XmlIgnore()]
        public bool RatePeriodSpecified;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class SpecialEquipPref
    {

        // <remarks/>
        [XmlAttribute()]
        public string EquipType;

        // <remarks/>
        [XmlAttribute()]
        public int Quantity;

        // <remarks/>
        [XmlIgnore()]
        public bool QuantitySpecified;

        // <remarks/>
        [XmlAttribute()]
        [System.ComponentModel.DefaultValue(SpecialEquipPrefPreferLevel.Preferred)]
        public SpecialEquipPrefPreferLevel PreferLevel = SpecialEquipPrefPreferLevel.Preferred;
    }

    // <remarks/>
    public enum SpecialEquipPrefPreferLevel
    {

        // <remarks/>
        Only,

        // <remarks/>
        Unacceptable,

        // <remarks/>
        Preferred
    }

    // <remarks/>
    public enum VehResRQCoreStatus
    {

        // <remarks/>
        Available,

        // <remarks/>
        Unavailable,

        // <remarks/>
        OnRequest,

        // <remarks/>
        Confirmed,

        // <remarks/>
        All
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class VehResRQInfo
    {

        // <remarks/>
        [XmlElement("SpecialReqPref")]
        public SpecialReqPref[] SpecialReqPref;

        // <remarks/>
        [XmlArrayItem(IsNullable = false)]
        public CoveragePref[] CoveragePrefs;

        // <remarks/>
        [XmlElement("OffLocService")]
        public OffLocService[] OffLocService;

        // <remarks/>
        public ArrivalDetails ArrivalDetails;

        // <remarks/>
        public RentalPaymentPref RentalPaymentPref;

        // <remarks/>
        public TPA_Extensions TPA_Extensions;

        // <remarks/>
        [XmlAttribute()]
        public int LuggageQty;

        // <remarks/>
        [XmlIgnore()]
        public bool LuggageQtySpecified;

        // <remarks/>
        [XmlAttribute()]
        public int PassengerQty;

        // <remarks/>
        [XmlIgnore()]
        public bool PassengerQtySpecified;

        // <remarks/>
        [XmlAttribute()]
        [System.ComponentModel.DefaultValue(false)]
        public bool SmokingAllowed = false;

        // <remarks/>
        [XmlAttribute()]
        [System.ComponentModel.DefaultValue(false)]
        public bool GasPrePay = false;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class SpecialReqPref
    {

        // <remarks/>
        [XmlAttribute()]
        [System.ComponentModel.DefaultValue(SpecialReqPrefPreferLevel.Preferred)]
        public SpecialReqPrefPreferLevel PreferLevel = SpecialReqPrefPreferLevel.Preferred;

        // <remarks/>
        [XmlText()]
        public string Value;
    }

    // <remarks/>
    public enum SpecialReqPrefPreferLevel
    {

        // <remarks/>
        Only,

        // <remarks/>
        Unacceptable,

        // <remarks/>
        Preferred
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class OffLocService
    {

        // <remarks/>
        public Address Address;

        // <remarks/>
        public PersonName PersonName;

        // <remarks/>
        public Telephone Telephone;

        // <remarks/>
        [XmlAttribute()]
        public OffLocServiceType Type;

        // <remarks/>
        [XmlAttribute()]
        public string SpecInstructions;
    }

    // <remarks/>
    public enum OffLocServiceType
    {

        // <remarks/>
        CustPickUp,

        // <remarks/>
        VehDelivery,

        // <remarks/>
        CustDropOff,

        // <remarks/>
        VehCollection
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class RentalPaymentPref
    {

        // <remarks/>
        public PaymentCard PaymentCard;

        // <remarks/>
        public BankAcct BankAcct;

        // <remarks/>
        public DirectBill DirectBill;

        // <remarks/>
        public Voucher Voucher;

        // <remarks/>
        [XmlAttribute()]
        public RentalPaymentPrefShareSynchInd ShareSynchInd;

        // <remarks/>
        [XmlIgnore()]
        public bool ShareSynchIndSpecified;

        // <remarks/>
        [XmlAttribute()]
        public RentalPaymentPrefShareMarketInd ShareMarketInd;

        // <remarks/>
        [XmlIgnore()]
        public bool ShareMarketIndSpecified;

        // <remarks/>
        [XmlAttribute()]
        public string CostCenterId;

        // <remarks/>
        [XmlAttribute()]
        public string RPH;
    }

    // <remarks/>
    public enum RentalPaymentPrefShareSynchInd
    {

        // <remarks/>
        Yes,

        // <remarks/>
        No,

        // <remarks/>
        Inherit
    }

    // <remarks/>
    public enum RentalPaymentPrefShareMarketInd
    {

        // <remarks/>
        Yes,

        // <remarks/>
        No,

        // <remarks/>
        Inherit
    }

    // <remarks/>
    public enum OTA_VehResRQTarget
    {

        // <remarks/>
        Test,

        // <remarks/>
        Production
    }

    // <remarks/>
    public enum OTA_TravelModifyRQTarget
    {

        // <remarks/>
        Test,

        // <remarks/>
        Production
    }

    // <remarks/>
    public enum OTA_TravelModifyRQResStatus
    {

        // <remarks/>
        Book,

        // <remarks/>
        Quote,

        // <remarks/>
        Hold,

        // <remarks/>
        Initiate,

        // <remarks/>
        Ignore,

        // <remarks/>
        Modify,

        // <remarks/>
        Commit
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class OriginDestinationOption
    {

        // <remarks/>
        [XmlElement("FlightSegment")]
        public FlightSegment[] FlightSegment;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class OriginDestinationOptions
    {

        // <remarks/>
        [XmlArrayItem(typeof(FlightSegment), IsNullable = false)]
        public FlightSegment[][] OriginDestinationOption;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class PTC_FareBreakdowns
    {

        // <remarks/>
        [XmlElement("PTC_FareBreakdown")]
        public PTC_FareBreakdown[] PTC_FareBreakdown;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class PaymentDetails
    {

        // <remarks/>
        [XmlElement("PaymentDetail")]
        public PaymentDetail[] PaymentDetail;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class Remarks
    {

        // <remarks/>
        [XmlElement("Remark")]
        public string[] Remark;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class ResGuestRPHs
    {

        // <remarks/>
        [XmlElement("ResGuestRPH")]
        public ResGuestRPH[] ResGuestRPH;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class RoomRates
    {

        // <remarks/>
        [XmlElement("RoomRate")]
        public RoomRate[] RoomRate;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class RoomStays
    {

        // <remarks/>
        [XmlElement("RoomStay")]
        public RoomStay[] RoomStay;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class RoomTypes
    {

        // <remarks/>
        [XmlElement("RoomType")]
        public RoomType[] RoomType;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class ServiceRPHs
    {

        // <remarks/>
        [XmlElement("ServiceRPH")]
        public ServiceRPH[] ServiceRPH;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class SpecialEquipPrefs
    {

        // <remarks/>
        [XmlElement("SpecialEquipPref")]
        public SpecialEquipPref[] SpecialEquipPref;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class SpecialRemarks
    {

        // <remarks/>
        [XmlElement("SpecialRemark")]
        public SpecialRemark[] SpecialRemark;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class SpecialRequests
    {

        // <remarks/>
        [XmlElement("SpecialRequest")]
        public SpecialRequest[] SpecialRequest;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class Taxes
    {

        // <remarks/>
        [XmlElement("Tax")]
        public Tax[] Tax;
    }

}