// This code was generated by a tool.
// Runtime Version: 4.0.30319.42000
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Xml.Serialization;
// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace wsTripXML.wsTravelTalk.wmGenerateVirtualCard
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [System.ComponentModel.DesignerCategory("code")]
    public partial class PAY_GenerateVirtualCardRQ
    {

        // <remarks/>
        public VirtualCreditCard.POS POS { get; set; }

        // <remarks/>
        public string ConversationID { get; set; }

        /// <remarks/>
        public VirtualCardDetail VirtualCard { get; set; }

        /// <remarks/>
        public VirtualCreditCard.NotificationType Notification { get; set; }

        /// <remarks/>
        public ReportingInfo ReportingInfo { get; set; }

        /// <remarks/>
        public VirtualCreditCard.ReservationType Reservation { get; set; }

        /// <remarks/>
        [XmlAttribute()]
        public string EchoToken { get; set; }

        /// <remarks/>
        [XmlAttribute()]
        public DateTime TimeStamp { get; set; }

        /// <remarks/>
        [XmlIgnore()]
        public bool TimeStampSpecified { get; set; }

        /// <remarks/>
        [XmlAttribute()]
        public VirtualCreditCard.Target Target { get; set; }

        /// <remarks/>
        [XmlIgnore()]
        public bool TargetSpecified { get; set; }

        /// <remarks/>
        [XmlAttribute()]
        public string TargetName { get; set; }

        /// <remarks/>
        [XmlAttribute()]
        public decimal Version { get; set; }

        /// <remarks/>
        [XmlAttribute()]
        public string TransactionIdentifier { get; set; }

        /// <remarks/>
        [XmlAttribute()]
        public long SequenceNmbr { get; set; }

        /// <remarks/>
        [XmlIgnore()]
        public bool SequenceNmbrSpecified { get; set; }

        /// <remarks/>
        [XmlAttribute()]
        public VirtualCreditCard.TransactionStatusCode TransactionStatusCode { get; set; }

        /// <remarks/>
        [XmlIgnore()]
        public bool TransactionStatusCodeSpecified { get; set; }

        /// <remarks/>
        [XmlAttribute(DataType = "language")]
        public string PrimaryLangID { get; set; }

        /// <remarks/>
        [XmlAttribute(DataType = "language")]
        public string AltLangID { get; set; }

        /// <remarks/>
        [XmlAttribute()]
        public bool RetransmissionIndicator { get; set; }

        /// <remarks/>
        [XmlIgnore()]
        public bool RetransmissionIndicatorSpecified { get; set; }

        /// <remarks/>
        [XmlAttribute()]
        public string CorrelationID { get; set; }

    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [System.ComponentModel.DesignerCategory("code")]
    public partial class VirtualCardDetail
    {

        /// <remarks/>
        public VirtualCreditCard.VirtualCardAccountType Account { get; set; }

        /// <remarks/>
        public VirtualCreditCard.CardRestrictionsType Limitations { get; set; }

        /// <remarks/>
        [XmlAttribute()]
        public string CardName { get; set; }

        /// <remarks/>
        [XmlAttribute()]
        public string SubType { get; set; }

        /// <remarks/>
        [XmlAttribute()]
        public string VendorCode { get; set; }

        /// <remarks/>
        [XmlAttribute()]
        public bool ReturnCVV { get; set; }

        /// <remarks/>
        [XmlIgnore()]
        public bool ReturnCVVSpecified { get; set; }

        /// <remarks/>
        [XmlAttribute(DataType = "nonNegativeInteger")]
        public string Amount { get; set; }

        /// <remarks/>
        [XmlAttribute(DataType = "nonNegativeInteger")]
        public string DecimalPlaces { get; set; }

        /// <remarks/>
        [XmlAttribute()]
        public string CurrencyCode { get; set; }

    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [System.ComponentModel.DesignerCategory("code")]
    public partial class ReportingInfo : VirtualCreditCard.ReportingInfoType
    {

        /// <remarks/>
        public ReportingInfoFees Fees { get; set; }

    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [System.ComponentModel.DesignerCategory("code")]
    public partial class ReportingInfoFees
    {

        /// <remarks/>
        public VirtualCreditCard.VirtualCardAmountType PurchasePrice { get; set; }

        /// <remarks/>
        [XmlElement("Fee")]
        public ReportingInfoFeesFee Fee { get; set; }

    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [System.ComponentModel.DesignerCategory("code")]
    public partial class ReportingInfoFeesFee
    {

        /// <remarks/>
        public VirtualCreditCard.VirtualCardAmountType Value { get; set; }

        /// <remarks/>
        public string VendorCode { get; set; }

        /// <remarks/>
        public string CardType { get; set; }

    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable()]
    public enum PersonNameTypeShareSynchInd
    {

        /// <remarks/>
        Yes,

        /// <remarks/>
        No,

        /// <remarks/>
        Inherit
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable()]
    public enum PersonNameTypeShareMarketInd
    {

        /// <remarks/>
        Yes,

        /// <remarks/>
        No,

        /// <remarks/>
        Inherit
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [System.ComponentModel.DesignerCategory("code")]
    public partial class CustomerTypeEmail : EmailType
    {


        /// <remarks/>
        [XmlAttribute()]
        public VirtualCreditCard.TransferActionType TransferAction { get; set; }

        /// <remarks/>
        [XmlIgnore()]
        public bool TransferActionSpecified { get; set; }

        /// <remarks/>
        [XmlAttribute()]
        public string ParentCompanyRef { get; set; }

    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [System.ComponentModel.DesignerCategory("code")]
    public partial class EmailType
    {
        /// <remarks/>
        [XmlAttribute()]
        public PersonNameTypeShareSynchInd ShareSynchInd { get; set; }

        /// <remarks/>
        [XmlIgnore()]
        public bool ShareSynchIndSpecified { get; set; }

        /// <remarks/>
        [XmlAttribute()]
        public PersonNameTypeShareMarketInd ShareMarketInd { get; set; }

        /// <remarks/>
        [XmlIgnore()]
        public bool ShareMarketIndSpecified { get; set; }

        /// <remarks/>
        [XmlAttribute()]
        public bool DefaultInd { get; set; }

        /// <remarks/>
        [XmlIgnore()]
        public bool DefaultIndSpecified { get; set; }

        /// <remarks/>
        [XmlAttribute("EmailType")]
        public string EmailType1 { get; set; }

        /// <remarks/>
        [XmlAttribute()]
        public string RPH { get; set; }

        /// <remarks/>
        [XmlAttribute()]
        public string Remark { get; set; }

        /// <remarks/>
        [XmlText()]
        public string Value { get; set; }

    }

}