// ------------------------------------------------------------------------------
// <autogenerated>
// This code was generated by a tool.
// Runtime Version: 1.1.4322.573
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated.
// </autogenerated>
// ------------------------------------------------------------------------------


using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=1.1.4322.573.
// 
namespace wsTripXML.wsTravelTalk.wmInventoryManagementOut
{
    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class TXML_InventoryManagementRS
    {

        // <remarks/>
        public Success Success;

        // <remarks/>
        [XmlArrayItem("Warning", IsNullable = false)]
        public string[] Warnings;

        // <remarks/>
        public Inventory Inventory;

        // <remarks/>
        [XmlArrayItem("Error", IsNullable = false)]
        public string[] Errors;

        // <remarks/>
        [XmlAttribute()]
        public double Version;

    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class Success
    {
    }


    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class Inventory
    {

        // <remarks/>
        public MarketingAirline MarketingAirline;

        // <remarks/>
        public InitialDate InitialDate;
    }

    // <remarks/>
    public class MarketingAirline
    {

        // <remarks/>
        [XmlAttribute()]
        public string Code;

        // <remarks/>
        [XmlAttribute()]
        public string CodeContext;

        // <remarks/>
        [XmlAttribute()]
        public string FlightNumber;
    }

    // <remarks/>
    public class InitialDate
    {

        // <remarks/>
        [XmlAttribute()]
        public DayOfWeek DayOfWeek;

        // <remarks/>
        [XmlText()]
        public string Value;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public enum DayOfWeek
    {

        // <remarks/>
        Mon,

        // <remarks/>
        Tue,

        // <remarks/>
        Wed,

        // <remarks/>
        Thu,

        // <remarks/>
        Fri,

        // <remarks/>
        Sat,

        // <remarks/>
        Sun
    }

}