// ------------------------------------------------------------------------------
// <autogenerated>
// This code was generated by a tool.
// Runtime Version: 1.1.4322.573
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated.
// </autogenerated>
// ------------------------------------------------------------------------------

using System;
using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=1.1.4322.573.
// 
namespace wsTripXML.wsTravelTalk.wmVoidTicketOut
{
    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class TT_VoidTicketRS
    {

        // <remarks/>
        public Success Success;

        // <remarks/>
        [XmlArrayItem("Warning", IsNullable = false)]
        public string[] Warnings;

        // <remarks/>
        public UniqueIDRS UniqueID;

        // <remarks/>
        public TicketingControl TicketingControl;

        // <remarks/>
        [XmlArrayItem("Error", IsNullable = false)]
        public string[] Errors;

        // <remarks/>
        [XmlElement("Ticket")]
        public Ticket[] Ticket;

        // <remarks/>
        [XmlAttribute()]
        public string EchoToken;

        // <remarks/>
        [XmlAttribute()]
        public DateTime TimeStamp;

        // <remarks/>
        [XmlIgnore()]
        public bool TimeStampSpecified;

        // <remarks/>
        [XmlAttribute()]
        [System.ComponentModel.DefaultValue(TT_IssueTicketRSTarget.Production)]
        public TT_IssueTicketRSTarget Target = TT_IssueTicketRSTarget.Production;

        // <remarks/>
        [XmlAttribute()]
        public double Version;

        // <remarks/>
        [XmlAttribute()]
        public string TransactionIdentifier;

        // <remarks/>
        [XmlAttribute()]
        public int SequenceNmbr;

        // <remarks/>
        [XmlIgnore()]
        public bool SequenceNmbrSpecified;

        // <remarks/>
        [XmlAttribute()]
        public TT_IssueTicketRSTransactionStatusCode TransactionStatusCode;

        // <remarks/>
        [XmlIgnore()]
        public bool TransactionStatusCodeSpecified;

        // <remarks/>
        [XmlAttribute()]
        public string PrimaryLangID;

        // <remarks/>
        [XmlAttribute()]
        public string AltLangID;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class Success
    {
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class Ticket
    {

        // <remarks/>
        public string Name;

        // <remarks/>
        public Fare Fare;



        // <remarks/>
        [XmlAttribute()]
        public string Number;

        [XmlAttribute()]
        public Status Status;

        [XmlAttribute()]
        public string AuthorizationCode;


    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class Fare
    {

        // <remarks/>
        [XmlAttribute()]
        public string Amount;

        // <remarks/>
        [XmlAttribute()]
        public string Currency;
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class TicketingControl
    {

        // <remarks/>
        [XmlAttribute()]
        public TicketingControlType Type;
    }

    // <remarks/>
    public enum TicketTypeType
    {

        // <remarks/>
        Electronic,

        // <remarks/>
        Paper,

        // <remarks/>
        MCO
    }

    // <remarks/>
    public enum TicketingControlType
    {

        // <remarks/>
        OK,

        // <remarks/>
        TF
    }
    public enum Status
    {

        // <remarks/>
        Void,

        // <remarks/>
        NotVoid
    }

    // <remarks/>
    [XmlRoot(IsNullable = false)]
    public class UniqueIDRS
    {

        // <remarks/>
        [XmlAttribute(DataType = "anyURI")]
        public string URL;

        // <remarks/>
        [XmlAttribute()]
        public string Type;

        // <remarks/>
        [XmlAttribute()]
        public string Instance;

        // <remarks/>
        [XmlAttribute()]
        public string ID;

        // <remarks/>
        [XmlAttribute()]
        public string ID_Context;
    }

    // <remarks/>
    public enum TT_IssueTicketRSTarget
    {

        // <remarks/>
        Test,

        // <remarks/>
        Production
    }

    // <remarks/>
    public enum TT_IssueTicketRSTransactionStatusCode
    {

        // <remarks/>
        Start,

        // <remarks/>
        End,

        // <remarks/>
        Rollback,

        // <remarks/>
        InSeries
    }

}