# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: default

steps:

- task: NuGetToolInstaller@1
  inputs:
    versionSpec: '6.6.1'

- task: Cake@2
  inputs:
    script: 'build.cake'
    target: 'OctoPush'
    verbosity: 'Verbose'
