# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: default

steps:
- task: AssembyInfoReader@3
  inputs:
    searchPattern: '.\My Project\AssemblyInfo.vb'

- task: OctopusPackNuGet@6
  inputs:
    PackageId: 'wsTripXML'
    PackageVersion: $(AssemblyInfo.AssemblyFileVersion)
    NuGetDescription: 'Trip XML'
    NuGetAuthors: 'Technology Transfer Corp'
    Include: '"*.dll", "Web.config", "*.asmx", "*.xml", "*.aspx", "bin***.dll", "bin***.config", "bin***.pdb", "App_Data***.*", "Code/bin***.dll", "Tables/BL***.*", "Tables/Decoding***.xml", "Tables/Users***.*"'

